### ISSUE TITLE
Cannot read property 'blockheight' of undefined

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1011]
Branch: `origin/listTrades-grpc`

With LND and Raiden enabled in config but unavailable, `xucli getinfo` throws:
```
~/xud/bin$ ./xucli getinfo
Error: 2 UNKNOWN: Cannot read property 'blockheight' of undefined
```

Other calls work. Log clearly shows that this is because of raiden with a failed `ECONNREFUSED` for every getinfo RPC call:
```
07/06/2019 18:33:33.736 [RPC] debug: received call /xudrpc.Xud/GetInfo
07/06/2019 18:33:33.736 [RAIDEN] error: Error: connect ECONNREFUSED 127.0.0.1:5001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
07/06/2019 18:33:33.736 [RPC] error: Cannot read property 'blockheight' of undefined
```

**Comment by kilrau** [comment]
FWIW: I can't reproduce this on master

**Comment by sangaman** [comment]
Looks like this would happen when an lnd instance is configured but is disabled due to some reason like no macaroon file found. I'm opening a PR with a fix shortly.
