### ISSUE TITLE
[XUD Master Password] CLI fixes

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1021]
Continuation of #912:

* [Hide password input for `xucli unlock` and `xucli create`](https://github.com/ExchangeUnion/xud/pull/1006#issuecomment-499826994)
* [* CLI enhancement, right now `CreateNode` just spits out the 24 word seed in JSON, but we should probably have a message instructing people to write it down, keep it safe, what they can recover with it and how, etc etc...](https://github.com/ExchangeUnion/xud/pull/1006#issuecomment-499826994)

**Comment by sangaman** [comment]
This is partly addressed in #1189. @kilrau, any thoughts on what we should say for the second bullet point? If not I can come up with something on my own that's based off of the message lnd prints out (after all, it's the same seed). But I'll try and deal with that as well so we can close this issue.

**Comment by kilrau** [comment]
Actually, the output is handled by `xud-docker`: https://github.com/ExchangeUnion/xud-docker/issues/63

If you think the call should return that, please include it and let @reliveyy know. After, this can be closed.

**Comment by sangaman** [comment]
Oh gotcha, I can then base off of what docker is currently outputting. My thought is it makes sense to have directly from the cli for anyone that creates an xud node via the cli without docker.

**Comment by sangaman** [comment]
This issue is closed with #1212.
