### ISSUE TITLE
Direct Channel Checks (Updated)

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1027]
- similar to sanity swaps

**Comment by kilrau** [comment]
As just discussed in the call we want to have the check on receiving an order if we have a direct channel with raiden. Issue raised by @offerm

**Comment by sangaman** [comment]
Let's discuss this more today, some thoughts I have:

- Checking on every order received may result in a lot of calls with heavy load.
- If we detect no channel, we'd want to remove all orders for that peer. Maybe we would want periodic checks (starting with the handshake) to occur to account for existing orders?
- We make this check already before we attempt to execute an order, in case of raiden when we detect no direct channels we can deactivate the pair and drop all orders.

**Comment by kilrau** [comment]
> Maybe we would want periodic checks (starting with the handshake) to occur 
How about we store the "direct" channel info as peer property and discard orders which involve tokens, where this property is `false`? Not querying raiden for every order...

And yes, I think it makes sense to periodically hit https://raiden-network.readthedocs.io/en/latest/rest_api.html#get--api-(version)-channels-(token_address) and see if there is a new channel.

**Comment by kilrau** [comment]
Some new thoughts: https://github.com/ExchangeUnion/xud/pull/1347#issuecomment-574684977
