### ISSUE TITLE
ensure jstype proto definitions are permanent

### ISSUE THREAD

**Issue by erkarl** [ExchangeUnion/xud#1038]
This is a follow-up issue to: https://github.com/ExchangeUnion/xud/pull/1036 to ensure we have some mechanism in place to prevent this from happening in the future.

**Comment by sangaman** [comment]
I reopened and rebased https://github.com/lightningnetwork/lnd/pull/2352. Aside from that I'm not that sure what we can do aside from be vigilant when we update the lnd proto definition from the main repo. Any ideas?

**Comment by kilrau** [comment]
@erkarl

**Comment by sangaman** [comment]
Done! https://github.com/lightningnetwork/lnd/commit/7408fe51eea3341801ccc6fa270388b877e6fee4
