### ISSUE TITLE
CLTV fixes

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1043]
This is about 2 features:

- [ ] add buffer to cltv factor (reason: to be sure longer block times don't screw up our 0.25 assumption for litecoin and X for ethereum). Block times can easily vary from 5 to 30 mins on Bitcoin.
- [x] max configurable cltv value for a route (lnd via [switch to sendpayment](https://github.com/ExchangeUnion/xud/pull/1121) which allows to set `cltv_limit`, raiden via [api endpoint](https://github.com/ExchangeUnion/xud/issues/1053#issuecomment-517646132))

**Comment by erkarl** [comment]
If Raiden team is open to a much longer configurable timelock then I'm strongly leaning towards going with that approach since it doesn't involve changing our internal swaps logic. Going with `requester/initiator` changes will increase complexity and could introduce new bugs.

**Comment by kilrau** [comment]
we agreed on starting with patching raiden default and max first, ideally make it configurable. Needs checking some lnbtc routes what are long cltv values out there and then set the maximum of raiden to something high enough that it can include it in any case with a decent buffer. That's our own raiden fork and we assume people will use this in our setup. We keep the option to "force raiden on the second leg" for the future in case these changes don't get merged

**Comment by kilrau** [comment]
Moved Raiden CLTV fixes into separate issues: https://github.com/ExchangeUnion/xud/issues/1052 & https://github.com/ExchangeUnion/xud/issues/1053
