### ISSUE TITLE
Raiden CLTV check

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1052]
1st leg: ln
2nd leg: raiden

At the moment we don't calculate & transform the cltv of raiden to be included in the first leg. This needs to be done. (Test: this should also prevent raiden to be the first leg as of now, since raiden only support very short cltv values)

**Comment by kilrau** [comment]
Problem 1: btc ends up being calculated as 144x faster than eth, whereas it should be eth being 40x faster than btc
Problem 2: Recipient of the 1st leg (maker) doesn't cross-check cltv locktime if it's a raiden payment
Problem 3: Recipient of the 1st leg & 2nd leg (maker+taker) doesn't cross-check token address

**Comment by offerm** [comment]
Created a PR that handle problem 1.
It also prevents raiden from being the firstleg and also checks during the resolver execution that the CLTV is right.
I provided an initail PR. Suggest that @sangaman and/or @erkarl take it from here.

**Comment by kilrau** [comment]
Yes, but the PR will be reviewed and adjusted by @sangaman so that raiden fails on the first leg *because* of the too-short cltv locktime to includ leg 2. The outcome is the same, but the check should *not* be "if raiden = first leg then fail", but maybe I read your PR wrong. In any case, what we want from this PR is "if max cltv on first leg too short to include cltv of leg 2, then fail".

**Comment by kilrau** [comment]
How about https://github.com/ExchangeUnion/xud/issues/1052#issuecomment-506644890 does any of the open PRs already address this? @sangaman
