### ISSUE TITLE
Raiden ERC20 swap integration

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#106]
- Raiden ERC20 swap
- Raiden/Lightning swap

**Comment by sangaman** [comment]
This issue is on hold until Raiden reintroduces swap functionality, which was removed after v0.3.

**Comment by kilrau** [comment]
Waiting for mainnet release. Asked Lefteris to keep us in the loop on the HTLC design, so we can help to make them compatible with ln.

**Comment by kilrau** [comment]
duplicate, closing
