### ISSUE TITLE
Hardcode bootstrap nodes for simnet, testnet

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1061]
simnet = `xud1.test.exchangeunion.com`, `xud2.test.exchangeunion.com`, `xud3.test.exchangeunion.com`
testnet = `xud1.testnet.exchangeunion.com`

**Comment by sangaman** [comment]
I'll need nodepubkeys for these, so once we spin up these nodes and initialize them I can just copy/paste into the code.

**Comment by kilrau** [comment]
Up and running: `02d8ac24fe2952d0d4c9eaa188a1d51ae4d80879fa311a3729a23a15b24f121d6c`


```
testnet > connect 02d8ac24fe2952d0d4c9eaa188a1d51ae4d80879fa311a3729a23a15b24f121d6c@xud1.testnet.exchangeunion.com:8885
D0708 18:00:13.032867384      48 env_linux.cc:71]            Warning: insecure environment read function 'getenv' used
success
```
