### ISSUE TITLE
Go over all in-code "TODO's" to check if there's something "urgent" left

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1071]
And let's open issue for anything non-refactoring/non-beautifying you stumble upon.

**Comment by erkarl** [comment]
I went through the TODOs in the code and didn't notice **critical** issues that we don't already have an issue for.

**Comment by kilrau** [comment]
Ok, thank you so much for doing this. Closing here and pointing at :point_right: from now on issues, not in-code `//TODO`'s
