### ISSUE TITLE
xud not shutting down gracefully

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1073]
On latest master, simnet mode - 100% of the cases:

```
28/06/2019 19:50:16.831 [GLOBAL] info: XUD shutdown gracefully
^C28/06/2019 19:50:20.865 [GLOBAL] info: XUD is already shutting down
^C28/06/2019 19:50:21.067 [GLOBAL] info: XUD is already shutting down
^C28/06/2019 19:50:21.260 [GLOBAL] info: XUD is already shutting down
```

Guess is that there are some new listeners that are not cleaned up properly. Debug logs not at hand, but can get them if you have troubles reproducing.

**Comment by erkarl** [comment]
No need, the issue does reproduce for me as well.

**Comment by kilrau** [comment]
Closed by https://github.com/ExchangeUnion/xud/pull/1077

**Comment by erkarl** [comment]
After applying this patch during my normal development flow I noticed it made graceful shutdowns more reliable, but it didn't fully resolve the issue. I've occasionally experienced non-graceful shutdowns - will keep an eye on it and see if I can replicate the problem. For now we can keep this issue closed.

**Comment by sangaman** [comment]
@erkarl If you discover any steps that lead to an unclean shutdown, let me know. I was debugging with the [wtfnode](https://www.npmjs.com/package/wtfnode) tool and it was quite helpful.
