### ISSUE TITLE
Remove `detectexternalip`

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1092]
this is handled by docker now and code and config option should be removed from xud

**Comment by sangaman** [comment]
What about for users that aren't installing via docker?

**Comment by kilrau** [comment]
Good point.

Well, detecting external IP was always only part of the solution since it ignored ports and to check if they were forwarded and reachable. Which they aren't - in most of the home router cases. @erkarl 's docker solution will do both.

Anyhow, let's talk about [Tor](https://www.torproject.org/) next Tuesday, which will do away with the whole IP address detection / port forwarding problem and I think should be default in future. That's why I believe IP detection shouldn't be an xud core feature anymore. And ... I didn't expect @michael1011  to be that fast.

(On-top TOR might solve our "full mesh network scalability problem", remind me to mention it!)

**Comment by michael1011** [comment]
I think that if people are able to setup their router to forward their port, they will also be able to set their external IP in the config. The only case in which this feature would have made sense is when people don't have a static external IP which would result in having to set the IP again after every restart of their router. And that is kind of an edge case.

Anyways. Let's talk about Tor on next Tuesday and leave the PR alone until then.

**Comment by sangaman** [comment]
Yeah, to me it's a working feature that doesn't add much in the way of complexity or maintenance to the code, so I'd be fine with leaving it in even if it's only going to be useful in a handful of cases.
