### ISSUE TITLE
Higher Raiden balance causes "Assertion failed" error (`channelbalance`)

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1097]
```
xud@xud-test-1:~$ xucli channelbalance
Error: 13 INTERNAL: Assertion failed
```

Reliably reproducable with 25btc in dai. That is 25 times 11500 times 1e18. Looks like something still violates the int64 limit.

**Comment by sangaman** [comment]
Can you confirm whether this is still happening? I lost my raiden channels for testing purposes and am having issues getting them back to properly debug this, but when I simulate a balance of 25 * 11500 for raiden (by hardcoding it in and debugging) I don't get this assertion error.

**Comment by kilrau** [comment]
I can confirm that this still happening. Since the raiden channel manager is working now, you can easily reproduce this by spinning up a docker environment, wait for btc/ltc/weth/dai channels opened to you automatically and then run `channelbalance`. Result:
```
simnet > channelbalance
D0717 12:40:18.323560156     419 env_linux.cc:71]            Warning: insecure environment read function 'getenv' used
Error: 13 INTERNAL: Assertion failed
```

**Comment by sangaman** [comment]
I'm not getting this error with 1,625,000 DAI in docker after setting up as you described. Any ideas?

```
{
  "balancesMap": [
    [
      "BTC",
      {
        "balance": 1250000000,
        "pendingOpenBalance": 0
      }
    ],
    [
      "DAI",
      {
        "balance": 162500000000000,
        "pendingOpenBalance": 0
      }
    ],
    [
      "LTC",
      {
        "balance": 112500000000,
        "pendingOpenBalance": 0
      }
    ],
    [
      "WETH",
      {
        "balance": 500000000000,
        "pendingOpenBalance": 0
      }
    ]
  ]
}
```

**Comment by erkarl** [comment]
Try doing a successful swap and then `channelbalance`.

**Comment by kilrau** [comment]
That's exactly how I saw it so far too. Initially all good, then once the raiden balance changed, it throws `Assertion failed`.

**Comment by sangaman** [comment]
I finally was able to reproduce while debugging, the problem was not with a value that's too high but rather a fractional value that wasn't rounded. Simple fix.
