### ISSUE TITLE
LND channels take long to get re-enabled

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1112]
The issue: Currently, if you take your xud setup down (with channels open to some other nodes) for >20 minutes and bring it up again, you will need to wait 19 minutes for channels to get re-enabled and swaps to work.

As per https://github.com/lightningnetwork/lnd/issues/3328#issuecomment-512971540 we should change lnd's config, question is how.

Options 
a)`--chan-disable-timeout`, but this will increase routing failures drastically since nodes will try to route via disabled channels
b) `--chan-enable-timeout` and configure the timeout to something short and check that it works in both directions. Channels get disabled after 10s but also re-enabled after 10s.
c) ?

**Comment by kilrau** [comment]
Second question is the right place to do this. `xud` native or docker.

**Comment by sangaman** [comment]
xud native can't set lnd command args or config flags, so this would be for the docker/simnet repos I believe.

**Comment by kilrau** [comment]
Which option do you prefer? I would vouch for b) with something like 10s, since this is the "proper" way and should work accross Simnet/Testnet/Mainnet.

**Comment by kilrau** [comment]
Decision: 10s for Simnet & Testnet. Mainnet stays with 20 mins.

**Comment by offerm** [comment]
10s chan-enable-timeout implemented in xud-simnet-start (simnet native).

Taking myself of the Assignees list. @kilrau
