### ISSUE TITLE
match with ownorder shows swap with peerorder

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1113]
```
simnet > buy 0.7 btc/dai 9998
D0719 11:27:40.078404888     608 env_linux.cc:71]            Warning: insecure environment read function 'getenv' used
no matches found
remaining 0.7 BTC entered the order book as 37adb9e0-aa18-11e9-93ed-b74d6a7415f5
simnet > sell 0.7 btc/dai 9998
D0719 11:27:47.607656463     628 env_linux.cc:71]            Warning: insecure environment read function 'getenv' used
swapped 0.7 BTC with peer order 30d983e0-a975-11e9-a1f5-8da2255d491b
```

orderbook, channelbalance didn't change - that was definitely a match with the previous own order.

**Comment by sangaman** [comment]
@kilrau Do you have more details on this? It looks like it might be related to #1206. Something would be very off if it's reporting that it's performing swaps but is actually matching with own orders behind the scenes, I'm not sure how that could possibly be happening and it's not something I ever recall observing.

**Comment by kilrau** [comment]
Well this issue is quite ... dated. I'll close it for now and we'll open new issue for anything we encounter. Thanks for https://github.com/ExchangeUnion/xud/pull/1454 !
