### ISSUE TITLE
Monitor "pending swaps"

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1115]
This issue discusses a new architecture for https://github.com/ExchangeUnion/xud/pull/1081: a monitor for pending (non-complete, non-failed) swaps

**Comment by sangaman** [comment]
This describes the approach I've implemented in #1081: https://github.com/ExchangeUnion/xud/pull/1081#issuecomment-518370083

**Comment by kilrau** [comment]
Closing here, covered by #1079.
