### ISSUE TITLE
Add `sendpayment` calls to SwapClient

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1118]
Since we can expect users wanting to send regular lightning/raiden payments and L2 payment calls are not easy to use/learn (e.g. on raiden) we want to expose them in a simplified manner via xud's grpc and CLI as well:

Add to SwapClient interface, implement for LNDClient only (for now):
- [ ] `pay <Invoice>`
LND Call: https://api.lightning.community/#sendpaymentsync
- [ ] `send <amount> <currency> <XudPubKey/LndPubKey/0xAddress>`
LND Call: EDIT: available as ` --keysend` in https://api.lightning.community/#sendpayment (even though I couldn't make it work in some tests)

**Comment by kilrau** [comment]
Not that interesting for lnd, since `lncli` can be comfortably used from within xud ctl, but *very* interesting for raiden.

**Comment by engwarrior** [comment]
Pls provide estimate for this task.

**Comment by kilrau** [comment]
I'd want to postpone this for ~one month. @engwarrior
