### ISSUE TITLE
Cancel Raiden payment when swap fails

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1123]
Enhancement of https://github.com/ExchangeUnion/xud/pull/1081:

When `xud` crashes between `SwapCreated` and `SwapCompleted`: we currently only cancel ln invoices for the swap, but don't do anything for raiden since there is no `cancelpayment` or `refundpayment` call. One just has to wait until the payment times out.

This issue is about adding a `cancelpayment` call to the raiden client and enhance #1081 to utilize it.

**Comment by sangaman** [comment]
I believe this is obsolete with the new approach by raiden to keep retrying the resolve request until it gets an intelligible response.

This is tangentially related to #1282, in that when we want to "cancel" an incoming payment we should definitively let raiden know via the resolver response.
