### ISSUE TITLE
cltv/cltvdelta renaming to `lockDuration` and `lockBuffer`

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1132]
Enhancement according to [#1082 (comment)](https://github.com/ExchangeUnion/xud/pull/1082#discussion_r309026424): to globally rename all `cltv` to `lockDuration` and `cltvdelta` to `lockBuffer` to unify things and move away from the lightning-specifc `cltv` naming. Add comment in config to explain what `lockBuffer` is.

**Comment by sangaman** [comment]
This was addressed in https://github.com/ExchangeUnion/xud/pull/1082/commits/68b8c0f1ca654a743d9cc45134b06c43e8e90c81.
