### ISSUE TITLE
Reconnection log entries don't contain xud pubkey

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1136]
### Background

log entries for reconnection don't contain xud pubkey

### Your environment

* version of `xud`: latest master
* which operating system (`uname -a` on *Nix):
* version of `btcd`, `bitcoind`, `ltcd`, `litecoind`, `geth`, `parity`, `raiden`, `lnd` or other chain backend:
* any other relevant environment details:

### Steps to reproduce

make xud reconnect and fail and watch the log, see below

### Expected behaviour

```
xud_1     | 08/08/2019 16:56:28.958 [P2P] debug: Connection attempt #1 to peer 03c112f7fa44b65c6371d012c8d45132cf7866570d1045be70370a001a00d2407e@b7mxwwrk7sif6fp5vfph62k6el4pu4on53hxxd6gg6q7i6nu7u7h4syd.onion:8885 failed: connect ECONNREFUSED 224.0.0.5:8885. retrying in 5 sec...
```

### Actual behaviour

```
xud_1     | 08/08/2019 16:56:28.958 [P2P] debug: Connection attempt #1 to peer (b7mxwwrk7sif6fp5vfph62k6el4pu4on53hxxd6gg6q7i6nu7u7h4syd.onion:8885) failed: connect ECONNREFUSED 224.0.0.5:8885. retrying in 5 sec...
```

**Comment by sangaman** [comment]
@kilrau There are other log messages where we only log the peer's address for an outbound peer where the node pub key has not been established via the handshake yet, should we update those as well? I figure we could standardize on the format used in your "expected behavior" above.

**Comment by kilrau** [comment]
That sounds good, yes - could you open an issue describing the places where this needs to be adjusted?

**Comment by sangaman** [comment]
The additional changes were fairly minimal so I just went ahead and put them in a PR: #1151.

**Comment by kilrau** [comment]
even better
