### ISSUE TITLE
Create a list of most common build failures

### ISSUE THREAD

**Issue by erkarl** [ExchangeUnion/xud#1139]
Our Travis builds are failing quite often with "false positives" - meaning that if you were to restart the build it would eventually pass. 

The first step to go through old build logs and compile a list of failing log outputs to this issue (and how many times they occur):
https://travis-ci.org/ExchangeUnion/xud/builds

**Comment by erkarl** [comment]
Alternative approach is to create a new test PR and restart it many times.

**Comment by kilrau** [comment]
I believe we can close this. Please re-open if there's anything more you think should be done @erkarl
