### ISSUE TITLE
Generate and use TLS certificates for gRPC layer

### ISSUE THREAD

**Issue by sangaman** [ExchangeUnion/xud#114]
Currently, our gRPC layer is not using a TLS certificate. We'll need to generate one as part of our initialization process if none exists, and use it for all rpc calls similar to how we use the `lnd` cert for calls in `LndService.ts`.

**Comment by kilrau** [comment]
Includes Macaroons authentication on RPC Calls

**Comment by sangaman** [comment]
Closing this and will open a separate issue for macaroons.
