### ISSUE TITLE
Refactor XUClient 

### ISSUE THREAD

**Issue by sangaman** [ExchangeUnion/xud#115]
`XUClient.ts` currently has quite a bit of code duplication and use of `any` types. It should be refactored to provide better type safety and code reuse. It can use the generated types and methods in `xudrpc_pb.d.ts` and `xudrpc_pb.js`. Another possible approach would be to generate a static gRPC client, as described here: https://github.com/grpc/grpc/tree/master/examples/node/static_codegen.

**Comment by itsbalamurali** [comment]
@sangaman I am closing this as the PR Fix has been already merged.
