### ISSUE TITLE
Add tor configuration option

### ISSUE THREAD

**Issue by erkarl** [ExchangeUnion/xud#1154]
Now that `xud-docker` is using Tor by default we'll have lots of nodes with `hash.onion` advertised addresses. The nodes that are not using Tor will be unable to connect to those addresses.

I propose to have a `tor = false` configuration option that for now will prevent `xud` from trying to connect to those addresses.

**Comment by hatmer** [comment]
There are proxy services that allow regular internet nodes to connect to Tor hidden services, they are pretty sketchy though. Eventually we could build one to allow full connectivity from non-tor to tor nodes.

**Comment by erkarl** [comment]
>  they are pretty sketchy though.

Agreed. For now I'd go with a simple solution and just not connect to onion addresses if Tor is disabled.

**Comment by sangaman** [comment]
Seems like a good approach to me, and fairly standard from what I've seen in other services where tor is optional. What I'm not sure about is whether tor should be enabled or disabled by default. Maybe it can be disabled by default but if we detect an advertised tor address then we enable it?

**Comment by engwarrior** [comment]
Pls provide estimate for this task.

**Comment by flicker-harmony** [comment]
@kilrau @erkarl @sangaman how it can be determined in current xud code if Node has hash.onion advertised address? For now I can't find anything related to it in current Pool Config, Peer info and Xud configs.

**Comment by engwarrior** [comment]
@kilrau @erkarl @sangaman how it can be determined in current xud code if Node has hash.onion advertised address? For now I can't find anything related to it in current Pool Config, Peer info and Xud configs.

**Comment by erkarl** [comment]
@engwarrior https://github.com/ExchangeUnion/xud/blob/master/sample-xud.conf#L67
