### ISSUE TITLE
Make locktime logging clearer

### ISSUE THREAD

**Issue by offerm** [ExchangeUnion/xud#1157]
```
xucli sell 0.1 ltc/btc 0.0077
```
first leg - ltc
second leg - btc

from maker's log:
```
16/08/2019 12:40:23.955 [SWAPS] debug: New deal: {"proposedQuantity":10000000,"pairId":"LTC/BTC","orderId":"cdbf2030-c012-11e9-ba33-1dd8acf2144f","rHash":"0939c9af013e743e55704ee81ed7413f190417dd17dc334766b96f7e7893542b","takerCltvDelta":40,"price":0.0077,"isBuy":true,"quantity":10000000,"makerAmount":10000000,"takerAmount":77000,"makerCurrency":"LTC","takerCurrency":"BTC","makerUnits":10000000,"takerUnits":77000,"takerPubKey":"03c0af90724ce74c0c79e9c05aea0b0bf5f87e34fd35ce22c4f13459d31aad6d2c","destination":"03c0af90724ce74c0c79e9c05aea0b0bf5f87e34fd35ce22c4f13459d31aad6d2c","peerPubKey":"03fcce59c115970614f0d6c098f6d676b8c76a84c5047394836dd39f1e717383c3","localId":"cdbf2030-c012-11e9-ba33-1dd8acf2144f","phase":0,"state":0,"role":1,"createTime":1565959223954}
16/08/2019 12:40:23.961 [LND-BTC] debug: got 1 route(s) to destination 03c0af90724ce74c0c79e9c05aea0b0bf5f87e34fd35ce22c4f13459d31aad6d2c: 62043,1,77001,17109500441133056,2500000000,77000,1,62003,77000000,1077,036f9b004f047283b33a640bc4afdd26e2eb82e73938f8ac0796641ad20dc5bdd4,66704071922352128,2500000000,77000,,62003,77000000,,03c0af90724ce74c0c79e9c05aea0b0bf5f87e34fd35ce22c4f13459d31aad6d2c,1077,77001077, finalCltvDelta: 40
16/08/2019 12:40:23.969 [SWAPS] debug: got block height of 61963 for BTC
16/08/2019 12:40:23.969 [SWAPS] debug: choosing a route with total time lock of 62043
16/08/2019 12:40:23.970 [SWAPS] debug: route time lock: 80
16/08/2019 12:40:23.970 [SWAPS] debug: maker client lock buffer: 576
16/08/2019 12:40:23.970 [SWAPS] debug: CLTV delta factor: 4
16/08/2019 12:40:23.970 [SWAPS] debug: makerCltvDelta: 896
16/08/2019 12:40:23.982 [LND-LTC] debug: added invoice of 10000000 for 0939c9af013e743e55704ee81ed7413f190417dd17dc334766b96f7e7893542b with cltvExpiry 896
```
The prints above explains the maker's cltvdelta (LTC).

debug: route time lock: 80 . <-------- BTC units
debug: maker client lock buffer: 576 <------ LTC units
debug: CLTV delta factor: 4 
debug: makerCltvDelta: 896 <-------- LTC units

First issue:

IMHO, everything should be in the same units or another line shoud be used to convert 80 t0 320.

Second issue: 
Why are we adding a lock buffer of one day? I understand if we add a small number of blocks to allow compensate for mining speed different from average. But one day is very high.
And if we have a justification for one day for the maker, shouldn't we also do that for the taker?

**Comment by kilrau** [comment]
> First issue:
> IMHO, everything should be in the same units or another line shoud be used to convert 80 t0 320.

Agree that it's very hard to read. How about adding units and adding the other leg's unit in parentheses for easy comparison:
```
debug: route time lock: 80 BTC blocks (~ 320 LTC blocks)
debug: maker client lock buffer: 576 LTC blocks (~ 144 BTC blocks)
```

> Second issue:
> Why are we adding a lock buffer of one day? I understand if we add a small number of blocks to allow compensate for mining speed different from average. But one day is very high.

Not really. I checked the [average daily block times of the last 2 years](https://bitinfocharts.com/comparison/bitcoin-confirmationtime.html#2y), and the extreme was 18 minutes on 2017/11/11 +12. Add a little bit of buffer to that and we can double our security assumption to 20 minutes block times for BTC on leg 2. Further, since the default CLTV delta on lnd was just [recently decreased from 144 to 40 blocks](https://github.com/lightningnetwork/lnd/pull/2759/commits/c302f1ea3a91ccfa382d56851d23f4c73656208c), I still took 144 btc blocks as basis here. Or just take a 4-hop route with the new 4*40=160 btc blocks. Also, let's not forget that the block time variance on leg one can go into the other direction - e.g. BTC on leg 2 20 minute block times and ltc on leg 1 one minute block times.

Taking all that into account I think a day makes sense. Sorry for not involving you in this. It was result of a discussion last week.

> And if we have a justification for one day for the maker, shouldn't we also do that for the taker?

As per your words, the maker is at risk, not the taker :)

**Comment by kilrau** [comment]
Also, I see a couple of renaming to be done in the log output above:

`total time lock`
` route time lock`
`maker client lock buffer`
`CLTV delta factor`
`makerCltvDelta`

should all be cleaned to `lockDuration` and `lockBuffer`. `CLTV delta factor` maybe as something like `lockConversionFactor`.

**Comment by sangaman** [comment]
> Why are we adding a lock buffer of one day?

We had been using 1 day previously, 144 for BTC and 576 for LTC are 1 day worth of blocks and that was being added to the total delta of the 2nd leg. So that didn't change recently, just the way it's configured has changed, with 1 value in hours that's calculated for each chain.

But I think it's important that this is fairly long because we need to be certain that the 1st leg payment doesn't expire before the 2nd leg, and since the two chains don't move at exactly the same pace it's more fragile than hops along the same chain.

**Comment by kilrau** [comment]
Please let me know if you don't agree with the "math" above to justify the 1 day `lockBuffer` @offerm 

@sangaman so can we make this issue about making logging clearer as per [1](https://github.com/ExchangeUnion/xud/issues/1157#issuecomment-522023669) & [2](https://github.com/ExchangeUnion/xud/issues/1157#issuecomment-522035726) above? Open for suggestions how, but I agree with @offerm  that the current logging is very hard to read.

**Comment by offerm** [comment]
@sangaman 

> We had been using 1 day previously, 144 for BTC and 576 for LTC are 1 day worth of blocks and that was being added to the total delta of the 2nd leg. So that didn't change recently, just the way it's configured has changed, with 1 value in hours that's calculated for each chain.

What we did is to convert  the `cltv_delta` of the maker to `lockBuffer`. This, IMHO, is wrong. The taker and the maker should have `cltv_delta` and should be able to control them (config) separately from the `lockBuffer`. 
Why is it wrong?
the `cltv_delta` of the maker is a value which should be decided by the maker, is fixed and is not impacted by the route of the second leg.
On the other hand, the lockBuffer should be proportional to the `lockDuration` of the second leg (not fixed). 
@kilrau A fix value for lockBuffer allows the taker to game the number. He can use a direct channel for the first leg and an indirect channel on the second leg (by having a front node). With this setup he can make the `lockDuration` of the second leg as long as he wishes increasing the risk of the first leg expiring before the second leg.

IMHO, The `lockBuffer` should be dynamically computed based on the `lockDuration` of the second leg. Assuming that the average block time on the second leg increases 100% while at the same time the first leg decrease by 50% is very drastic.  I agree that there should be a lockBufferFactor (>1) that we should use.

**Comment by sangaman** [comment]
> IMHO, The lockBuffer should be dynamically computed based on the lockDuration of the second leg. Assuming that the average block time on the second leg increases 100% while at the same time the first leg decrease by 50% is very drastic. I agree that there should be a lockBufferFactor (>1) that we should use.

Yeah I agree with this, it's just not something I or anyone else has designed or implemented yet. The lock buffer config can be a factor or something like that. My point above was just that the behavior there hasn't changed with regards to adding a day to the 2nd leg to calculate the cltv delta for the last hop of the first leg.

I'm going to treat this issue as just addressing the logging improvements so discussion about changing the buffer logic can be separate.

**Comment by kilrau** [comment]
> IMHO, The lockBuffer should be dynamically computed based on the lockDuration of the second leg. Assuming that the average block time on the second leg increases 100% while at the same time the first leg decrease by 50% is very drastic. I agree that there should be a lockBufferFactor (>1) that we should use.

Agree, very good point @offerm 

> I'm going to treat this issue as just addressing the logging improvements so discussion about changing the buffer logic can be separate.

Also agree, opened separate issue: https://github.com/ExchangeUnion/xud/issues/1164
