### ISSUE TITLE
Add flexibility on second leg's `lockDuration`

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1165]
Status Quo: currently the maker calls `QueryRoutes` to get a route with a specific total cltv and specific cltv_limit. Chances are high that `SendPayment` is limited to this one specific route (and maybe some more routes with shorter cltv values).

Idea: add an equivalent of e.g. 40 BTC blocks to the total cltv of the returned route to allow `SendPayment` to use routes with slightly higher cltv values and increase routing success. 

TBD: Raiden?

**Comment by sangaman** [comment]
To elaborate slightly, currently when we `SendPayment` from maker to taker we are restricted to routes with equal or lower total time lock/cltvdelta compared to the first route we get back when calling `QueryRoutes` to the taker. If we add a buffer of 1 (or maybe 2) hop's worth of default cltv delta (40 blocks for bitcoin) and add that to what we use for `cltvLimit` and `makerCltvDelta` then we could conceivably increase the number of potential routes for a successful payment should the first route fail.

**Comment by sangaman** [comment]
This does not apply to Raiden as long as we are still requiring direct channels. Once we move past that we can keep this approach of adding some flexibility to picking a route in mind.

**Comment by kilrau** [comment]
I think we should to take care of raiden too in this issue, since it is our near-term goal to support have multi-hop raiden payments.

**Comment by sangaman** [comment]
The way I implemented it in the PR, it would apply to Raiden too *when* we start looking for routes besides the direct one.
