### ISSUE TITLE
Show git commmit as version number (when not running a release)

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1171]
Status Quo: At the moment running latest master shows the last release as `version`, which is confusing at best.

What we want: set the  "version" field in (e.g. `xucli getinfo`) to the latest git commit hash and only to a release name if it's indeed the release

How: some kind of script that fetches the hash of the latest git commit and writes it to a TypeScript file. Then execute this script before `npm run compile`. Like this, the commit hash is set at compile time.

**Comment by sangaman** [comment]
Showing both the package.json version and the git commit hash would be nice I think.

**Comment by kilrau** [comment]
@rsercano @michael1011 asked to take over

**Comment by rsercano** [comment]
Thats fine Kilian

2 Eyl 2019 Pzt 17:18 tarihinde Kilian Rausch ⚡️ <notifications@github.com>
şunu yazdı:
