### ISSUE TITLE
Fix gRPC REST Web Proxy

### ISSUE THREAD

**Issue by sangaman** [ExchangeUnion/xud#118]
We have defined a REST service in our `xudrpc.proto` file with the aim of using it to spin up an HTTP REST service with `express`. Currently, our implementation using the `grpc-dynamic-gateway` package is throwing errors, described briefly in #103. We should either fix the existing implementation or, preferably, implement a different approach of either writing our own dynamic REST gateway module in typescript for use in this project, or generating a REST server statically using `grpc-gateway`.

**Comment by itsbalamurali** [comment]
PR #127 has been merged and it addresses this issue.
