### ISSUE TITLE
Integrate security and instability simulations tests into travis

### ISSUE THREAD

**Issue by sangaman** [ExchangeUnion/xud#1220]
Currently, we have `security` and `instability` simulation tests that rely on the `adversarial/breakswap` and `instability` branches, respectively. These tests are not run in travis currently, and the branches they rely on need to be updated manually to keep up with `master`. They also may need to use commits from a feature branch to test new changes, which may cause issues should we have two pending PRs simultaneously that impact these tests.

Another concern is that, if we don't run these tests with every PR that could potentially cause them to break, we won't know which commits caused the failure if several were merged since the last known successful run.

This issue tracks how we can resolve these issues without excessively lengthening the time of travis builds or introducing code into the `master` branch that cause side effects or require much maintenance.

One potential solution may be to dynamically apply the changes for the modified branches when the tests are run, perhaps by attempting to cherry-pick the changes on top of the current code. Another may be to automatically update the `adversarial/breakswap` and `instability` branches whenever `master` is updated via travis script. I'd need to do some research/poking around to see how feasible these solutions might be.

**Comment by LePremierHomme** [comment]
I think that applying a git patch, which will be defined in the test code, can work. It might get outdated due to the line numbers, so it will require some maintenance.

This will also spare us from downloading the custom xud client, since the canonical one will be used instead (after being patched).

What do you say?

**Comment by kilrau** [comment]
fine with me. wdyt? @sangaman

**Comment by sangaman** [comment]
Yeah that sounds like a good idea actually - it's the same amount of maintenance as keeping the separate branches up to date. So when we run the the other tests, we recreate the branch off the latest code and then apply the patch automatically?

**Comment by LePremierHomme** [comment]
Yes.

It would be possible to create a patch per test case and to remove the reliance on cmd args for the differentiation, but I think it will introduce much higher maintenance over head, so i'll probably use one patch for all tests (same as one custom branch).

**Comment by LePremierHomme** [comment]
Closed by #1507 & #1534
