### ISSUE TITLE
Enhancement of `listtrades`

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1232]
* `Completed at`: Timestamp (formatted, json can be unix)
* `Order ID`: UUID of the original order, can be the OrderID of multiple trades in the event of partial fills. abbrev. in formatted output, full in json output.
* `Trade ID`: rhash , abbreviated in formatted output, full in json output
* `Price per ETH`: `0.02 BTC`
* `Buy (Received)`: `50 ETH`
* `Sell (Sent)`: `1 BTC`
* `Add. Network Fees`: `0.0000004 BTC` 
* `Role`: Taker/Maker
* `Peer`: Alias

And probably we can close https://github.com/ExchangeUnion/xud/pull/625, I see a huge overlap and would want to avoid confusion by having two very similar calls listing trade/swap history.

**Comment by kilrau** [comment]
Took https://github.com/ExchangeUnion/xud/pull/1243#issuecomment-627914754 and changed `Date` -> `Timestamp`
```
Trading Pair
Amount
Side
Price
```
condensed this into (imho even better readable):
```
Buy (Received): 1 ETH
Sell (Sent): 0.1 BTC
```

Not necessary imo:
```
Total payment
Order Type (Limit / Market)
```

**Comment by kilrau** [comment]
I thought to leave routing fees out of the buy/sell amount to keep them clean and comparable among peers. That's why `Add.` Do you think that's clear?

Also I thought about renaming `Add. Routing Fees` to `Add. Network Fees` since there will be traders who don't know what and why routing fees and I think there will be different fees, e.g. for collateralization, new channels, inbound liquidity and not just routing fees. So I thought `Network Fees` is more generic and easier to digest for most. Let me know what you think.

**Comment by sangaman** [comment]
> So I thought `Network Fees` is more generic and easier to digest for most. Let me know what you think.

I like this naming, but before we can display it we need to preserve it. I'm tracking it in #1565.
