### ISSUE TITLE
Mainnet is failed to load

### ISSUE THREAD

**Issue by fagunbhavsar** [ExchangeUnion/xud#1234]
### Background
Mainnet is not at all launching, showing failed to launch

### Your environment
* version of `xud`: 
* which operating system (`uname -a` on *Nix): Ubuntu 18.04
* version of `btcd`, `bitcoind`, `ltcd`, `litecoind`, `geth`, `parity`, `raiden`, `lnd` or other chain backend:  Please refer [Stopped containers' details](https://gist.github.com/fagunbhavsar/66f86f04bba4c05270dbb88b9c2966b2)
* any other relevant environment details:

### Steps to reproduce

On Ubuntu EC2 instance --> Install Docker and Docker-compose
Run docker & install xud
Run xud through bash
Validate mainnet connection

### Expected behaviour
Mainnet should get connected

### Actual behaviour
Mainnet is failing to load

**Comment by kilrau** [comment]
Fix should be ready to test today, will ping you.

**Comment by kilrau** [comment]
Fixed by https://github.com/ExchangeUnion/xud-docker/pull/165 and https://github.com/ExchangeUnion/xud/pull/1241
