### ISSUE TITLE
Change xud 8886/8887 ports depending on active network 

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1239]
Enhancement of https://github.com/ExchangeUnion/xud/issues/1238: We discussed that in the long run we would want 8886/8887 to change with the network too.

Reason: This avoids port conflicts when running multiple `xud` on different networks natively on the same system.

Dependency: xud-docker to adjust ports

**Comment by engwarrior** [comment]
Pls provide estimate for this task.

**Comment by kilrau** [comment]
We'd need this for https://github.com/ExchangeUnion/xud-docker/issues/282
