### ISSUE TITLE
xud should return "locked" not "unimplemented" when it's up and locked

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1244]
Currently `xud` returns `UNIMPLEMENTED` when it's up, but locked. It should return `LOCKED` with the cli hint `xud is LOCKED. Use "xucli unlock <password>" to unlock the xud node.` or similar

**Comment by sangaman** [comment]
This was closed by #1302. The message is `xud is locked, run 'xucli unlock' or 'xucli create' then try again`.
