### ISSUE TITLE
Failed seedutil call prints the seed in the logs

### ISSUE THREAD

**Issue by erkarl** [ExchangeUnion/xud#1254]
When the call to `seedutil` fails we're printing the seed in the logs.

https://github.com/ExchangeUnion/xud/blob/master/lib/swaps/SwapClientManager.ts#L158

```
xud_1        | 27/09/2019 09:22:24.879 [RAIDEN] warn: could not create keystore: Error: Command failed: ./seedutil/seedutil -pass= -path=/root/.ethereum abstract destroy cupboard medal gallery horse mandate add have animal half shield series first other develop canyon rain skill segment oil top fox clock
xud_1        | /bin/sh: ./seedutil/seedutil: not found
```

I'm wondering if we completely want to remove that error message or still display it when the log level is set to something like `trace`?

**Comment by kilrau** [comment]
> I'm wondering if we completely want to remove that error message or still display it when the log level is set to something like trace?

I would completely remove it.  A seed should never end up in the logs, no matter the log level and I don't see how we can do that in fail-safe way.
