### ISSUE TITLE
Simplify wallet created output

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1263]
How it is:
```
The following lnd wallets were initialized: BTC, LTC
The keystore for raiden was initialized.
```

How it should be:
```
The following wallets were initialized: BTC, LTC, ERC20(ETH).
```

**Comment by sangaman** [comment]
My concern with this suggested change is that there isn't an "ETH" wallet per se, it could be that we're not going to be trading ETH at all but rather various ERC-20 tokens. I was trying to most clearly convey which L2 clients were initialized.

**Comment by kilrau** [comment]
> I was trying to most clearly convey which L2 clients were initialized.

But users shouldn't care much about clients, only about assets. Since there is also ERC20 on ETC and others `ERC20(ETH`, `ERC20(ETC)`.
