### ISSUE TITLE
Resolve unknown hashes from database

### ISSUE THREAD

**Issue by erkarl** [ExchangeUnion/xud#1264]
Offshoot from: https://github.com/ExchangeUnion/xud/pull/1262#discussion_r330678588

**Comment by kilrau** [comment]
could you explain @erkarl

**Comment by erkarl** [comment]
I think the comment above explains it pretty clearly. Xud holds the preimage in memory and the swap client requests it, but we don't actually wait for confirmation that the swap client has processed it. If the swap client requests the preimage again xud will respond with unknown preimage because it's no longer in the memory (but we still have it in the database).

The solution would be to also query the database for the preimage if we cannot find it in memory.
