### ISSUE TITLE
xud sometimes not stopping gracefully via SIGTERM or shutdown

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1278]
Discovered on master pre `1.0.0-mainnet` tag by @offerm 

```
admin@lightning:~ $ sudo systemctl start xud
admin@lightning:~ $ sudo systemctl stop xud
admin@lightning:~ $ sudo systemctl status xud
● xud.service - xud Daemon
   Loaded: loaded (/etc/systemd/system/xud.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Thu 2019-10-03 16:57:26 -03; 3s ago
  Process: 30032 ExecStart=/bin/bash /home/bitcoin/scripts/run_xud (code=killed, signal=TERM)
 Main PID: 30032 (code=killed, signal=TERM)
    Tasks: 12 (limit: 2319)
   Memory: 53.1M
   CGroup: /system.slice/xud.service
           └─30033 node /home/bitcoin/github/xud/bin/xud --mainnet --lnd.LTC.disable

Oct 03 16:57:22 lightning systemd[1]: Started xud Daemon.
Oct 03 16:57:26 lightning systemd[1]: Stopping xud Daemon...
Oct 03 16:57:26 lightning systemd[1]: xud.service: Main process exited, code=killed, status=15/TERM
Oct 03 16:57:26 lightning systemd[1]: xud.service: Succeeded.
Oct 03 16:57:26 lightning systemd[1]: Stopped xud Daemon.
admin@lightning:~ $ ps -ef |grep xud
bitcoin  30033     1 61 16:57 ?        00:00:07 node /home/bitcoin/github/xud/bin/xud --mainnet --lnd.LTC.disable
admin    30074 28920  0 16:57 pts/1    00:00:00 grep --color=auto xud
```

Please confirm that this is still the case on latest master @offerm , then @sangaman can take over.

**Comment by michael1011** [comment]
@offerm what does your `xud.service` file look like? Did you use [the one from the docs](https://docs.exchangeunion.com/development/native-installation#installing-from-npm)?

**Comment by kilrau** [comment]
To be done: test manual xud setup with sample service fail and test if it starts/stops properly.

**Comment by engwarrior** [comment]
Pls provide estimate for this task.

**Comment by sangaman** [comment]
There are still a handful of scenarios where xud doesn't shutdown gracefully given a sigterm or shutdown command, I've tried a couple of times to diagnose what the issue is but with no success so far. I don't think it's related to systemd necessarily, so I will rename this issue and use it to track general shutdown issues.

**Comment by kilrau** [comment]
I found one more: when xud is `Waiting for lndbtc admin.macaroon` it doesn't react to shutdown/sigterm

**Comment by kilrau** [comment]
Can you help testing if in above two scenarios (easy reproducable with a new xud-docker environment, just don't "create") xud is still not shutting down gracefully? If it works now, we can close here. @raladev

**Comment by raladev** [comment]
got it yesterday with native setup twicely and for both attempts i got failed ETH/BTC swap before. So, it definitely can be reproduced now using combined setup + buy ETH/BTC order, but I can try to reproduce it with only docker env, oke.

**Comment by kilrau** [comment]
Closing here in favor of https://github.com/ExchangeUnion/xud/issues/1668
