### ISSUE TITLE
achilles heel

### ISSUE THREAD

**Issue by offerm** [ExchangeUnion/xud#1282]
https://github.com/raiden-network/raiden/pull/5025 was merged to Raiden.

IMHO, this open the door for a "not atomic swap".

consider raiden as first leg and lnd as second leg. Alice and Bob agreed on a swap and swap started. Alice issue first leg to Bob, Bob's xud called from raiden and issued the second leg. Now, there was some kind of a problem on LND and bob's resolver returned HTTP 500 to raiden.

Outcome - alice got paid (second leg). Bob got the secret from Alice. Bob didn't get his payment from Alice. resolving the payment on-chain by Bob is very hard and practically impossible. 

I haven't done full analysis of xud to check if there is a scenario that can cause it. Even if it is hard to find one now, we can't be sure that we will not add one in the future.

The resolution IMHO is that the resolver will only send back HTTP codes 200 (with secret)  and 404 (not found). We can consider other codes if these represents situations that we understand. But 500 and other generic codes should never be  used.

**Comment by offerm** [comment]
Raiden, when getting any code which it does not clearly understand should retry. If it gets 500 it must retry and should not assume that the maker does not have the secret.

If the request is not valid (400) raiden should assert(False) and crash.

**Comment by erkarl** [comment]
Nice catch @offerm - I haven't tested this manually, but if I'm reading (the code)[https://github.com/raiden-network/raiden/pull/5025/files) correctly then Raiden will stop querying for the preimage from xud after 500 response code. This should not happen.

**Comment by kilrau** [comment]
One more point to consider: if raiden with a resolver configured does a *regular* raiden payment, it will ask the resolver for the preimage, resolver returns 404 and raiden continues and asks initiator for preimage.

**Comment by sangaman** [comment]
I am thinking that if we want to definitively inform raiden that a resolver request permanently failed, perhaps we should not rely on HTTP status codes for that at all. They are, by design, somewhat broad and not exactly intended for our use case in the resolver (which technically need not use HTTP at all, it would work just as well with TCP).

Perhaps what we should do then is return a JSON body in the error response with a `retry` property that is either `true` or `false`. If it is `true` - or if raiden does not receive a valid response - then raiden retries. If it is `false` then raiden will stop retrying.

**Comment by kilrau** [comment]
> Perhaps what we should do then is return a JSON body in the error response with a retry property that is either true or false. If it is true - or if raiden does not receive a valid response - then raiden retries. If it is false then raiden will stop retrying.

That actually sounds like a good compromise. We can give detailed error info in the JSON body and clearly indicate if to retry or not while avoiding anyone else "accidentally" returning a 500 code and make raiden stop retrying.

What do you think? @offerm @erkarl

**Comment by erkarl** [comment]
I'm good with the proposed solution from @sangaman.

**Comment by offerm** [comment]
Me too.

**Comment by offerm** [comment]
Thinking more about it:

a. providing retry property in a json object will not take away the need to handle all kinds of HTTP errors.  The raiden sind, when getting an HTTP code that it does not know how to handle must retry. 

b. The outcome of a raiden call to the resolver can only be:
i) the preimage - swap continues
ii) an response saying that the resolver will never have  the preimage - payment continues
iii) invalid request (format error or something like that) - raiden should crash
Any thing else must convert to a retry.

Doing this with json just complicates things since we need to check both HTTP and the json itself. 

My suggestion is to go back to the 200/404 we had before. 

Since we have only 2 outcomes

**Comment by sangaman** [comment]
> ii) an response saying that the resolver will never have the preimage - payment continues

This would be the case where it responds with `"retry": false`. In any other case, raiden should retry the call, regardless of http status code. I think that is clearer and more explicit than relying on a particular status code.

**Comment by erkarl** [comment]
> > ii) an response saying that the resolver will never have the preimage - payment continues
> 
> This would be the case where it responds with `"retry": false`. In any other case, raiden should retry the call, regardless of http status code. I think that is clearer and more explicit than relying on a particular status code.

The way I understand it if raiden receives any other code except 200 OK it should continue to hitting the resolver endpoint for the preimage until it receives `"retry: false"`. This approach seems unambiguous to me.

**Comment by offerm** [comment]
Another comment:
- when we provide `retry=true` we must be sure that the payment was not done or failed. The risk here is of double payment and I'm not sure that there is a safeguard in place to protect from it.

**Comment by sangaman** [comment]
> a. does the preimage included in the response -> continue the swap
> b. if not, does retry has the value of false -> if so, continue the raiden flow.
> c. else retry.

That's right.

> Note that while the above logic is sound, it is over complicated with not real need. We can just use 2 HTTP codes that signal - OK, NOT FOUND, ERROR.
> We need to keep in mind that this interface is not just for XUD but is more generic and may be used by others.

Yes this is my concern as well, but that's also why I don't want to use a client error status code for errors that don't pertain to the client. "Not found" is not intuitive to me as necessarily a permanent failure in the resolver context (it could be that we can't find it now, but we might find it later). It's also worth mentioning that 404 will be the status code if the wrong path is used against xud, or if the right path is used against the wrong server many servers will respond with 404 as well, and we wouldn't want to fall back to the raiden swap in those cases.

> when we provide retry=true we must be sure that the payment was not done or failed. The risk here is of double payment and I'm not sure that there is a safeguard in place to protect from it.

I tried to do exactly this in #1297 with separate internal errors for "final" payment errors and "unknown" payment errors.
