### ISSUE TITLE
lnd `invalid key length` error

### ISSUE THREAD

**Issue by sangaman** [ExchangeUnion/xud#1301]
This issue tracks a recently observed bug where a swap fails due to a failed lnd payment by the remote peer due to `invalid key length` - which is returned by lnd when a send payment attempt specifies a destination pub key that is not 33 characters. Restarting xud resolves the issue. See logs below from @kilrau.

https://paste.ubuntu.com/p/WXHKWX7PDZ/

I suspect that what happened is that for some reason, xud got a wrong (probably an empty) pub key or did not get a pub key from lnd but still connected to peers and shared this empty pub key with them. Later xud got the correct pubkey (as verified by calling getinfo) but did not update peers of this correct pubkey (we do not currently inform peers about lnd pub key change via node state update, although this is a known desired feature). However, swaps with that peer will fail as the peer will attempt to send payment using the wrong lnd pubkey.

**Comment by sangaman** [comment]
@kilrau Have you observed this issue recently at all? I can't remember the last time I've seen it.

**Comment by kilrau** [comment]
No..

**Comment by kilrau** [comment]
Haven't seen it in months. Closing for now.
