### ISSUE TITLE
Add config option to raise mainnet limits to ln/raiden max values

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1304]
* Add config option to raise xud mainnet trading limits to lndbtc/lndltc/raiden max values. Maybe `network_max_limits`.
* BTC, LTC Values: https://github.com/lightningnetwork/lnd/pull/1246/files. Our Raiden contract max values: @offerm

**Comment by offerm** [comment]
When I deployed the contracts I used these values:
 
--channel-participant-deposit-limit 115792089237316195423570985008687907853269984665640564039457584007913129639935 --token-network-deposit-limit 1157920892373161954235709850
08687907853269984665640564039457584007913129639935

**Comment by sangaman** [comment]
@offerm Just to make sure I'm reading this right, these limits seem extremely high even when represented in wei. I calculate `11579208923731619542357098500868790785326998466564056403945758400791` satoshis worth of ERC20 tokens, which isn't a problem but it effectively means no limit and I want to make sure I'm understanding correctly.

**Comment by kilrau** [comment]
I think that's correct @sangaman. `115792089237316195423570985008687907853269984665640564039457584007913129639935` is the maximum value of a 256-bit number meaning no limit for ERC20s from Raiden side.
