### ISSUE TITLE
Move simulation tests' scripts to a dedicated folder

### ISSUE THREAD

**Issue by erkarl** [ExchangeUnion/xud#1310]
Simulation tests folder is currently cluttered with scripts. It would be better organized if we could have all the `.sh` files in one folder called `scripts`.

**Comment by kilrau** [comment]
volunteers? @krrprr @rsercano

**Comment by erkarl** [comment]
This is a follow-up to: https://github.com/ExchangeUnion/xud/pull/1195

**Comment by engwarrior** [comment]
Pls provide estimate for this task.

**Comment by kilrau** [comment]
Is this still relevant after dockerization? @LePremierHomme

**Comment by LePremierHomme** [comment]
> Is this still relevant after dockerization? @LePremierHomme

No.. closing.
