### ISSUE TITLE
Swagger API Docs for Web API Proxy

### ISSUE THREAD

**Issue by itsbalamurali** [ExchangeUnion/xud#133]
The idea is to generate `Swagger REST API` documentation for web API proxy from the `proto` file.
This would involve.

- Generation of swagger json file from `protoc` via [protoc-gen-swagger](https://github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger)
       Example: `protoc DEFINITION.proto --swagger_out=logtostderr=true:.`
- Attach Swagger Docs Middleware to `webproxy / express` for serving the documentation.

**Comment by sangaman** [comment]
I actually already have this working locally, will open a PR for it soon.
