### ISSUE TITLE
TradingLimits (GetBalance enhancements)

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1331]
Off-shoot from https://github.com/ExchangeUnion/xud/issues/1329 by @offerm :

> I need a way to know how much I can trade. for this I need the max out going and incoming channel for each asset. The current information can't help with this. Incoming is not provided at all and out going (channel balance ) my be over multiple channels so it can't be used in a single swap.

> #2 - what I need is a reliable way to ensure that an order I'm about to issue can be placed.
So, if I'm about to place a buy 1 BTC/DIA 8800 order, I need to know that I can send 8800 DAI and can receive 1 BTC. Ideally it should take into account my other orders of that pair in that direction.
For example, if I already sent buy 1 BTC/DIA 8800 and I'm now sending `buy 2 BTC/DAI 8600' I want to ensure that I can send 28600+18800 and receive 3 BTC.

**Comment by erkarl** [comment]
What Offer said makes a lot of sense and I came across the same concerns while implementing overview of balances for Arby. I'd like to have output for the maximum amounts I can send/receive via a single channel.

Considering active orders would be a nice to have, but not required at this point.

**Comment by kilrau** [comment]
Implementation idea: Loop through channels and find max local balance and max remote balance

**Comment by sangaman** [comment]
As discussed today, I think it makes more sense to return these limits in a separate call from `getbalance`. Maybe something like `channellimits` or `tradinglimits`?

We also should take `local_chan_reserve_sat` and `remote_chan_reserve_sat` into account by subtracting them from the available balance.

We can also assign the outbound max to the `maximumOutboundAmount` property on each `LndClient` (and perhaps create a `maximumInboundAmount` field with corresponding logic) but that can be done separately.

**Comment by erkarl** [comment]
Sounds good - I'd prefer `tradinglimits` for the name.

**Comment by offerm** [comment]
Need both in and out.
Consider to provide the information by pairs
Best would be to provide the Max sell and Max buy per pair.

**Comment by kilrau** [comment]
> We also should take local_chan_reserve_sat and remote_chan_reserve_sat into account by subtracting them from the available balance.
:+1: 
> Sounds good - I'd prefer `tradinglimits` for the name.
:+1: 
> We can also assign the outbound max to the maximumOutboundAmount property on each LndClient (and perhaps create a maximumInboundAmount field with corresponding logic) but that can be done separately.
I think the below is better (assign limits to pair, not swap client). Let's also not forget about Raiden(!)
> Best would be to provide the Max sell and Max buy per pair.
That also makes sense to me. How about `tradinglimits btc/dai`. Response can be a JSON stating `buylimit` & `selllimit`.

**Comment by kilrau** [comment]
@offerm @erkarl had some more feedback on the `tradinglimits btc/dai` : it should account for existing orders which are taking capacity of a channel. Let's the continue discussion here.

**Comment by LePremierHomme** [comment]
Steps / Questions:

* Create new gRPC/CLI call `tradinglimits(pair)`
* For the given pair, find the max outbound/inbound balance for a distinct channel. Is that make sense, considering that this channel might not be usable for a given swap?
* `LndClient` to maintain `maximumChannelOutboundAmount` & `maximumChannelInboundAmount` updated by `listChannels()` lnd calls, while subtracting `local_chan_reserve_sat` and `remote_chan_reserve_sat` respectively. 
* `RaidenClient` - if Raiden’s channel balance is the outbound amount, is there a way to query the inbound amount?
* For stating `maxbuy` (or similarly `maxsell`) in the response as the allowed quantity, it should consider quote currency outbound amount, limited by the base currency inbound amount, for a given price, no? if so, we should also require to provide the price as an argument to `tradinglimits(pair)`, no?
* consider active orders - is that supposed to take into account the effect of all ownOrders on channel capacity as if they would be executed? If so, is it supposed to only reduce the outbound amount, or also to increase the inbound amount? Is doing so make sense, since these order might not get executed?

**Comment by sangaman** [comment]
>  Is that make sense, considering that this channel might not be usable for a given swap?

I think so, it's just the theoretical maximum. We can't know whether it's available for swapping until we try a swap.

> LndClient to maintain maximumChannelOutboundAmount & maximumChannelInboundAmount updated by listChannels() lnd calls, while subtracting local_chan_reserve_sat and remote_chan_reserve_sat respectively?

Yes that's what I had in mind, although it doesn't have to be done all at once with the new rpc call. There's a `updateCapacityTimer` that periodically updates the available balance, and that can be enhanced to update the new theoretical limits instead.

> RaidenClient - if Raiden’s channel balance is the outbound amount, is there a way to query the inbound amount?

Yes, you'd subtract `balance` from `total_deposit` I believe to get the inbound amount. See here: https://raiden-network.readthedocs.io/en/stable/rest_api.html#querying-information-about-channels-and-tokens

> For stating maxbuy (or similarly maxsell) in the response as the allowed quantity, it should consider quote currency outbound amount, limited by the base currency inbound amount, for a given price, no? if so, we should also require to provide the price as an argument to tradinglimits(pair), no?

I wasn't thinking this would be expressed in terms of max buy/sell, but if so then yes. Maybe price could be optional? We can discuss this more perhaps.

**Comment by kilrau** [comment]
> Considering active orders would be a nice to have, but not required at this point.

I think we should do it.

> * Create new gRPC/CLI call `tradinglimits(pair)`

Correct!
 
> * For the given pair, find the max outbound/inbound balance for a distinct channel. Is that make sense, considering that this channel might not be usable for a given swap?

Yes. It is impossible to know if one particular channel will be usable for one particular swap beforehand since routes are constantly changing. Therefore, the best we can do is:
* Among all channels, find the channel with the momentarily `max_available_outbound_amount` for `sell_currency` and the channel with `max_available_inbound_amount` for `buy_currency`. Among all our existing channels.
* Constantly updated `max_available_outbound_amount` for *each channel* by taking inbound amount minus channel reserve and minus `sell_currency_amount` from an existing order that is "blocking amount" on this channel. Update with every order status change (filled, canceled - remove block) and payments on the channel (orders might block amount on one channel but actually execute on another; also their might be manual payments on the channel). Same for `max_available_inbound_amount`.

Simply speaking, each existing open order is assigned to one particular channel and "blocks" meaning reduces available amount. Once the order is completed/cancelled the block is removed and available amount is updated. With every payment on the channel available amount is updated.

> * `LndClient` to maintain `maximumChannelOutboundAmount` & `maximumChannelInboundAmount` updated by `listChannels()` lnd calls, while subtracting `local_chan_reserve_sat` and `remote_chan_reserve_sat` respectively?

It's a bit more, `lndclient` and `raidenclient` have to maintain `max_available_outbound_amount` & `max_available_inbound_amount **per channel**. Subtracting `local_chan_reserve_sat` and `remote_chan_reserve_sat` and blocked amounts by existing orders. See above.

> * `RaidenClient` - if Raiden’s channel balance is the outbound amount, is there a way to query the inbound amount?

It should be `total_deposit`-`balance`. Please confirm @offerm @erkarl. https://raiden-network.readthedocs.io/en/latest/rest_api.html#channel-object. There shouldn't be a channel reserve in raiden since on-chain fees are paid in ETH, but I just asked the raiden team to confirm here: https://gitter.im/exchangeunion/raiden-swaps. Please watch this.

> * For stating `maxbuy` (or similarly `maxsell`) in the response as the allowed quantity, it should consider quote currency outbound amount, limited by the base currency inbound amount, for a given price, no?

Good point. It's `maxbuy` for `buy_currency` and `maxsell` for `sell_currency`, not base/quote. I think it would be very helpful to have two versions of the call, one based on original requirement #1 and one based on requirement #2 of @offerm above https://github.com/ExchangeUnion/xud/issues/1331#issue-521520217.
#1 `tradinglimits(pair_id)` retuning a JSON with `maxbuy` & `maxsell` for base and `maxbuy` & `maxsell` for quote currency
#2 `tradingpossible(price, quantity, pair_id, side)` returning `true` if channels channels with sufficient available inbound and outbound capacity could be found, and false if not

> if so, we should also require to provide the price as an argument to `tradinglimits(pair)`, no?

See answer above.

> * consider active orders - is that supposed to take into account the effect of all broadcasted ownOrders on channel capacity as if they would be executed? If so, is it supposed to only reduce the outbound amount, or also to increase the inbound amount? Is doing so make sense, since these order might not get executed?

Reduce the outbound amount and increase the inbound amount, see above. I think it makes sense, since we should assume that all orders will eventually complete. It's just like on exchanges nowadays: If I issue an order, the amount is immediately deducted from my available balance (or moved to "frozen") and I cannot use it for another order.

**Comment by sangaman** [comment]
> It's a bit more, lndclient and raidenclient have to maintain max_available_outbound_amount & max_available_inbound_amount **per channel**.

Why does it have to be per channel? I thought we were only concerned with the maximums.

> Reduce the outbound amount and increase the inbound amount, see above. I think it makes sense, since we should assume that all orders will eventually complete. It's just like on exchanges nowadays: If I issue an order, the amount is immediately deducted from my available balance (or moved to "frozen") and I cannot use it for another order.

What if I have X inbound capacity for BTC, but I want to put out several orders to buy BTC in exchange for several different currencies? It wouldn't be possible to do with this, not to mention that it could get quite complicated calculating this frequently across multiple trading pairs with multiple orders that are constantly changing.

Overall I'm concerned this issue is growing too large in complexity/scope. At the end of the day this can only provide a rough upper limit to our trade size, in reality that would only be possible under optimal conditions.

**Comment by kilrau** [comment]
> not to mention that it could get quite complicated calculating this frequently across multiple trading pairs with multiple orders that are constantly changing.

We are maintaining available amounts per channel, not trading pair. The market maker is just querying this state with the tradinglimits call.

> What if I have X inbound capacity for BTC, but I want to put out several orders to buy BTC in exchange for several different currencies? It wouldn't be possible to do with this

You are. `tradinglimits` is an informational call and not blocking. You don't have to use it.

> could get quite complicated calculating this frequently across multiple trading pairs with multiple orders that are constantly changing.

It's not a super trivial but also not super complicated I believe. We don't calculate across trading pairs and orders. Just constantly update available amounts for a channel based on external events like a filled order or an executed payment. The market maker can simply query this via `tradinglimits`, `tradepossible`.

**Comment by sangaman** [comment]
> Because there is no AMP yet.

I'm aware... but that's exactly why we only need to track the channel with the highest balance, since payments can't go through more than one channel.

Another thing to keep in mind is that we should cap it at the maximum amounts allows by the network, ~0.04 in case of BTC.

**Comment by kilrau** [comment]
> I'm aware... but that's exactly why we only need to track the channel with the highest balance, since payments can't go through more than one channel.

"highest available balance" to count in open orders. I just think it's bad for a call that is supposed to give me my "trading limits" to say "all good" if I have one highest channel with 0.1 BTC outbound and can issue 100 orders with 0.1BTC outbound. One order goes through, and all others will fail. That's why I am supporting @offerm to count in open orders. And since that makes the implementation quite a bit different I'd do it right away.

> Another thing to keep in mind is that we should cap it at the maximum amounts allows by the network, ~0.04 in case of BTC.

Good point! Since some channels can be `wumbo` in future or already have the hardcoded limits simply removed from the code (we might do this! and already did on simnet), we might as well maintain a `maxpayment` property for each channel in the list I'm proposing above. Afaik there is no such info in a channel atm (just a client-side check), so I'd just initialize the `maxpayment` with the default 0.04 BTC and corresponding ltc,dai, weth limits. Once wumbo is here, we can see how to query this info from a channel and change the `maxpayment` property. If we decide to not care open orders and therefore are not maintaining a list of channels per swap client, then it'll just be a generic `if >0.04 BTC then false` for `tradingpossible(price, quantity, pair_id, side)`.

What are the WETH/DAI per-payment-limits  for the mainnet contracts again? @offerm

**Comment by sangaman** [comment]
> "highest available balance" to count in open orders.

I was talking about tracking the single highest balance across channels there, not about open orders, instead of tracking balance per channel.

**Comment by kilrau** [comment]
Summary from the call: we go for the "simple" version **without** accounting for open orders and we want results per `currency`, not `pair`.

TODO:
* in **addition** to [maximum total outbound capacity](https://github.com/ExchangeUnion/xud/blob/master/lib/swaps/SwapClient.ts#L135), add `maximum channel outbound capacity` & `maximum channel inbound capacity` to regularly background-updated value. I also suggest a separate timer for it [here](https://github.com/ExchangeUnion/xud/blob/master/lib/swaps/SwapClient.ts#L79) in addition to the existing timer. 3000ms is a good default value I think.
* we get these max channel inbound/outbound capacity values by looping through lnd's [listchannels](https://api.lightning.community/#listchannels) & raiden's [channel endpoint](https://raiden-network.readthedocs.io/en/stable/rest_api.html#get--api-(version)-channels) and selecting the channel with the highest value for inbound and outbound.
* add tradinglimits(currency) to gRPC and CLI. Response contains `maxbuy`(max channel inbound capacity) & `maxsell` (max channel outbound capacity) for given currency. Currency parameter is optional; if not set return for all currencies.

**Comment by kilrau** [comment]
I confirmed that there is no "channel reserve" in raiden.

**Comment by kilrau** [comment]
Closed by https://github.com/ExchangeUnion/xud/pull/1341
