### ISSUE TITLE
Add minimum price precision for orders

### ISSUE THREAD

**Issue by erkarl** [ExchangeUnion/xud#1343]
At the moment it's possible to create orders with many decimal places.

```
➜  xud git:(feat/change-orderbook-default-precision) ./bin/xucli buy 0.00000001 LTC/BTC 0.00000000000000000000000000000000000000001
no matches found
remaining 0.00000001 LTC entered the order book as c736a520-12b1-11ea-979c-9b01abcb2b70
➜  xud git:(feat/change-orderbook-default-precision) ./bin/xucli orderbook

Trading pair: LTC/BTC
┌───────────────────────────────────────┬───────────────────────────────────────┐
│ Buy                                   │ Sell                                  │
├───────────────────┬───────────────────┼───────────────────┬───────────────────┤
│ Quantity          │ Price             │ Price             │ Quantity          │
└───────────────────┴───────────────────┴───────────────────┴───────────────────┘
➜  xud git:(feat/change-orderbook-default-precision) ./bin/xucli listorders

Trading pair: LTC/BTC
┌────────────────────────────────────────────────────┬────────────────────────────────────────────────────┐
│ Buy                                                │ Sell                                               │
├───────────────────┬───────────────────┬────────────┼───────────────────┬───────────────────┬────────────┤
│ Quantity          │ Price             │ Own Order  │ Quantity          │ Price             │ Own Order  │
├───────────────────┼───────────────────┼────────────┼───────────────────┼───────────────────┼────────────┤
│ 0.00000001        │ 1e-41             │ X          │                   │                   │            │
└───────────────────┴───────────────────┴────────────┴───────────────────┴───────────────────┴────────────┘
➜  xud git:(feat/change-orderbook-default-precision) ./bin/xucli orderbook --precision 80

Trading pair: LTC/BTC
┌───────────────────────────────────────┬───────────────────────────────────────┐
│ Buy                                   │ Sell                                  │
├───────────────────┬───────────────────┼───────────────────┬───────────────────┤
│ Quantity          │ Price             │ Price             │ Quantity          │
├───────────────────┼───────────────────┼───────────────────┼───────────────────┤
│ 0.00000001        │ 1e-41             │                   │                   │
└───────────────────┴───────────────────┴───────────────────┴───────────────────┘
```

**Comment by engwarrior** [comment]
Hi, I want to work on this issue and others and eventually join your team, I spoke to Killian and he advised me  to start work on the issues. There should be estimation on how much I get paid on completion, can you give me one?

**Comment by erkarl** [comment]
@engwarrior I've added a rough estimation for the issue. 

@sangaman what do you think about limiting the minimum amount to 1 satoshi per coin (10 ** 8)?

**Comment by sangaman** [comment]
I'm not so sure actually, I could see scenarios where we want price precision below that level. Just as a hypothetical example, dogecoin is currently 2 e-7. A hardcoded limit could prove to be more of a hindrance than a help. Maybe we could do a millisatoshi lmiit (1e-11), as that pretty much covers every token currently in existence? The other question then is whether the limit should be enforced on the cli or rpc level?

**Comment by kilrau** [comment]
My argumentation would be pro 8 decimals max for *all* coins/tokens. Reasons:
- Regular exchanges have lower trade amount limits too, main reason are probably attack vectors to overload matching engines matching tiny bits and pieces. I am pretty sure we want to discourage trading "dust amounts", since I can see similar attack vectors [coming up.](https://twitter.com/tdryja/status/1101858335144529921?s=19) but can't find a real good use case for allowing tiny trading amounts.
- "Satoshis the standard" (in most other places xud seems to have the sat standard: https://github.com/ExchangeUnion/xud/blob/master/lib/utils/UnitConverter.ts)

Enforcement on RPC level.

**Comment by sangaman** [comment]
> My argumentation would be pro 8 decimals max for _all_ coins/tokens. Reasons:
> 
> * Regular exchanges have lower trade amount limits too, main reason are probably attack vectors to overload matching engines matching tiny bits and pieces. I am pretty sure we want to discourage trading "dust amounts", since I can see similar attack vectors [coming up.](https://twitter.com/tdryja/status/1101858335144529921?s=19) but can't find a real good use case for allowing tiny trading amounts.
> * "Satoshis the standard" (in most other places xud seems to have the sat standard: https://github.com/ExchangeUnion/xud/blob/master/lib/utils/UnitConverter.ts)
> 
> Enforcement on RPC level.

We already have the minimum *quantity* increment as satoshis, that is the smallest unit internally and on the rpc level. But price does not have that minimum, and if we ever try to trade something that's priced like dogecoin then satoshi price precision wouldn't be enough. You could trade a billion dogecoin at a very small price and it certainly wouldn't be dust.

**Comment by engwarrior** [comment]
I guess we settle with 10 ** 11 or 10 ** 12 right as it gives maximum precision for all coins as @sangaman described?

**Comment by erkarl** [comment]
> But price does not have that minimum, and if we ever try to trade something that's priced like dogecoin then satoshi price precision wouldn't be enough. You could trade a billion dogecoin at a very small price and it certainly wouldn't be dust.

Isn't 10 ** 8 enough for DOGE as it's currently trading at ~0.00000027?

**Comment by kilrau** [comment]
> I guess we settle with 10 ** 11 or 10 ** 12 right as it gives maximum precision for all coins as @sangaman described?

You can code it up with 10 **12 for now, this number is easily switched.

**Comment by engwarrior** [comment]
@kilrau sure

**Comment by sangaman** [comment]
> > But price does not have that minimum, and if we ever try to trade something that's priced like dogecoin then satoshi price precision wouldn't be enough. You could trade a billion dogecoin at a very small price and it certainly wouldn't be dust.
> 
> Isn't 10 ** 8 enough for DOGE as it's currently trading at ~0.00000027?

I wouldn't say so exactly because you'd you have less than 2 digits of precision. It's a ~4% jump from 2.6 e-7 to 2.7 e-7 for example, and we wouldn't be able to handle anything in between.

**Comment by engwarrior** [comment]
Do we want to have error shown on order creation in case of higher precision or we want to just cut off last digits?

**Comment by engwarrior** [comment]
I'm adding same condition for quantity too.

**Comment by engwarrior** [comment]
Is it normal that FAIL  test/jest/Backup.spec.ts (14.84s) fails for me? Just 1 test. Seems like we don't have CLI orders tests, but I guess its different issue.
<img width="718" alt="Screenshot 2020-02-04 at 01 15 16" src="https://user-images.githubusercontent.com/36715003/73695758-d13e4780-46eb-11ea-88be-e15f72d9222c.png">

**Comment by engwarrior** [comment]
When running CLI, missing file. I tried sudo npm i -unsafe-perm -allow-root, doesn't help.
<img width="834" alt="Screenshot 2020-02-04 at 01 40 46" src="https://user-images.githubusercontent.com/36715003/73697351-655dde00-46ef-11ea-95a0-4fa9cbc6d592.png">

**Comment by kilrau** [comment]
> Do we want to have error shown on order creation in case of higher precision or we want to just cut off last digits?

Definitely show a meaningful error and don't let the order go through since "just cut off last digits" could have unintended results. Regarding tests: @sangaman

**Comment by engwarrior** [comment]
@kilrau yes, that's what I thought for possible unintended results, already done, I'll make PR now.

**Comment by erkarl** [comment]
> Is it normal that FAIL test/jest/Backup.spec.ts (14.84s) fails for me? Just 1 test. Seems like we don't have CLI orders tests, but I guess its different issue.
> <img alt="Screenshot 2020-02-04 at 01 15 16" width="718" src="https://user-images.githubusercontent.com/36715003/73695758-d13e4780-46eb-11ea-88be-e15f72d9222c.png">

Can you try compiling the seed utility and check if the problem persists? `npm run compile:seedutil && npm run test`

**Comment by engwarrior** [comment]
@erkarl works fine now, can you pls review my PR? We can merge after that. Added checks for RPC too.

**Comment by engwarrior** [comment]
@kilrau close this pls.

**Comment by kilrau** [comment]
Done, next time pls use the `Closes` keyword.
