### ISSUE TITLE
Raiden simulation test occasionally fails

### ISSUE THREAD

**Issue by erkarl** [ExchangeUnion/xud#1354]
Created based on: https://github.com/ExchangeUnion/xud/pull/1351#pullrequestreview-334160630

Raiden simulation test occasionally fails because the time it takes for the clients to join the matrix rooms when creating a new channel.

We're currently waiting 180 seconds for the clients to join the matrix rooms, but a better solution would be to try executing a swap every 10 seconds, timeout after 300 seconds.

**Comment by LePremierHomme** [comment]
Closing this as Raiden setup was removed from the simulation tests.
