### ISSUE TITLE
Throttle xud-backup update interval

### ISSUE THREAD

**Issue by erkarl** [ExchangeUnion/xud#1368]
Currently `xud-backup` updates immediately when changes to the file are detected. This could be problematic for larger database files (100mb+).

**Comment by engwarrior** [comment]
Pls provide estimate for this task.

**Comment by kilrau** [comment]
Since the backup eventually will be somewhere remote, we should rather consider exporting and pruning historical data if filesize exceeds e.g. 100 MB.
