### ISSUE TITLE
xucli prints "could not connect to xud" when call fails

### ISSUE THREAD

**Issue by sangaman** [ExchangeUnion/xud#1371]
When certain calls fail, including `connect` when the connection times out and `create` or `unlock` when lnd is disconnected, xucli prints `could not connect to xud at localhost:8886, is xud running?` despite xud being reachable and the call failing due to an error. The error messages should be corrected in these cases.

Example errors from xud logs that cause this issue:

`[RPC] error: call /xudrpc.XudInit/CreateNode errored with code 14: lnd-BTC is Disconnected`

`[RPC] error: call /xudrpc.Xud/Connect errored with code 14: could not connect to peer at xud1.testnet.exchangeunion.com:18885: connect ECONNREFUSED 35.226.156.99:18885`

**Comment by kilrau** [comment]
+1, experienced that too
