### ISSUE TITLE
could not create keystore

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1379]
### Background

Following the RaspiXUD guide Light Setup on a Pi3 B+, I get:
```
You are creating an xud node key and underlying wallets. All will be secured by
a single password provided below.
  
Enter a password: 
Re-enter password: 

Error: 13 INTERNAL: could not create keystore: Error: Command failed: ./seedutil/seedutil keystore -pass= -path=/root/.raiden abstract hair essence scrap future finger rifle innocent hill apology office river elite hurdle bomb chest multiply garment float alien practice abstract abc xyz

❌ Failed to launch mainnet environment. For more details, see /home/xud/.xud-docker/mainnet/mainnet.log
```
[mainnet.log](https://github.com/ExchangeUnion/xud/files/4129245/mainnet.log)

### Your environment

* version of `xud`: xud-docker mainnet
* which operating system (`uname -a` on *Nix): 19.10 arm64
* version of `btcd`, `bitcoind`, `ltcd`, `litecoind`, `geth`, `parity`, `raiden`, `lnd` or other chain backend:
* any other relevant environment details:

### Steps to reproduce

Not clear, only managed to get this once.

**Comment by kilrau** [comment]
Test 2, deleted directories and docker images:
```
You are creating an xud node key and underlying wallets. All will be secured by
a single password provided below.
  
Enter a password: 
Re-enter password: 

❌ Failed to launch mainnet environment. For more details, see /home/xud/.xud-docker/mainnet/mainnet.log
```

**Comment by sangaman** [comment]
This has only happened once? What's strange is that `abc` and `xyz` are not part of the word list, that's most likely why the call failed in your first test, but I don't know why we would have gotten those words in the first place.

I'm not sure what went wrong with the second test, do you have the log for that one?

**Comment by kilrau** [comment]
> abc and xyz
I edited the last two words, not really sure why though :)

> This has only happened once?
So far yes. I am trying to reproduce.

**Comment by kilrau** [comment]
I tested again from scratch on the same Pi3 B+ with an officially recommended power cable to exclude this as reason for the behavior above.

Now the setup just got stuck (kept the shell open for 30 mins) at:
```
You are creating an xud node key and underlying wallets. All will be secured by
a single password provided below.
  
Enter a password: 
Re-enter password: 

```

Since it's working flawlessly on the Pi4, I suspect it has to do with the low-end CPU. Could you try the setup on a similarly spec'd ARM device than the Pi3 B+? @sangaman

**Comment by kilrau** [comment]
Also: how do you handle timeouts in https://github.com/ExchangeUnion/xud/pull/1376 ?

**Comment by kilrau** [comment]
Ran it again, watching the Pi 3's resources with htop on the side, nothing was in particular spiking when I created the node. This time it interstingly failed again with:
```
xud@ubuntu:~$ xud -b feat/arm
1) Simnet
2) Testnet
3) Mainnet
Please choose the network: 3
🚀 Launching mainnet environment
🌍 Checking for updates ...
All up-to-date.

You are creating an xud node key and underlying wallets. All will be secured by
a single password provided below.
  
Enter a password: 
Re-enter password: 

Error: 13 INTERNAL: could not create keystore: Error: Command failed: ./seedutil/seedutil keystore -pass= -path=/root/.raiden absent unhappy bonus patient outside comic pen select leopard clap hurt upper bargain flag canvas scissors cause gospel ski wasp sign race gym lens

❌ Failed to launch mainnet environment. For more details, see /home/xud/.xud-docker/mainnet/mainnet.log
```

**Comment by engwarrior** [comment]
Pls provide estimate for this task.

**Comment by kilrau** [comment]
@sangaman is already working on this @engwarrior

**Comment by kilrau** [comment]
Good news @sangaman , @michael1011  figured this out: this is because the seedutil crashed because the machine running out of RAM. Solution: Create a swap file on a 1GB RAM machine, update official recommendation to 2GB RAM. See https://github.com/ExchangeUnion/docs/issues/88

Closing here.
