### ISSUE TITLE
Replace raiden directChannelChecks config option

### ISSUE THREAD

**Issue by sangaman** [ExchangeUnion/xud#1384]
Followup to #1347.

This issue tracks getting rid of the `directChannelChecks` raiden config option and treat it as if it's always true - but then internally count a channel with a hardcoded routing service node as satisfying the direct channel requirement (so for any given currency/peer, we need either a channel with that peer or a channel with a routing service for the currency).

**Comment by engwarrior** [comment]
Pls provide estimate for this task.

**Comment by kilrau** [comment]
I'd also like to postpone this task for ~1month
