### ISSUE TITLE
lnd unlock issues

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1415]
lndltc reports that it was succesfully unlocked, but actually wasn't. E.g. calling `lndltc-lncli getinfo` returns that it is still locked. Unlockling via `lndltc-lncli unlock` also reports the "Success" message, but it turns out lndltc is still locked.
```
mainnet > lndltc-lncli getinfo
[lncli] Wallet is encrypted. Please unlock using 'lncli unlock', or set password using 'lncli create' if this is the first time starting lnd.
mainnet > lndltc-lncli unlock
Input wallet password: 

lnd successfully unlocked!
mainnet > lndltc-lncli getinfo
[lncli] Wallet is encrypted. Please unlock using 'lncli unlock', or set password using 'lncli create' if this is the first time starting lnd.
```
Restarting lndltc fixes this. Can be easily reproduced by simply starting up testnet/mainnet.

**Comment by erkarl** [comment]
my current flow on mainnet with lnd unlocking is:
1. start environment and unlock
2. status says Container running for lnds
3. restart lndbtc
4. status says Wallet is locked.
5. lndbtc-lncli unlock
6. success, repeat for ltc
the lnds are not automatically unlocked
