### ISSUE TITLE
XUD sends order twice

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#142]
- with same ID
- with different ID

Receiving XUD just drops it.

**Comment by moshababo** [comment]
If an order with the same Id arrives, the order book should ignore it, and the p2p layer should penalize the peer (an issue for this task will be open soon).

If a duplicated order with a different Id arrives, there's no practical way to protect against it, except with our general anti-spam mechanisms, which will be applied to all orders.

**Comment by moshababo** [comment]
For now we just need to make sure that order book does not add an order with a duplicated order id.
