### ISSUE TITLE
Testnet & Mainnet | Copying URI address to get that node info or to open channel, is tedious

### ISSUE THREAD

**Issue by fagunbhavsar** [ExchangeUnion/xud#1426]
**Is your feature request related to a problem? Please describe.**
Right now, when user copies address from listpeers table either to get node info or to open channel, it also copies details from Details column - which has to be formatted again before using; and that is a tedious job! Could it be made easier?

**Describe the solution you'd like**
Either to change tabular format with single column

**Describe alternatives you've considered**

**Additional context**

cc: @kilrau 

![Screenshot 2020-03-04 at 1 37 19 PM](https://user-images.githubusercontent.com/18718151/75858006-4ef59000-5e1d-11ea-93b9-97c7efc1788a.png)

**Comment by kilrau** [comment]
Good point, experienced the same! Even though to get node details or open channel you only would need the pubkey and even better only the very short alias human-readable alias in future ( https://github.com/ExchangeUnion/xud/pull/1362). Props to @hatmer !

Another though: @sangaman should we simply get rid of the "pairs" and "Details" Column? All that information should be in `getnodeinfo`.
