### ISSUE TITLE
Testnet | Channel is not getting opened - as it shows an error - connect PeerAddreses failed

### ISSUE THREAD

**Issue by fagunbhavsar** [ExchangeUnion/xud#1428]
**Describe the bug**
On testnet, unable to open channel, as it throws an error - connect PeerAddreses failed

**To Reproduce**
1. Connect to AWS EC2 instance
2. Run the installation
3. Select testnet
4. Run listpeers
5. Run connect <node_id> <currency> <quantity>
6. Validate result

**Expected behavior**
Step 6 - Channel should get opened

**Actual Behaviour**
Step 6 - It throws an error - "connectPeer Addreses failed"

**Screenshots**
![Screenshot 2020-03-03 at 4 30 00 PM](https://user-images.githubusercontent.com/18718151/75861600-9e3ebf00-5e23-11ea-9853-3654763caa16.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fagunbhavsar** [comment]
@kilrau Here it is!

[testnet.zip](https://github.com/ExchangeUnion/xud/files/4286892/testnet.zip)

**Comment by kilrau** [comment]
Reproduced the same today on simnet: https://github.com/ExchangeUnion/xud/issues/1448 (closed as duplicate). Bumping prio.

**Comment by kilrau** [comment]
Fixed by https://github.com/ExchangeUnion/xud/pull/1468
