### ISSUE TITLE
Connecting to new node -> automatically connect Lightning clients

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1456]
When connecting to a new xud node, e.g. (`02529a91d073dda641565ef7affccf035905f3d8c88191bdea83a35f37ccce5d64) on xud-level, we should fetch their L2 URIs and connect to these automatically too.

Details:
- Lightning clients only (atm LND only, but through swapclient interface should support c-lightning https://github.com/ExchangeUnion/xud/issues/1281 too, doesn't apply to connext/raiden)
- since we auto-connect to the bootstrap nodes `xud1.simnet.exchangeunion.com`, `xud1.testnet.exchangeunion.com` & `xud1.exchangeunion.com` on launch, this serves not only a preparation for channels but also as a bootstrap peer for the lightning graph sync to solve this issue:
```
2020-04-02 11:28:09.182 [INF] DISC: Attempting to bootstrap with: Authenticated Channel Graph
2020-04-02 11:28:09.182 [ERR] SRVR: Unable to retrieve initial bootstrap peers: no addresses found
```

**Comment by sangaman** [comment]
I'm not sure that this is necessary. We already connect before we attempt to open a channel, and lnd automatically connects on its own if there is a channel. If we just connect directly on lnd without having or intending to have channels, I don't think there's any benefit to that. Does this make sense or is there a benefit that I am missing?

**Comment by michael1011** [comment]
I don't think that it is worth it but connecting to all LND nodes might give our local node a better overview of the network

**Comment by sangaman** [comment]
> I don't think that it is worth it but connecting to all LND nodes might give our local node a better overview of the network

As far as I'm aware this isn't necessary though for a functional lightning node. As long as there are just a few channels/connections (and I think even one should be enough in most cases) a node will learn about most of the network, at least given the rough size of the network nowadays.

**Comment by michael1011** [comment]
> a node will learn about most of the network, at least given the rough size of the network nowadays

Yes, most of the network. But try connecting to some random node from 1ml.com on your local node. It will find a couple more channels that it didn't know about before which could be helpful for building routes longer than two hops
