### ISSUE TITLE
p2p packets: get_hosts, hosts

### ISSUE THREAD

**Issue by moshababo** [ExchangeUnion/xud#147]
* `get_peers`: asking for information about known active peers to help with finding potential nodes in the network.
* `peers`: `get_peers` response. provide information on active peers.

**Comment by kilrau** [comment]
peers: connected xud's
hosts: xud's which I connected to successfully in the past (superset of peers, all peers are in hosts db)

revisit: exchange all hosts instead of peers only

**Comment by moshababo** [comment]
We might want to call this `get_hosts` & `hosts` instead. Let's talk before implementing.

**Comment by kilrau** [comment]
For now `get_peers` returns full host list, in future we can filter by reputation score

**Comment by kilrau** [comment]
Add implementation details: recursive queries of new hosts @sangaman
