### ISSUE TITLE
Disconnect from non-advertised nodes

### ISSUE THREAD

**Issue by moshababo** [ExchangeUnion/xud#148]
Disconnect from non-advertised nodes after 3 hours (configurable), not including `ping`/`pong` packets.

**Comment by kilrau** [comment]
I think this needs some more elaboration on 'non-advertised' @moshababo

**Comment by sangaman** [comment]
Yeah I am not sure what needs to be done for this issue, could you elaborate @moshababo ?

**Comment by kilrau** [comment]
@moshababo please add some details here or close this 👍

**Comment by moshababo** [comment]
Sorry, I missed this one. 

I was referring here to nodes which didn't send any packets. It's mostly for detecting stagnant nodes which have no order book activity.

**Comment by kilrau** [comment]
Interesting idea, I think we should think one step further when `xud` is operated by individuals too .We have to clearly define what counts as "activity", there might be nodes online only watching (receiving orders) and  filling my maker orders every now and then. Still they are valuable "customers" to me as maker. Here an appropriate timeout would be rather weeks then hours. Not sure about this one, moved it to a later milestone.

**Comment by kilrau** [comment]
Thought about this some more and don't think we should have a timeout on peer connections based on if they trade or not. Every responsive (`ping`/`pong`) node is a potential trading partner at some point.

Closing. Please reopen and elaborate if you think otherwise @moshababo
