### ISSUE TITLE
p2p packets: get_orders, orders

### ISSUE THREAD

**Issue by moshababo** [ExchangeUnion/xud#149]
* `get_orders`: on joining the network, query peers for the list of their existing valid orders. Default behavior is to query all orders, but a base timestamp optional condition should be supported.
* `orders`: `get_orders` response. if timestamp is applied, it should be considered as local.

EDIT: `get_orders` shouldn't only be called when joining the network, but rather on every time that the node is connecting to a new peer. The opposite applies as well: when disconnecting from a peer, remove his orders (#168).

EDIT 2: I think we should drop the timestamp support, because it will never be reliable, and it's actually not needed. If a node will query a peer for its orders, it should assume that it will send all of them. if it will query it incorrectly (without clearing the peer's orders, or after handshaking was completed, when new orders have already arrived), it will simply get duplicated orders, and it won't be the peer's fault.
Since handshaking is blocking the broadcasting of new orders, the edge case would be that between the `orders` response and the handshake finalization, some new orders won't be broadcasted. There are a few solutions for this, but I don't think we even need to address this issue. 
@kilrau @sangaman

**Comment by kilrau** [comment]
Related: https://github.com/ExchangeUnion/xud/issues/141
