### ISSUE TITLE
Generate simple html website from orderbook

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1495]
Step 1:
- create a simple .html website with some JS connecting to `xud`'s webproxy endpoint
- features: pair switcher (default to btc/usdt), orderbook buy/sell, node alias, node advertised address (pubkey@hostname:port), connected peers count
- use https://api.exchangeunion.com/#subscribeorders to show
showing the current local orderbook of a node
- color scheme should be dark (e.g. like [this](https://docs.blocknet.co/img/blockdx/full-screen.png), or grey/orange OpenDEX colors)
- needs external webserver like nginx/apache to host this

Step 2:
- add an (default false) config option to enable (orderbook ui) container which includes nginx to host this
- add price chart, visual depth and other fancy things

What is the goal? An easy **display** into the OpenDEX network, a way to show the public what's going on on the network by clicking on a link, e.g. ob.kilrau.com will host the orderbook of my mainnet node.

What is **not** the goal? A performanet web UI to control xud, a trade UI. It is display only.

**Comment by michael1011** [comment]
Idea for architecture: daemon listening to xud `subscribeorders` on machine -> EventSource HTTP stream -> frontend listening to stream

**Comment by erkarl** [comment]
We could do some light research if we can use grpc-web to `subscribeorders` directly in the future. At the moment this would also require that we have read-only macaroons because we wouldn't want the client being able to access other gRPC calls.

For now `subscribeorders` -> wrapper service -> client/frontend would be the easiest to implement.

**Comment by kilrau** [comment]
> We could do some light research if we can use grpc-web to subscribeorders directly in the future. 

Something for you? @hatmer 

Something reusable from the exchange orderbook UI you built a while ago? @reliveyy

**Comment by reliveyy** [comment]
> Something reusable from the exchange orderbook UI you built a while ago?

@kilrau I'd like to give is a try in watchdog container which combines my previous created reactjs app in the later PRs in xud-docker repo.

**Comment by hatmer** [comment]
macaroons can be JSON serialized and grpc-web allows for custom headers, so Karl's idea would work

**Comment by hatmer** [comment]
@reliveyy you could use JSON-serialized macaroons from reactjs too

**Comment by kilrau** [comment]
I like https://github.com/ExchangeUnion/xud/issues/1495#issuecomment-618246954.

Interested in taking the xud "backend" part of this one? @hatmer @reliveyy can provide a simple orderbook frontend he already cooked a while ago I think :)

**Comment by hatmer** [comment]
Yes sure, it will go nicely with the macaroons project

**Comment by kilrau** [comment]
EDITed issue as per discussion with @reliveyy . Moved to @reliveyy , bumped prio to P1.
