### ISSUE TITLE
Maker order type in listtrades for taker

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud#1511]
### Background

Taker has 'maker' order type for taker order.
![Screenshot](https://user-images.githubusercontent.com/29906866/80487241-298c8a80-8965-11ea-8173-86e4bc2f2dd4.png)

### Steps to reproduce

1. Place order to orderbook as maker
2. Fill it as taker
3. listtrades as taker

### Expected behaviour

Order type is taker

### Actual behaviour

Order type is maker

### Note about column name
Order type is Limit/Market. Its seems column should be renamed to something like 'Liquidity side' (https://www.onixs.biz/fix-dictionary/5.0.sp1/tagnum_851.html).

**Comment by kilrau** [comment]
This should be fixed as part of https://github.com/ExchangeUnion/xud/pull/1243

**Comment by kilrau** [comment]
Closed by https://github.com/ExchangeUnion/xud/pull/1567
