### ISSUE TITLE
xucli getinfo returns nothing because of socket hang up error for connext node

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud#1517]
### Background

xucli getinfo returns nothing because of socket hang up error for connext node. **It seems i should get socket hang up error in connext status cell of getinfo request**, but i got nothing instead. its just not good to block access to lnd info when connext does not work. 

Note: same behaviour for status command in docker-env

### Logs

[f_connext.log](https://github.com/ExchangeUnion/xud/files/4557746/f_connext.log)
[f_utils.log](https://github.com/ExchangeUnion/xud/files/4557747/f_utils.log)
[f_xud.log](https://github.com/ExchangeUnion/xud/files/4557748/f_xud.log)

### Screen

![Screenshot 2020-04-30 13:07:02](https://user-images.githubusercontent.com/29906866/80701675-73ea4480-8ae8-11ea-9e10-54d79bd84a6f.png)

**Comment by kilrau** [comment]
Since connext is not ready yet, this happens actually quite often and is quite annoying. One has to manually kill connext to get xud working again. Can you take over? @sangaman
