### ISSUE TITLE
Sequelize v4 deprecated

### ISSUE THREAD

**Issue by sangaman** [ExchangeUnion/xud#1523]
`npm WARN deprecated sequelize@4.44.4: This version will no longer receive security fixes per our security policy. Please update to sequelize@5 or above.` 

We'll have to bite the bullet and finally upgrade from sequelize v4, last time I dove into this it involved quite a bit of refactoring and changes to the code in particular due to incomplete typescript support in v5, but things may have improved since then.

**Comment by erkarl** [comment]
:(, hopefully the TS types support will be better now.

**Comment by kilrau** [comment]
Sounds like we should upgrade Sequelize if we want to be able to tag `1.0.0` with peace of mind.
