### ISSUE TITLE
feat: Change output of removeorder command/grpc call

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud#1526]
### Reason 

UX improvements

### Task 1

Change current output of removeorder to more useful. 
As user I want to know status of the operation, but instead of that I got info about amount in hold (it is additional information, not main)
It seems removed qty should be returned in response + remained qty if it was partial removal + qty in hold if it exists:
{
removedQty:5;# qty that was successfully removed
remainingQty:7;# remaining qty after partial removing
quantityOnHold:5; # qty in swap, but it will be removed if swap fails
}

### Task 2

Add Text output to xucli for removeorder command. Now it returns only json.

Draft:

- order "id" with qty "qty" fully removed - if remained = 0, and quantityOnHold = 0;
- order "id" with qty "qty" partially removed, remained qty = "qty" - if remained != 0, and quantityOnHold = 0;
- order "id" with qty "qty" partially removed, qty on hold because of swap process = "qty" - if remained = 0, and quantityOnHold != 0;

**Comment by kilrau** [comment]
Noticed that today too. Currently only two cases:
1. quantityOnHold: 0
```
testnet > removeorder a8d8ffb0-acd0-11ea-9bb4-378737f17cd2
{
  "quantityOnHold": 0
}
```
->
```
testnet > removeorder a8d8ffb0-acd0-11ea-9bb4-378737f17cd2
Order a8d8ffb0-acd0-11ea-9bb4-378737f17cd2 successfully removed.
```

2. quantityOnHold: X
```
testnet > removeorder a8d8ffb0-acd0-11ea-9bb4-378737f17cd2
{
  "quantityOnHold": 123
}
```
->
```
testnet > removeorder a8d8ffb0-acd0-11ea-9bb4-378737f17cd2
Order a8d8ffb0-acd0-11ea-9bb4-378737f17cd2 partially removed, remaining quantity on hold: 123
```

**Comment by erkarl** [comment]
Reverted https://github.com/ExchangeUnion/xud/pull/1985
