### ISSUE TITLE
feat: make output of discover command more informative

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud#1527]
### Reason

After discovering I have no information about count of peers that were autoconnected to me.

### Task 1

If discover is always equivalent of discover+autoconnect, it would be good to return number of autoconnected nodes too because it can be different because of tor using or network settings.

{
discovered:3
connected:2
}

### Task 2
Add plain text output for discover command in cli.

Draft:
3 nodes discovered and connection is established with 2 of them - if connected field is not empty
3 nodes discovered - if connected field is empty
There is no discovered nodes - if discovered is 0

**Comment by kilrau** [comment]
I don't consider discover really relevant on the CLI for now.
