### ISSUE TITLE
xud processing order updates for pairs I do not have

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1530]
### How it is

I do **not** have the pair btc/xuc set up on my xud (I do have xuc/btc set up though), xud is receiving order invalidations for such peer and actually tries to remove the order; which fails of course.

```
07/05/2020 11:24:11.754 [P2P] verbose: received order invalidation from 02778bcd8f1f578bbb2f3ff345ecccdb5865e4a08a0cfd98145da08ca3470c3e74 (ReadyAbsurd): {"id":"409fb610-9055-11ea-b76d-13690b06b3b3","pairId":"BTC/XUC","quantity":10000000}
07/05/2020 11:24:11.755 [ORDERBOOK] error: failed to remove order (409fb610-9055-11ea-b76d-13690b06b3b3) of peer 02778bcd8f1f578bbb2f3ff345ecccdb5865e4a08a0cfd98145da08ca3470c3e74 (ReadyAbsurd)
```

### How it should be

- xud knows about a peers pairs, don't send updates for pairs the peer doesn't have
- if an update gets send anyways, xud on the receiving side ignores such an update, adding a log entry in trace level, but not default log level (debug)

**Comment by kilrau** [comment]
As @erkarl pointed out, this could be abused to add new pairs and flood the network (and everyone's logs) with these failure messages.

**Comment by rsercano** [comment]
May I take this please? Want to check

**Comment by kilrau** [comment]
you got it

**Comment by rsercano** [comment]
Will we create another issue for GetOrders packet? @sangaman

**Comment by raladev** [comment]
> Will we create another issue for GetOrders packet? @sangaman @raladev

https://github.com/ExchangeUnion/xud/pull/1884
This PR should fix it
