### ISSUE TITLE
Remove all limits 🚀

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1531]
lnd 0.10 did, so should we. Let's remove all limits for all swap clients/currencies on xud level:
```
simnet > sell 15 eth/btc 0.022
Error: 3 INVALID_ARGUMENT: order amount 33000000 is exceeding limit of 16777216 set for BTC
```

```
07/05/2020 11:45:56.803 [RPC] error: call /xudrpc.Xud/PlaceOrderSync errored with code 3: order amount 33000000 is exceeding limit of 16777216 set for BTC
```

**Comment by sangaman** [comment]
Just to clarify, we already have a `maxlimits` config option that's set to automatically disable these limits by default. So this wouldn't result in any change to default behavior, but if we're confident that we won't need this going forward I can just remove any logic related to these limits for the codebase. The ETH/ERC20 currencies already have no limit. Let me know.

**Comment by kilrau** [comment]
We can keep it that why, but then please check what we are doing wrong in xud-docker for me to hit this limit message.

**Comment by sangaman** [comment]
Ah my apologies, I actually misread the code. We do currently enforce these limits (unrelated to docker), I'll remove them in a PR soon.

**Comment by kilrau** [comment]
Thanks! Just to be clear: I think we should keep `xucli tradinglimits [currency]            trading limits for a given currency` since its a useful option just set them to 21 million for btc, 84 million for ltc and something ridiculously high for eth and all erc20 by default.

**Comment by sangaman** [comment]
> Thanks! Just to be clear: I think we should keep `xucli tradinglimits [currency] trading limits for a given currency` since its a useful option just set them to 21 million for btc, 84 million for ltc and something ridiculously high for eth and all erc20 by default.

Yes that's a separate thing related to our balance. This is just concerning the hard network level limits.
