### ISSUE TITLE
No order invalidation for peer when self-match

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud#1547]
### Steps to reproduce

1. Place buy order as Alice
2. Check orderbook of Bob -> order in orderbook
3. Place order with same values but sell as Alice -> Alice got self-match
4. Check orderbook of Bob

### Expected behaviour

First order of Alice was removed from orderbook

### Actual behaviour

First order of Alice still in orderbook

### Screens
[Screenshot 2020-05-08 18:32:23](https://user-images.githubusercontent.com/29906866/81421719-94567680-915a-11ea-9d4f-f015917b410d.png)
[Screenshot 2020-05-08 18:32:09](https://user-images.githubusercontent.com/29906866/81421720-9587a380-915a-11ea-8810-8cd20369d64e.png)

**Comment by kilrau** [comment]
Just saw this now, we need logs here (always!) to see if the invalidation package was actually dispatched. Since we had a couple of situations where the invalidation packet was send but doesn't show up on the receiving side, we might have a bug there. Hope you still got the logs - please add them here.

**Comment by raladev** [comment]
> Just saw this now, we need logs here (always!) to see if the invalidation package was actually dispatched. Since we had a couple of situations where the invalidation packet was send but doesn't show up on the receiving side, we might have a bug there. Hope you still got the logs - please add them here.

First screen contains order palcing + order matching logs for both users or do you prefer txt format?:)
The case is persistent and can be easily reproduced again.

**Comment by sangaman** [comment]
I'm going to look into making a simulation test case for this, which will probably be helping both for diagnosing/fixing this issue and also making sure it doesn't arise again.
