### ISSUE TITLE
Same currency pair can be added

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud#1559]
### Steps to reproduce

1. Add Pair BTC/BTC
2. Place order to BTC/BTC order book and fill it

### Expected behaviour

No opportunity to add <symbol>/<same_symbol> because:
1. its useless action
2. for now eth/eth swap leads to SwapTimeOut and 500 Connext Error

### Actual behaviour

Pair Added, Swap performed
Note: These Swaps work only for lndbtc and lndltc and dont work for Connext pairs (leads to SwapTimeOut and 500 Connext Error).

**Comment by kilrau** [comment]
I think what we want to do here is: `if base_asset == quote_asset` in `addpair`, throw `Base asset and quote asset have to be different.` error. Should be quick win @rsercano
