### ISSUE TITLE
Adjust error message for openchannel command

### ISSUE THREAD

**Issue by erkarl** [ExchangeUnion/xud#1560]
Offshoot from: https://github.com/ExchangeUnion/xud-docker/pull/429#issuecomment-628622870

When the `openchannel` command fails for Connext it should not display `nodePubKey` in the error message.

**Comment by kilrau** [comment]
Instead it should print the actual `alias (nodePubKey)`.

**Comment by sangaman** [comment]
> Instead it should print the actual `alias (nodePubKey)`.

I think this would be a slightly separate issue? Connext doesn't deal with nodepubkey or alias at all for opening a channel.

**Comment by kilrau** [comment]
> I think this would be a slightly separate issue? Connext doesn't deal with nodepubkey or alias at all for opening a channel.

True.. simply removing `nodePubKey` should do.

**Comment by rsercano** [comment]
Is this already fixed within 704072e668f1737479617bad7b1db3478ff6e67f ? @sangaman @kilrau
