### ISSUE TITLE
Infinite swap recovery (after connext SwapTimeout error)

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud#1561]
### Background

I got SwapTimeOut for one of my swaps and now one of my nodes tries to recover this swap deal during ~3.5 hours. It seems that the reason of this behavior is connext node response.

Note:
For now you can get SwapTimeOut in 2 cases:
1. perform ETH/ETH swap
2. perform BTC/ETH swap with ETH amount > ETH in Channel

### Steps to reproduce

1. Perform swap and get SwapTimeOut
2. Wait

### Expected behaviour

Not more then 2-3 recovering attempts per swap.

### Actual behaviour

Swap recovering each 5 mins during 4 hours.

### Screens

[Screenshot from 2020-05-14 18-05-17](https://user-images.githubusercontent.com/29906866/81952481-37056e00-960f-11ea-8488-fffaacdc5662.png)
[Screenshot from 2020-05-14 18-05-06](https://user-images.githubusercontent.com/29906866/81952483-38369b00-960f-11ea-92ab-c0517ef2b31d.png)

### Logs

Swaps for grep:
b1e453ec5f68681b8186972e5ab136d0dca3baa1e6f92e763b9a08bbb4919c92
2d4059a5dd7881f57663634463d19a746a885a323f5d827b96010f5670451486

[swap_xud_a.log](https://github.com/ExchangeUnion/xud/files/4629336/swap_xud_a.log)
[swap_xud_b.log](https://github.com/ExchangeUnion/xud/files/4629334/swap_xud_b.log)

**Comment by kilrau** [comment]
Swap TimeOut themselves will be fixed by https://github.com/connext/indra/issues/1125 and others on connext side.

What needs to be done here in this issue: digg into swap recovery and see why there is an infinite recovery attempts in these scenarios and fix it.

**Comment by kilrau** [comment]
6.6.2 is merged, swap recovery should work now and can be tested @raladev

**Comment by raladev** [comment]
Closed because of after #1583 and 6.6.2 there is now Swap recovery for this case.
