### ISSUE TITLE
Verify data integrity 

### ISSUE THREAD

**Issue by moshababo** [ExchangeUnion/xud#157]
Add checksum/hash field to the packet header.
On receiving, verify the packet data integrity.

**Comment by moshababo** [comment]
1st is done.
All the rest can be done separately.

**Comment by kilrau** [comment]
Updated scope of this issue:
- On receiving, verify the packet data integrity via the checksum/hash field.
- Receive data structure of packet is what we expect
- rate limit for certain packet types like `GET_ORDERS` per `nodePubKey`

**Comment by kilrau** [comment]
Do we still need this when we do (packet serialization)[https://github.com/ExchangeUnion/xud/issues/159#issuecomment-435583439]? @moshababo @sangaman

**Comment by kilrau** [comment]
Moved to next milestone, not too critical

**Comment by moshababo** [comment]
@kilrau we won't need to do most of this if we'll change to protobuf serialization (#159). but it's not a trivial change.

**Comment by kilrau** [comment]
https://github.com/ExchangeUnion/xud/issues/159 is a requirement

**Comment by moshababo** [comment]
Lets limit the scope of this issue solely to:

* On receiving, verify the packet data integrity via the checksum/hash field.

In regards to the others:

* Receive data structure of packet is what we expect - 

#159 will make this unnecessary. 

* rate limit for certain packet types like GET_ORDERS per nodePubKey - 

I don't think it's related to here. I've opened #708.

**Comment by moshababo** [comment]
Waiting for #159.
