### ISSUE TITLE
SwapTimeout during connext swaps for new connext clients

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud#1570]
Based on https://github.com/ExchangeUnion/xud-docker/pull/464#issuecomment-632115929

Problems:
1. After performing new setups, users cant swap with connext clients during some time because of SwapTimeout error.
2. DAI amount was blocked for a XUC/DAI swap for taker and I dont see the way to get It back because of failed swap (For instance, in lnd we have force close to get back pending htlcs). Can be connected with https://github.com/ExchangeUnion/xud/issues/1561

**Comment by kilrau** [comment]
> during some time

When does it stop working when does it start working again? Needs log entries from connext client for these time intervals.

> DAI amount was blocked for a XUC/DAI swap for taker and I dont see the way to get It back because of failed swap (For instance, in lnd we have force close to get back pending htlcs). Can be connected with #1561

Also here logs would reveal if it's the infinite swap recovery attempts. Please attach these.

**Comment by raladev** [comment]
>  logs 

Logs for both cases attached in the comment message that mentioned in first row.

**Comment by erkarl** [comment]
@raladev if you experience this again please attach new connext logs. I'm currently not seeing this transfer in the node's logs.

**Comment by raladev** [comment]
> @raladev if you experience this again please attach new connext logs. I'm currently not seeing this transfer in the node's logs.

One more time :)
[Screenshot 2020-05-22 14:02:24](https://user-images.githubusercontent.com/29906866/82662482-98909280-9c36-11ea-81dc-3ef5d7816c7e.png)

Logs:

[again3_taker_connext.log](https://github.com/ExchangeUnion/xud/files/4667663/again3_taker_connext.log)
[again3_taker_xud.log](https://github.com/ExchangeUnion/xud/files/4667664/again3_taker_xud.log)


Steps:
1. 2 fresh installation (maker first, taker second)
2. sell 300 XUC/DAI 2 1 -> buy 300 XUC/DAI mkt -> SwapTimeout
3. sell 300 XUC/DAI 2 1 -> buy 300 XUC/DAI mkt -> SwapTimeout
4. buy 300 XUC/DAI 2 1 -> sell 300 XUC/DAI mkt -> Success
5. sell 300 XUC/DAI 2 1 -> buy 300 XUC/DAI mkt -> Success

Note:
This behavior a little bit different. In previous case (https://github.com/ExchangeUnion/xud-docker/pull/464#issuecomment-632115929) DAI of taker was blocked after unsuccessful swap, in this case they are still free to use after failed swap.

**Comment by raladev** [comment]
should be retested after adding second Connext token to simnet node and this one too - https://github.com/ExchangeUnion/xud/issues/1585

**Comment by kilrau** [comment]
Can you retest and close this if it's gone? @raladev

**Comment by raladev** [comment]
There was no swap problems after initialization,closed
