### ISSUE TITLE
Reserved Balance (show balance reserved by open orders separately)

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1584]
Exchanges usually show balance that is reserved by open orders slightly different, e.g. as "frozen", so should we. I prefer the term "reserved" since it's simply balance reserved for a certain open order.

Additionally, this reserved balance should be subtracted from `tradinglimits` to make `placeorder` balance checks account for it.

**Comment by sangaman** [comment]
Do you mean subtracting the quantity from all our open orders from the numbers we return/display for balance calls?

**Comment by kilrau** [comment]
Subtracting and showing it in a separate field or parenthesis e.g.:
```
simnet > getbalance

Balance:
┌──────────┬───────────────┬──────────────────────────────┬────────────────────────────────┐
│ Currency │ Total Balance │ Channel Balance (Tradable)   │ Wallet Balance (Not Tradable)  │
├──────────┼───────────────┼──────────────────────────────┼────────────────────────────────┤
│ BTC      │ 5.92217896    │ 0 (1 reserved | 2.5 pending) │ 1.96102386 (0.4611551 pending) │
├──────────┼───────────────┼──────────────────────────────┼────────────────────────────────┤
```

**Comment by kilrau** [comment]
This feature was requested from two users independently in the last days, so I am bumping prio here. Do you think it makes sense as described? @sangaman

**Comment by kilrau** [comment]
Bumped prio to P1 since this is needed for https://github.com/ExchangeUnion/xud/issues/1896.

**Comment by kilrau** [comment]
As just discussed with @raladev we have no collateralization for `placeorder` with `nobalancechecks` flag (https://github.com/ExchangeUnion/xud/pull/1916#issuecomment-701914861).  So while we want to restrict order placing by default (if e.g. all balance is used up by open orders), one can skip this check by appending `--nobalancechecks` to `placeorder`.

**Comment by kilrau** [comment]
Closing here in favour of https://github.com/ExchangeUnion/xud/issues/1678#issuecomment-708530763
