### ISSUE TITLE
invalid response - 0 error when another client connects to the node 

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud#1586]
### Steps to reproduce

1. Perform setup of 2 simnet nodes
2. Restart connext container of one of them
3. Check connext logs of second node

### Actual behaviour

Connext error, invalid response - 0  
video - https://gofile.io/d/76u4PR

### Logs
[inval_connext.log](https://github.com/ExchangeUnion/xud/files/4688770/inval_connext.log)
[inval_xud.log](https://github.com/ExchangeUnion/xud/files/4688771/inval_xud.log)

[inval_connext_restarted_client.log](https://github.com/ExchangeUnion/xud/files/4688764/inval_restarted_client.log)

**Comment by kilrau** [comment]
Reliably reproducible with these steps?

**Comment by raladev** [comment]
> Reliably reproducible with these steps?

Yeap

**Comment by kilrau** [comment]
I don't get this tbh, I was of the opinion `Connext error, invalid response - 0` signifies connext client issues to connect to its eth provider? @erkarl

**Comment by erkarl** [comment]
> I don't get this tbh, I was of the opinion `Connext error, invalid response - 0` signifies connext client issues to connect to its eth provider? @erkarl

I believe so, yes. I'd put this issue on hold until we upgrade the client and node to v7.0.0+.

**Comment by kilrau** [comment]
We didn't see this anymore after upgrading connext to 7.0.0. Closing.
