### ISSUE TITLE
Packets serialization

### ISSUE THREAD

**Issue by moshababo** [ExchangeUnion/xud#159]
We're currently using JSON string format for all packets serialization. We might want to introduce a pre-defined structure serialization at some point.

**Comment by ImmanuelSegol** [comment]
@moshababo @sangaman Could you elaborate on this?

**Comment by moshababo** [comment]
I guess our only viable solution is to switch to protobuf. I thought I already opened an issue in regards to that, but I guess I only raised that in the chat. It might be an overkill for us, but it's definitely more preferment, and will save us some of the data integrity checks (#157).

**Comment by moshababo** [comment]
I guess our only viable option is to switch to protobuf. I thought I already opened an issue in regards to that, but I guess I only raised that in the chat. It might be an overkill for us, but it's definitely more preferment, and will save us some of the data integrity checks (#157).

**Comment by kilrau** [comment]
Let's go for this this milestone!

**Comment by sangaman** [comment]
I'm personally not exactly sure how I'd go about implementing this with protobuf, but if you have an approach in mind then I'd say go for it and let's see how it works.

I do think we'd need to either use delimiters (like we're doing now) or send the size of the message before each message. See "Streaming Multiple Messages" here https://developers.google.com/protocol-buffers/docs/techniques?csw=1.

**Comment by sangaman** [comment]
A simple option would be to gzip messages over a certain size with [zlib](https://nodejs.org/api/zlib.html#zlib_convenience_methods).

I'm also reading that the performance benefits of protobuf over JSON are not that great when messages need to be converted from and to JSON anyway as is the case for `xud`: https://auth0.com/blog/beating-json-performance-with-protobuf/.

**Comment by moshababo** [comment]
In regards to the last article, i'm not sure I understand why messages need to be converted from/to JSON on JS runtime - JSON is just the string representation, and if i'm going from binary to plain JS object (and vise versa), why do I need JSON?
Also, the benchmarks for HTTP endpoints, so that's a bit different from our use-case. 

We can indeed introduce gzip, but the main downside with JSON (besides performance), is the lack of structure validation, which is problematic in a trustless setup. Typescript doesn't help with that, so we'll need to write the validation code ourselves. It will still be simpler then using protobuf, which doesn't have a lot of documentation, so that's why I wanted to bring this up for discussion. 

Anyway, I'll start looking into it soon, and give some more feedback.

**Comment by sangaman** [comment]
That makes sense. Although even with protobuf, we'd still want some validation to ensure certain properties are assigned values (and valid ones) right? I believe protobuf doesn't have "required" fields.

Definitely give protobuf a try, I think it'd be great if we can get it to work, but not a problem if we can't.

**Comment by kilrau** [comment]
Updates here? @moshababo

**Comment by moshababo** [comment]
It seems to be working fine. I still have more work to do, including to convert all the packets & testing. I won't be working on Thursday, so if I won't finish this by tomorrow, i'll finalize it on the weekend.
