### ISSUE TITLE
Minimum order size check: swap amount smaller 1 sat fails with "no route found"

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud#1594]
### Steps to reproduce

1. place order sell 0.0000001 ETH/BTC 0.02  as a maker
2. place order buy 0.0000001 ETH/BTC mkt as a taker

### Actual behaviour

No route error because btc amount is 0.0000001*0.02=0.**00000000**2

### Expected behaviour

User cant place order with swap amount < 8 decimals
[Screenshot from 2020-06-02 12-37-18](https://user-images.githubusercontent.com/29906866/83513947-5fc8a700-a4db-11ea-9310-a10df44e48be.png)

[logs.zip](https://github.com/ExchangeUnion/xud/files/4716771/logs.zip)

**Comment by sangaman** [comment]
There was a time when we'd talked about minimum order sizes, and I'm thinking that might make sense again. I'm not sure what should be, but setting the minimum size to be 1 satoshi on each side of the swap seems like a no brainer.

**Comment by kilrau** [comment]
Bumping prio here since it's very likely to run into this one when testing out things and leading to a bad first-time UX.
