### ISSUE TITLE
Clearer matching output for market orders

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud#1596]
EDIT: here is what we want to do in this issue: https://github.com/ExchangeUnion/xud/issues/1596#issuecomment-637640938

### Precondition

You got No Route Error after installation or you can reliably reproduce another swap error reliably.

### Steps to reproduce

1. place buy 1 LTC/BTC 0.001 order as a maker
2. sell 0.1 LTC/BTC mkt 1 as a taker

### Expected behaviour

'no matches found' message should be printed after last unsuccessful swap.

### Actual behaviour

Nothing printed after last unsuccessful swap attempt.

[Screen 1](https://user-images.githubusercontent.com/29906866/83528732-1fc0ee80-a4f2-11ea-9691-fbd2671ace60.png)
[Screen 2](https://user-images.githubusercontent.com/29906866/83528735-218ab200-a4f2-11ea-9ece-2f8fd3506333.png)

**Comment by sangaman** [comment]
Right now it only prints "no matches found" when there are no matches at all. Should we maybe print "no *more* matches found" when there's a market order that doesn't get fully matched and doesn't enter the orderbook? Should we also print something like "order fully matched" when matching finishes by matching everything? 

Also this isn't exactly a bug, it's just not how it's designed to work right now (although I agree this would be an improvement).

**Comment by raladev** [comment]
so, all flows:

1. orderbook is empty -> mkt order placed -> no matches found msg
2. orderbook contains only part of market order -> order was filled partially msg (same for limit, but also add message about placing another part to order book)
3. order book contains order, but swap was failed -> swap failed error, retry ->  no matches found msg
4. order book contains 2 orders -> successful swap with first, failed with second -> succcess msg, failed msg, order partially filled msg (same for limit, but also add message about placing another part to order book)
5. order fully filled -> order fully filled msg (same for limit order)

is it correct @sangaman ?

**Comment by kilrau** [comment]
Let's keep it simple. Suggestion: add a summary in the end of the matching procedure of how much was filled.

1. orderbook is empty or simply no price match -> "No matches found." + \n "Filled 0 BTC out of 1 BTC."
2. partial match -> Matched with ... succesfully swapped, "No more matches found." + \n "Filled 0.5 BTC out of 1 BTC."
3. Matched with ... succesfully swapped + \n "Filled 0.5 BTC out of 1 BTC."

**Comment by kilrau** [comment]
But the current state is pretty comprehensible and since we are not optimizing for traders but for market makers, this is definitely P3 and shouldn't be worked on rn.
