### ISSUE TITLE
Connext: add creation result to `create` output

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1601]
How it is:
`The following wallets were initialized: LTC, BTC`

How it should be:
`The following wallets were initialized: BTC, LTC,  ETH`

**Comment by rsercano** [comment]
Could you please assign this also, I can check this too :) @kilrau

**Comment by erkarl** [comment]
@rsercano let me know if you run into trouble implementing this.

**Comment by rsercano** [comment]
Could you please check PR @erkarl ?
