### ISSUE TITLE
Finalize swap execution

### ISSUE THREAD

**Issue by moshababo** [ExchangeUnion/xud#161]
This issue is about implementing the match/swap scenarios below. Source: https://github.com/ExchangeUnion/xud/issues/277#issuecomment-416370196

* 1.2)
** Swap success: remove ownOrder from the order book (https://github.com/ExchangeUnion/xud/issues/422) trigger order invalidation over the network. Same as `cancelOrder`.
** Swap failure: add back to order book
* 2.1)
** Swap success, remove peerOrder from the order book (already being done, just test, nothing to be done here)
** Swap failure, try match again and if no immediate match can be found - add to order book (former taker `ownOrder` becomes a maker order)
* Update client on the swap result (stream to `subscribeOrders`)
* Save swap report in `xud` database

**Comment by kilrau** [comment]
Related issue: https://github.com/ExchangeUnion/xud/issues/202

**Comment by kilrau** [comment]
Dependency: https://github.com/ExchangeUnion/xud/issues/413

**Comment by offerm** [comment]
All, please note that swap should be considered successful once we released the preImage. It should be considered final once we get the preImage from our LND but once we released the preImage we should avoid trading the order again.

**Comment by sangaman** [comment]
The maker order is being removed after the swap is complete (and therefore can't be swapped again) with #447.

**Comment by kilrau** [comment]
Missing according to @offerm:

* Allow maker to reduce the quantity suggested by the taker's SWAP_REQUEST message. I suggest not to touch this until order book integration is done and there is a good feedback/visibility to the user.
* Timeouts on RPC calls (queryroutes, sendToRoutes, sendPayments, getinfo) are missing. We should add these and handle them.
* sanity - taker to check the r_preimage it got from sendPaymentSync and compare it with the deal.preImage. Not very important
* cleanup - remove swap.reject and swap.accepted if there is no use of these. Should be done after orderBook integration
* support totalCltvDelta - This is needed to prevent a route which results in a too big lock time. This can be done now to wait until LND's #1941 is accepted.
* fees - LND's sendPayment fees should somehow be limited. This is supported on LND's side with --fee_limit. Need to decide how to support it on XUD.
* Multi routes - currently the maker to taker payment is limited to one route (best). Supporting multi-route is not complicated but should be done once we have a testing environment.

**Comment by kilrau** [comment]
https://github.com/ExchangeUnion/xud/pull/495 & https://github.com/ExchangeUnion/xud/issues/479 closes this one

**Comment by sangaman** [comment]
The last item is:

> Save swap report in xud database

That's being tracked in #562, so I'm closing this issue.
