### ISSUE TITLE
Timeout error for closechannel ETH appears sometimes

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud#1613]
### Background

Got Timeout error for 2 of 4 closechannel ETH attempts, but channel was closed successfully. It seems the timeout value should be increased,

![Screen](https://user-images.githubusercontent.com/29906866/84049980-c8b98e80-a9b5-11ea-86b2-f1c737e55436.png)

**Comment by kilrau** [comment]
To be clear: this happened when running `xucli closechannel ETH` ? Could you please paste the exact command you used (with or without `--amount` option etc). @raladev

**Comment by raladev** [comment]
> To be clear: this happened when running `xucli closechannel ETH` ? Could you please paste the exact command you used (with or without `--amount` option etc). @raladev

It was just _xucli closechannel ETH_ without amount param.

**Comment by kilrau** [comment]
Is this still happening with connext alpha.14/15 ?

**Comment by raladev** [comment]
> Is this still happening with connext alpha.14/15 ?
Yeap, got it yesterday on testnet network with alpha14 client, but never seen it for simnet network,
[Screenshot from 2020-07-08 18-30-55](https://user-images.githubusercontent.com/29906866/87024446-cd09df00-c1e1-11ea-9a21-955efeba0416.png)

**Comment by kilrau** [comment]
Did you/can you check node logs when that happens? To see if the node received anything.

**Comment by raladev** [comment]
> Did you/can you check node logs when that happens? To see if the node received anything.

Node received and correctly processed the call if i read logs correctly, it just took more then 45 sec.
[Screenshot from 2020-07-13 15-06-35](https://user-images.githubusercontent.com/29906866/87304789-08781680-c51e-11ea-8a02-943db7e6b0cd.png)
[Screenshot from 2020-07-08 18-30-55](https://user-images.githubusercontent.com/29906866/87304794-0ada7080-c51e-11ea-8036-1cb9cbadc112.png)

**Comment by raladev** [comment]
Can not reproduce with 7.0.0 version, closed.
