### ISSUE TITLE
PubKey based blocking

### ISSUE THREAD

**Issue by moshababo** [ExchangeUnion/xud#162]
1. Add to handshake: exchange  `nodePubKey` (done)

2. When blocking a peer, we're doing it according to his ip address (without specifying the port, which is irrelevant). This means we can disconnect from him immediately, before handshaking, when he tries to reconnect. A support for blocking according to `nodePubKey` need to be added. This info will be known only after handshaking. The implementation need to take into consideration that one ip address could have multiple public keys, and vise versa.

**Comment by kilrau** [comment]
Yep, definitely needed. Important to prevent Sybil attacks since staked coins are PER PUBKEY.

**Comment by itsbalamurali** [comment]
@moshababoI meant this when I meant there should be a way to disconnect via public key.

**Comment by moshababo** [comment]
Yes, I didn't thought it's important enough to implement it merely for the manual disconnection, but since we'll need it for automatic blocking anyway, we'll better make it work also for the gRPC call as you suggested.
Anyway, to implement this we'll need to do some changes in the way we're managing the peers/hosts list. Please be in touch with me before starting to implement it.
