### ISSUE TITLE
listorders and placeorder calls are blocked by stucked order from disconnected peer

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud#1622]
### Steps:
0. orderbook contains orders for matching
1. place order as a taker -> Match attempts with failures
2. disconnect maker's node ( i think it crashed because of failed swap, i have no logs of this node or access to it)
3. Match attempts ended -> Order returned to orderbook, but there is no peer for this order

### Actual results:
listorders and placeorder calls are blocked by stucked order.
[Screenshot from 2020-06-09 14-27-33](https://user-images.githubusercontent.com/29906866/84145869-57d0b000-aa63-11ea-89e1-b7120173d94d.png)
[Screenshot from 2020-06-09 14-37-11](https://user-images.githubusercontent.com/29906866/84145891-6028eb00-aa63-11ea-9bcf-8b2de2ff766d.png)
[Screenshot from 2020-06-09 14-27-36](https://user-images.githubusercontent.com/29906866/84145918-7171f780-aa63-11ea-91dc-5708ee64b2f6.png)

### Expected result:
Order is not returned to orderbook after peer disconnecting. It seems additional check should be added -> no orders that block calls.

### Logs:

[block_lndbtc.log](https://github.com/ExchangeUnion/xud/files/4752068/block_lndbtc.log)
[block_connext.log](https://github.com/ExchangeUnion/xud/files/4752069/block_connext.log)
[block_xud.log](https://github.com/ExchangeUnion/xud/files/4752070/block_xud.log)

**Comment by sangaman** [comment]
Was this done with the `debug.testing` option? It shouldn't be returning the order to the order book after it fails a swap otherwise, although maybe this involves some edge case where the order wasn't removed when the peer disconnected (as should happen) because there was some hold on it due to the ongoing swap.

**Comment by kilrau** [comment]
Could you clarify if you used `debug.testing` here or not? @raladev

**Comment by raladev** [comment]
> Could you clarify if you used `debug.testing` here or not? @raladev

if i remember correctly, i answered this question on meeting and I said that it was without debug.testing option, but im not sure.
Usually i dont use this option, so i think that i got this case without it.
