### ISSUE TITLE
DealTimedOut error instead of NoRouteFound error during swap

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud#1625]
### Background

1.There are 2 xud nodes with multi-hop connection through xud1.simnet for lnd. first one has fully synced btc node with active channel, but second has synced node with inactive btc channel.
2. Orderbook contains orders from second node + orders from xud1.simnet. Orders of second node are on first place and orders of xud1.simnet are on second place
[Screenshot from 2020-06-10 12-45-36](https://user-images.githubusercontent.com/29906866/84255170-ec4a1980-ab1a-11ea-9296-5bae44036877.png)

### Steps to reproduce

1. Send buy 0.2 ETH/BTC mkt order from first node

### Actual result:

1. 6 DealTimedOut errors instead of NoRouteErrors
2. No matching attempt with LaundryBrush after failed attepts with second node 

### Expected result:

1. NoRouteErrors
2. Matching attempt with LaundryBrush after failed attepts with second node 

### Logs:

First node(taker):
[deal_lndbtc.log](https://github.com/ExchangeUnion/xud/files/4757733/deal_lndbtc.log)
[deal_connext.log](https://github.com/ExchangeUnion/xud/files/4757734/deal_connext.log)
[deal_xud.log](https://github.com/ExchangeUnion/xud/files/4757735/deal_xud.log)

**Comment by sangaman** [comment]
Examining the logs and the code, I'm pretty sure this is not due to no route found. Maker in this case is sending ETH, and Connext doesn't use routes so the internal `getRoute` call always succeeds. On the flip side, taker actually *does* find a route for BTC even tho there's an inactive channel on the second hop. An lnd node doesn't know which channels are active or not (besides its own) and for route-finding purposes will treat all channels as active.

The swap does appear to fail because the deal is not accepted in time, although I'm not sure why. There's nothing I can see in the maker's routine to decide whether to accept a swap that would take a long time for Connext. The logs from the maker would be helpful, if you can't get them I can try to reproduce. I've seen this `DealTimedOut` failure reason several times now when trying to swap with Connext, so we ought to get to the bottom of it. @erkarl If you have any ideas let me know.

**Comment by sangaman** [comment]
This log may be relevant to the DealTimedOut error from @kilrau .

https://paste.ubuntu.com/p/rmpThFw7NB/

```
10/06/2020 19:15:24.459 [SWAPS] debug: trying to accept deal: {"quantity":1000000,"localId":"ade7a660-ab4e-11ea-b17d-7df217f869bd","price":0.11,"isBuy":false} from xudPubKey: 02d7348d32c1e97f38c582946e4430a924c7a274d03051865a7e6a7d542cce642b
10/06/2020 19:15:24.460 [SWAPS] debug: New deal: {"proposedQuantity":1000000,"pairId":"ETH/BTC","orderId":"ade7a660-ab4e-11ea-b17d-7df217f869bd","rHash":"22cb43c9abe982f79404827ff70bc5556bc381045d1bae701ec6ba1331be37b9","takerCltvDelta":200,"price":0.11,"isBuy":false,"quantity":1000000,"makerAmount":110000,"takerAmount":1000000,"makerCurrency":"BTC","takerCurrency":"ETH","makerUnits":110000,"takerUnits":10000000000000000,"takerPubKey":"indra7cJGCcqqgeSFniwcitp3q8CTqY3Wxp6ZDudmJrwj7aptikZhhn","destination":"indra7cJGCcqqgeSFniwcitp3q8CTqY3Wxp6ZDudmJrwj7aptikZhhn","peerPubKey":"02d7348d32c1e97f38c582946e4430a924c7a274d03051865a7e6a7d542cce642b","localId":"ade7a660-ab4e-11ea-b17d-7df217f869bd","phase":0,"state":0,"role":1,"createTime":1591816524460}
10/06/2020 19:15:24.461 [SWAPS] debug: got ETH block height of 1
10/06/2020 19:15:24.462 [SWAPS] debug: found route to taker with total lock duration of 100 ETH blocks (~0h)
10/06/2020 19:15:24.466 [SWAPS] debug: calculated lock buffer for first leg: 22 BTC blocks (~4h)
10/06/2020 19:15:24.467 [SWAPS] debug: lock delta for final hop to maker: 62 BTC blocks (~10h)
10/06/2020 19:15:24.753 [LND-BTC] debug: added invoice of 110000 for 22cb43c9abe982f79404827ff70bc5556bc381045d1bae701ec6ba1331be37b9 with cltvExpiry 62
10/06/2020 19:15:24.759 [SWAPS] debug: Setting SwapAccepted phase for deal 22cb43c9abe982f79404827ff70bc5556bc381045d1bae701ec6ba1331be37b9
10/06/2020 19:15:28.879 [BACKUP] debug: xud database changed
10/06/2020 19:15:32.963 [BACKUP] debug: xud database changed
10/06/2020 19:15:33.303 [SWAPS] debug: sending swap accepted packet: {"makerCltvDelta":62,"rHash":"22cb43c9abe982f79404827ff70bc5556bc381045d1bae701ec6ba1331be37b9","quantity":1000000} to peer: 02d7348d32c1e97f38c582946e4430a924c7a274d03051865a7e6a7d542cce642b
10/06/2020 19:15:33.345 [P2P] debug: received swapFailed due to DealTimedOut from 02d7348d32c1e97f38c582946e4430a924c7a274d03051865a7e6a7d542cce642b (VideoReplace): {"rHash":"22cb43c9abe982f79404827ff70bc5556bc381045d1bae701ec6ba1331be37b9","failureReason":11}
10/06/2020 19:15:33.351 [SWAPS] debug: deal 22cb43c9abe982f79404827ff70bc5556bc381045d1bae701ec6ba1331be37b9 failed due to DealTimedOut
```

There's a ~10 second delay between setting the swap accepted phase and actually sending the swap accepted packet, and by then taker has already gotten impatient and failed the deal. We currently have a 10 second limit for the deal acceptance phase. It looks like the xud backups might be what are slowing things down, as that's the only log output for most of those 10 seconds.

**Comment by sangaman** [comment]
We're writing the database backups synchronously, I suspect that is the issue as that would block the xud thread while we wait for the db write to complete. Will open a PR now to make it asynchronous and hope it makes these `DealTimedOut` errors go away.
