### ISSUE TITLE
Trading pairs thresholds 

### ISSUE THREAD

**Issue by moshababo** [ExchangeUnion/xud#163]
Define **optional** sanity thresholds for each trading pair:
* minPrice
* maxPrice
* minQuantity
* disable thresholds for specific hosts

The usage of these thresholds:
* Check thresholds on `PlaceOrder`. If not, throw meaningful threshold error.
* Drop peer orders which don't meet threshold.
* Exchanges have e.g. minimum quantities in place and could enforce them with these thresholds.

**Comment by ImmanuelSegol** [comment]
@moshababo @kilrau Can I take this one?

**Comment by kilrau** [comment]
You got it @ImmanuelSegol

**Comment by kilrau** [comment]
Adjusted Moshe's original description: removed p2p punishment. I think we shouldn't advertise thresholds and punish if a peer violates them. This would require a peer to maintain potentially thousands of different thresholds for all peers. Just filtering locally by dropping orders is the better way I believe.

**Comment by sangaman** [comment]
>  think we shouldn't advertise thresholds and punish if a peer violates them. This would require a peer to maintain potentially thousands of different thresholds for thousands of peers.

I still think doing this would be a good idea, although not a priority. I don't think it's a whole lot of data to track, and I think part of the goal here is to prevent spam. A peer that floods us with tons of tiny orders is potentially hurting us, but it's conceivable that they don't realize it's spam. Or maybe it's not conceivable really, and we don't advertise our thresholds but we do punish peers that routinely violate them.

Another idea I'm just thinking of now is making the thresholds optional but dynamic, based on the current bid/ask prices. E.g, we automatically reject orders that are an order of magnitude or more removed from the current best bid and ask  We could also set a global minimum order size in terms of BTC, and have that be the only thing that gets shared with peers. This seems a lot less tedious than setting limits for every pair, especially given that prices can change sharply and an outlandish price now may be a reasonable price in a month.

**Comment by erkarl** [comment]
> I still think doing this would be a good idea, although not a priority.

Agreed. I'd push this post initial mainnet launch. My thinking is that once we have actual trading happening on mainnet we'll get feedback where the actual bottlenecks are.

> Another idea I'm just thinking of now is making the thresholds optional but dynamic

That sounds like a great way to reduce spam orders.

**Comment by kilrau** [comment]
> I still think doing this would be a good idea, although not a priority.
> Agreed. I'd push this post initial mainnet launch

Agreed.

So this issue stays as is. Anything that needs clarification? @ImmanuelSegol

**Comment by kilrau** [comment]
Taking `minPrice` & `maxPrice` out of this, moving to https://github.com/ExchangeUnion/xud/issues/945
