### ISSUE TITLE
Swap with canceled payment stuck in Swap Recovery

### ISSUE THREAD

**Issue by sangaman** [ExchangeUnion/xud#1633]
We've observed a failed swap on the maker side falling into SwapRecovery and remaining there even when the related outgoing LND payment appears to have been canceled and does not show up in the `listpayments` output for LND. Swaps that don't have pending outgoing payments should be removed from SwapRecovery and not continuously checked. This issue tracks this peculiarity.

**Comment by kilrau** [comment]
Opened https://github.com/ExchangeUnion/xud/issues/1635 with some more details, closing here.
