### ISSUE TITLE
LND balancecheck on placeorder to not include inactive/closed channelbalance

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1636]
This issue is about fixing the current lnd balancecheck on placeorder which allows me to place order with inactive/closed channels channels.

As @sangaman mentioned in https://github.com/ExchangeUnion/xud/issues/1609#issuecomment-642434598 :
This is a little more involved, we'd need to stop relying on the `ChannelBalance` lnd call since it always includes inactive channel balance. Would we want to switch to the logic for determining trading limits as the new lnd heartbeat call? It will continuously update our trading capacities/limits more precisely than `ChannelBalance` can.

Which is probably what we would need to do. Low prio, no milestone/project for now.

**Comment by kilrau** [comment]
Ran into this today. Noticed that arby issued orders with an inactive channel today -> filling would 100% fail:
```mainnet > getbalance

Balance:
┌──────────┬───────────────┬────────────────────────────┬───────────────────────────────┐
│ Currency │ Total Balance │ Channel Balance (Tradable) │ Wallet Balance (Not Tradable) │
├──────────┼───────────────┼────────────────────────────┼───────────────────────────────┤
│ BTC      │ 0.00936272    │ 0 (0.00936272 inactive)    │ 0                             │
├──────────┼───────────────┼────────────────────────────┼───────────────────────────────┤
│ ETH      │ 0.20796119    │ 0.10936819                 │ 0.098593                      │
├──────────┼───────────────┼────────────────────────────┼───────────────────────────────┤
│ USDT     │ 0             │ 0                          │ 0                             │
└──────────┴───────────────┴────────────────────────────┴───────────────────────────────┘
mainnet > tradinglimits

Trading Limits:
┌──────────┬───────────────────┬────────────┐
│ Currency │ Max Buy           │ Max Sell   │
├──────────┼───────────────────┼────────────┤
│ BTC      │ 0.00352051        │ 0.00923075 │
├──────────┼───────────────────┼────────────┤
│ ETH      │ 90071992.54740991 │ 0.10936819 │
├──────────┼───────────────────┼────────────┤
│ USDT     │ 90071992.54740991 │ 0          │
└──────────┴───────────────────┴────────────┘
```

Bumping prio.

**Comment by raladev** [comment]
outbound balance for placeorder check is not calculated correctly for lnd.

`29/07/2020 15:15:51.467 [RPC] error: call /xudrpc.Xud/PlaceOrderSync errored with code 9: BTC outbound balance of 0 is not sufficient for order amount of 276960793`

but tradinglimits call clearly shows there's enough balance.

```
simnet > tradinglimits -j
{
  "limitsMap": [
    [
      "BTC",
      {
        "maxsell": 276960793,
        "maxbuy": 213030157
      }
    ],
```
