### ISSUE TITLE
Seed node updates don't propagate on existing db

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1645]
### Background

It looks like adding/changing seed nodes in the xud codebase does **not** propagate these in an existing xud database.

This is an environment that was created with `beta.3` and after xud upgrade to `beta.4` it did **not** attempt to connect to the newly added seed nodes (#1616 & #1623 ), just the existing one (which is down by now):
```
12/06/2020 09:12:16.319 [P2P] info: Connecting to known / previously connected peers
12/06/2020 09:12:18.583 [P2P] debug: Connected pre-handshake to 127.0.0.1:32768
12/06/2020 09:12:18.872 [P2P] debug: Peer 02e2fb25a63e6e1df25a883e3d19e8048131571808eba13e9ada68231625d1f8c0 (VersionUphold): closing socket. reason: ConnectedToSelf
12/06/2020 09:12:18.878 [P2P] warn: could not open connection to inbound peer (02e2fb25a63e6e1df25a883e3d19e8048131571808eba13e9ada68231625d1f8c0 (VersionUphold)): cannot attempt connection to self
12/06/2020 09:12:18.880 [P2P] info: Peer 02e2fb25a63e6e1df25a883e3d19e8048131571808eba13e9ada68231625d1f8c0 (VersionUphold) socket closed
12/06/2020 09:12:19.010 [P2P] verbose: Verified reachability of advertised address: et6vfjftixwa4dqqwvermffbyxqlu5utxovyp2dz7tcru7wov4r744qd.onion:18885
12/06/2020 09:12:35.801 [RPC] debug: received call /xudrpc.Xud/ListPeers
12/06/2020 09:12:38.965 [RPC] debug: received call /xudrpc.Xud/ListPeers
12/06/2020 09:12:44.678 [RPC] debug: received call /xudrpc.Xud/ListPeers
12/06/2020 09:12:46.330 [P2P] warn: could not open connection to outbound peer (037a74737630bb5a9979762b2163ef9f95c81e00caf347bacc17f16991cdbb61f7@xud1.testnet.exchangeunion.com:18885): could not connect to peer at xud1.testnet.exchangeunion.com:18885: Proxy connection timed out
12/06/2020 09:12:48.529 [RPC] debug: received call /xudrpc.Xud/ListPeers
Jun 12 09:12:50.000 [notice] Closed 1 streams for service [scrubbed].onion for reason resolve failed. Fetch status: No more HSDir available to query.
12/06/2020 09:12:50.376 [P2P] warn: could not open connection to outbound peer (037a74737630bb5a9979762b2163ef9f95c81e00caf347bacc17f16991cdbb61f7@pso32ae2l5nyh3clgee2nj2hgpmcnluhaqibjm2r2fjcsn4gclxfmrid.onion:18885): could not connect to peer at pso32ae2l5nyh3clgee2nj2hgpmcnluhaqibjm2r2fjcsn4gclxfmrid.onion:18885: Socks5 proxy rejected connection - HostUnreachable
12/06/2020 09:12:50.380 [P2P] info: Completed start-up connections to known peers
```

### Your environment

* version of `xud`: `1.0.0-beta.4-43c03e7`
* which operating system (`uname -a` on *Nix): ubuntu 20.04 arm 64

**Comment by sangaman** [comment]
This is how it's designed currently. But I *would* expect seed nodes to get shared by nodes that we are connected to, it's just regular peer discovery, as tracked in the related issue #1646.

I can change this to attempt to connect to seed nodes each time xud starts up, but I think it'd be cleaner to ensure seed nodes are being shared. We can also always manually connect to new seed nodes.

**Comment by kilrau** [comment]
I consider https://github.com/ExchangeUnion/xud/issues/1646 and this two separate issues. What happened was:
`beta.3`: only one seed node xud1.testnet.exchangeunion.com
`beta.4`: two new seed nodes, xud1.testnet.exchangeunion.com offline
Result: xud didn't find any peers.

In order to prevent this, xud should always propagate new seed nodes to the database on start.

**Comment by kilrau** [comment]
Adding this to the `Hardening` project, this should be fixed rather soon imo.

**Comment by rsercano** [comment]
> I consider #1646 and this two separate issues. What happened was:
> `beta.3`: only one seed node xud1.testnet.exchangeunion.com
> `beta.4`: two new seed nodes, xud1.testnet.exchangeunion.com offline
> Result: xud didn't find any peers.
> 
> In order to prevent this, xud should always propagate new seed nodes to the database on start.

Currently xud checks if db is not filled and initDB flag is true then it loads seeds to database, I can change this to compare seeds on file with database and save/overwrite/delete correspondingly to the db, what do you think? @sangaman @kilrau

**Comment by erkarl** [comment]
> Currently xud checks if db is not filled and initDB flag is true then it loads seeds to database, I can change this to compare seeds on file with database and save/overwrite/delete correspondingly to the db, what do you think? @sangaman @kilrau

What do you think about adding new entries in the seeds file to the database?

Alternatively, we could considering setting up sequelize migrations: https://sequelize.org/master/manual/migrations.html

**Comment by rsercano** [comment]
> > Currently xud checks if db is not filled and initDB flag is true then it loads seeds to database, I can change this to compare seeds on file with database and save/overwrite/delete correspondingly to the db, what do you think? @sangaman @kilrau
> 
> What do you think about adding new entries in the seeds file to the database?
> 
> Alternatively, we could considering setting up sequelize migrations: https://sequelize.org/master/manual/migrations.html

I've been using flyway in our java projects, which means on every migration you need to write a db query like update/delete even insert, I don't know if this migration works like that, if so it's worth a shot.

**Comment by erkarl** [comment]
>  Or I can implement a very simple logic to do that :) Your call

Let's wait for @sangaman's and @kilrau's thoughts on this. I'd go for the easy option:
- if there are new entries in the seeds file -> add them to the database when xud starts

**Comment by rsercano** [comment]
> > Or I can implement a very simple logic to do that :) Your call
> 
> Let's wait for @sangaman's and @kilrau's thoughts on this. I'd go for the easy option:
> 
> * if there are new entries in the seeds file -> add them to the database when xud starts

Yes but what about changed or deleted ones?

**Comment by kilrau** [comment]
> if there are new entries in the seeds file -> add them to the database when xud starts

That sounds good to me. Assigned issue to you @rsercano

**Comment by kilrau** [comment]
`changed` should be treated as `new`, `deleted` can be ignored for now

**Comment by rsercano** [comment]
Alright gotcha!
