### ISSUE TITLE
Merge matching engine queues

### ISSUE THREAD

**Issue by moshababo** [ExchangeUnion/xud#166]
Since we're not supporting `internalMatching=false` mode anymore, we can merge `ownOrders` + `peerOrders` priority queues. 
But we need to make sure we the we keep the bulk of `ownOrders` accessible seperately, sorted by timestamp (that might just be the order which they were added, since timestamping is local), because that will be required for the `orders` p2p packet payload (#149).

**Comment by itsbalamurali** [comment]
Closing this issue as it has been merged
