### ISSUE TITLE
Not constant connext swaps problems

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud#1660]
This issue is created to monitor all swap related issues that sometimes appears during connext swaps but can not be reproduced reliably. Usually it is SwapTimeout errors or RejectInstallation Errors.

1. Reject installation during swap + infinite 'checking outgoing payment status for swap ' 
Swap time: 15/06/2020 11:04:44
[maker_f2.zip](https://github.com/ExchangeUnion/xud/files/4780915/maker_f2.zip)
indra log contains "App install failed: Error: Could not deposit sufficient collateral to resolve transfer for receiver:" error
[export_2020-06-15-14-45-45-382_f75f76cb-882d-4dca-bbb1-1f205b828986.jsonl.gz](https://github.com/ExchangeUnion/xud/files/4781023/export_2020-06-15-14-45-45-382_f75f76cb-882d-4dca-bbb1-1f205b828986.jsonl.gz)

2. SwapTimeout + SendPaymentFailure https://github.com/ExchangeUnion/xud/issues/1570 & https://github.com/ExchangeUnion/xud/issues/1585
looks like the one problem but with different types of pairs

**Comment by kilrau** [comment]
Bumping this to P1 as a general issue for connext swap stability - we are aiming for 100% for sunny conditions (no network issues, no slow disk, server is fine).

**Comment by raladev** [comment]
I have not seen the first error for a long time, and the second problem has separate issue. 
Other reliably reproducible connext bugs have their own issues.
It seems we can close this one. 
@kilrau
