### ISSUE TITLE
Remove orders of a disconnected peer

### ISSUE THREAD

**Issue by moshababo** [ExchangeUnion/xud#168]
When disconnecting from a peer, remove all his orders from the order book. If a general disconnection from the network is happening, all orders should be dropped altogether, and not for each peer separately.

**Comment by moshababo** [comment]
This can be done separately. Also, I want @kilrau to review this issue first.

**Comment by itsbalamurali** [comment]
@moshababo  @kilrau  Now I don't think we have any requirement of this since we are not going to store orders anymore right?

**Comment by moshababo** [comment]
We do, because we're referring here to the in-memory orders.

**Comment by kilrau** [comment]
Issue looks good. Yep doesn't matter if in-memory or on disk, we'll need this.

**Comment by itsbalamurali** [comment]
Closing as implemented in #192.
