### ISSUE TITLE
maker_shutdown_after_1st_htlc simulation test is failing

### ISSUE THREAD

**Issue by erkarl** [ExchangeUnion/xud#1698]
Follow-up from https://github.com/ExchangeUnion/xud/pull/1680#issuecomment-650038520

**Comment by LePremierHomme** [comment]
This was an error related to the processing time of htlc expiration in lnd. It solved after extending the wait time from 25sec to 45sec. 
I'm leaving this open for a reminder to improve this mechanism (by checking the status in shorter intervals).

**Comment by sangaman** [comment]
This will be fixed by [`def9e50` (#1680)](https://github.com/ExchangeUnion/xud/pull/1680/commits/def9e50c12c49962776034fb083ca8e2b4dd00d3) when it's merged - it's now using a retry loop rather than a fixed wait to check for when the channel has closed due to the expired htlc.
