### ISSUE TITLE
xud should cancel invoice when receiving 404 from connext

### ISSUE THREAD

**Issue by erkarl** [ExchangeUnion/xud#1708]
Depends on: https://github.com/connext/rest-api-client/issues/31

**Problem**
At the moment connext's `/hashlock-status` endpoint (for `swapClient.lookupPayment`) only returns 500 status codes which is quite bad since if the connext transfer fails for some reason so that the HTLC is never created it will go into recovery and start querying it.

**Solution**
It should get 404 status code back from connext if the HTLC does not exist. That would mean that it was never created and we can also cancel the invoice on the other chain.

**Comment by kilrau** [comment]
Bumping prio here.

**Comment by erkarl** [comment]
Solved by https://github.com/ExchangeUnion/xud/pull/1822
