### ISSUE TITLE
[Concept]  maxFee/maxLockTime swaps thresholds

### ISSUE THREAD

**Issue by moshababo** [ExchangeUnion/xud#171]
Define swaps thresholds for max fee and max lock time for `lnd`.
Before instantiating a swap, when querying the route, make sure that these thresholds do not exceed.

Also need to check for equivalent problem/solution for Raiden swaps.

**Comment by kilrau** [comment]
Covered by https://github.com/ExchangeUnion/xud/issues/528 "totalCltvDelta"
