### ISSUE TITLE
Force close of channel because of out_pending_htlc

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud#1724]
### Steps to reproduce

1. I got out_pending_htlc (htlc that should be received) by this bug https://github.com/ExchangeUnion/xud/issues/1637
2. Wait 

### Result

1. After 11:24 - 10:19 =1:05 i got force closed btc channel as a maker and returned back out_pending_htlc to the taker
2. channel of taker was fine

[Screenshot from 2020-07-13 17-45-16](https://user-images.githubusercontent.com/29906866/87318181-ac6abd80-c530-11ea-912b-9a96055c7f4e.png)
[Screenshot from 2020-07-13 17-14-00](https://user-images.githubusercontent.com/29906866/87317859-3f572800-c530-11ea-9206-bbfa3c1977dc.png)

Simnet lndbtc node logs - [simnet_lndbtc_node.log](https://github.com/ExchangeUnion/xud/files/4913186/simnet_lndbtc_node.log)

Logs of client nodes - https://github.com/ExchangeUnion/xud/issues/1637#issuecomment-657485019

**Comment by kilrau** [comment]
@sangaman help me to remember: Is it that we don't cancel invoices in such a scenario as of now because we don't have information from the connext client that a payment permanently failed?
