### ISSUE TITLE
(streamorders stream)/xud crashed after 1h of active arby using

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud#1727]
### Actual behaviour

![Screenshot from 2020-07-13 20-28-00](https://user-images.githubusercontent.com/29906866/87335597-3f175680-c549-11ea-9103-e2b5e9c1efd9.png)

### Expected behaviour

No crashes

**Comment by kilrau** [comment]
Any idea for this one? Was this an existing issue or caused be the `SubscribeSwapAccepted` PR we just merged (which would be bad)? @sangaman

**Comment by raladev** [comment]
> Any idea for this one? Was this an existing issue or caused be the `SubscribeSwapAccepted` PR we just merged (which would be bad)? @sangaman

It was only taker's node, so if I understood correctly there is no SwapAccepted logic for this side.

**Comment by raladev** [comment]
got this crash today but with xud instead of streamorders call
Bump to P1
[xud_fall.log](https://github.com/ExchangeUnion/xud/files/4926229/xud_fall.log)

**Comment by erkarl** [comment]
The error looks pretty deep into NodeJS core. I wonder if others are able to reproduce it...

**Comment by sangaman** [comment]
This is indeed something very low level and I'm guessing system specific that isn't playing nice with grpc. I suspect it's related to node v14, which was released fairly recently. @raladev Can you confirm the node version you're using? 

This is also a good reminder for me to revisit #1605, as the grpc dependency we're currently using is slated to be deprecated after April 2021.

**Comment by raladev** [comment]
> This is also a good reminder for me to revisit #1605, as the grpc dependency we're currently using is slated to be deprecated after April 2021.

```
native@ubuntu:~$ node
Welcome to Node.js v14.0.0.
Type ".help" for more information.
```
