### ISSUE TITLE
xud should detect if seed is unencrypted

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1729]
Reported by @michael1011 :
> I didn't enable the xud encryption but now that it is the default, xud is telling me that it needs unlocking. XUD should detect that when seed isn't encrypted even when --noencrypt is false.

**Comment by raladev** [comment]
i think that encryption option does not work at all for now.
Tested it yesterday with clean combined setup (with encryption false i was asked to create wallet), but it requires verification.

**Comment by kilrau** [comment]
I think the problem is rather: xud-docker only works with xud encryption true, so if you have a "combined" setup and set `noencrypt = true` in xud, xud-docker will ask you to create a wallet anyways. That is ok for now.

To test if `noencrypt = false/true` works as intended, one has to use a standalone native xud only.

**Comment by raladev** [comment]
> I think the problem is rather: xud-docker only works with xud seed encryption, so if you have a "combined" setup and set `noencrypt = true` in xud, xud-docker will ask you to create a wallet anyways. That is accepted behavior for now.
> 
> To test if `noencrypt = false/true` works as intended, one has to use a standalone native xud only.

how xud-docker can ask me if i used native cli instead of xud-docker utils?

**Comment by kilrau** [comment]
Hmm.. not sure. that has to be tested then! Could you run it and attach logs?

**Comment by raladev** [comment]
> Hmm.. not sure. that has to be tested then! Could you run it and attach logs?
Tested, i misused xud.conf - [Screen](https://user-images.githubusercontent.com/29906866/87550098-5c6a3300-c6b7-11ea-8228-0dc4d22a1afa.png)
 The option works fine for clean installation after config fix.
