### ISSUE TITLE
Implement `RemoveInvoice` for connext client

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1730]
The upcoming connext release will feature cooperatively cancelling an htlc:
- https://github.com/connext/rest-api-client/issues/39
- https://github.com/connext/indra/pull/1310

We should implement usage of the new call the same way we use to clean up invoices to avoid pending htlcs in lnd.

**Comment by erkarl** [comment]
I think logic wise nothing will change from swaps module. Just https://github.com/ExchangeUnion/xud/blob/master/lib/connextclient/ConnextClient.ts#L402 needs to be implemented.

**Comment by kilrau** [comment]
Waiting for answer here: https://github.com/connext/indra/issues/1173#issuecomment-658650056
