### ISSUE TITLE
Local/Global orderId

### ISSUE THREAD

**Issue by moshababo** [ExchangeUnion/xud#175]
Add `orderId` property to the high-level API (`placeOrder`, `cancelOrder`, etc.).
 Inside of `xud` it should be represented as `clientOrderId`, while attaching a globally unique `orderId` to it. The mapping between them should be managed by `xud`, so that the client won't be aware of that.

`peerOrders` should be exposed to the client with their globally unique `orderId`, and not with their `clientOrderId`. (@kilrau)

**Comment by kilrau** [comment]
Described in https://github.com/ExchangeUnion/xud/issues/176#issuecomment-401547923
