### ISSUE TITLE
Add `requestCollateral` to `openchannel eth` flow

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1756]
Problem: when swapping for the first time, indra will need to collateralize the channel which often results in a timeout (on-chain confirmation taking too long), but at least in a very slow swap. Bad first time UX.

Solution: In addition to [increasing swap timeout to 90s](https://github.com/ExchangeUnion/xud/issues/1752) to avoid most swap timeouts when a live collateralization is involved, we want to request collateral from the indra node right away in the `openchannel` flow via `client.requestCollateral`. The indra node decides based on collateralization profile if and how much to collateralize. E.g. we are targeting to collateralize the same as the deposit amount to have a 50:50 balanced channel.

cc @ArjunBhuptani please point us to how such a collateralization profile looks like.

**Comment by sangaman** [comment]
I have a couple of questions for the collateralization when opening channels

1. Do we want the rest-api-client to request collateral on every call to `deposit`, or rather should we pass a flag indicating whether we want to request collateral or not? xud can always pass that flag
2. `client.requestCollateral` takes a `tokenAddress` - is that the same as `assetId`? I don't see `tokenAddress` used anywhere in the rest client.

**Comment by kilrau** [comment]
> * Do we want the rest-api-client to request collateral on every call to `deposit`, or rather should we pass a flag indicating whether we want to request collateral or not? xud can always pass that flag

If possible with flag, since this enables us to lateron give the user the decision to use a (paid) collateral service or not.

> * `client.requestCollateral` takes a `tokenAddress` - is that the same as `assetId`? I don't see `tokenAddress` used anywhere in the rest client.

@erkarl confirmed that it is the same
