### ISSUE TITLE
Split order ids

### ISSUE THREAD

**Issue by moshababo** [ExchangeUnion/xud#176]
Each order can be split, locally or remotely, so representing an order merely by its original `orderId` isn't very effective.
One approach to tackle this would be to generate a new `orderId` for each order split, and to associate them all with the original `orderId`. 
Another approach would be to keep one single `orderId`, but to use the `orderId` + `quantity` tuple for every order-related action (cancellation, swap update, etc.). So for example, if I want to cancel an order, and to invalidate it over the network, i'll do so by specifying the quantity as well, so that in practice each order will be treated as a max sum of potential quantity, which can only be decreased over time. This approach seems more suitable to me, but we need to think this through together, in case I overlooked something.

**Comment by kilrau** [comment]
I thought about it for a bit and would go for the orderID+quantity tuple. This is how it could look like
``
1. placeOrder(internalOrderID, 1)
uuid() = 2494843749, 1 BTC, maker order
save (internalOrderID, 2494843749)
broadcast(2494843749, 1, BTC, 100, LTC)

2. 4023482337 10 LTC for 0.1 BTC coming in as taker, successfully fills 2494843749 partly with 0.1 BTC:
updateLocally(2494843749, 0.9, BTC) and broadcastUpdate(2494843749, 0.9, BTC)
saveToTradeHistory(4023482374, 2494843749, 0.1, BTC, 10, LTC)
``

**Comment by kilrau** [comment]
On a different topic we came accross this again with @sangaman and it seems we don't have a consensus to keep the same orderID and just decrease the quantity on a partial fill. Please both give opinions with detailed reasoning here so we can close this asap @moshababo @sangaman

**Comment by sangaman** [comment]
Ah yeah sorry I hadn't seen this discussion. In gitter I was against the idea of using the Id+quantity tuple to uniquely identify orders. It would complicate such things, for example our orderbook right now is a map of Id to order. Technically it's possible to use Id+qty as the key, but it would be more complicated. Also I can't imagine we'd want to allow for two orders with the same Id but different quantities in our books.

But I think what @moshababo is saying is that the Id is still the sole identifier, but that order-related actions would always require a quantity along with the ID. So when you cancel an order or fill an order, you must specify the amount being filled or canceled. I think that's a good approach. We keep the same Id until an order is completely filled or canceled, and each time the available quantity for an order is reduced we update our peers.

**Comment by kilrau** [comment]
Ok, good to be implemented then @michael1011 . Updated comment from above:

I agree on `orderID` as sole identifier, but `orderID`+quantity tuple for all order-related actions. Examples:
```
1. placeOrder(internalOrderID, 1, BTC, 100, LTC)
uuid() = 2494843749, no match = maker order
save (internalOrderID, 2494843749)
broadcast(2494843749, 1, BTC, 100, LTC)

2. incoming 4023482337 10 LTC for 0.1 BTC as taker, successfully fills 2494843749 partly with 0.1 BTC:
updateLocally(2494843749, 0.9, BTC) and broadcastUpdate(2494843749, 0.9, BTC)
saveToTradeHistory(4023482374, 2494843749, 0.1, BTC, 10, LTC)
```

**Comment by kilrau** [comment]
This is still open because partial matches not done yet, right? @michael1011
