### ISSUE TITLE
Refactor `this.failDeal` logic

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1763]
Follow-up of https://github.com/ExchangeUnion/xud/pull/1761: As discussed in https://github.com/ExchangeUnion/xud/pull/1761#pullrequestreview-456499186 , this issue is about making `this.failDeal` explicit and by default not failing the deal.

**Comment by sangaman** [comment]
As I understand this it's just to change the logic for when we fail deals upon receiving a `SwapFailedPacket` from a peer.
