### ISSUE TITLE
[Concept] Positive reputation

### ISSUE THREAD

**Issue by moshababo** [ExchangeUnion/xud#178]
Need to decide whether we want to apply positive score to peers (mostly for successful swaps and fee payment), or continue with the current, negative-only approach. It's mostly to know whether we need to do some semantic changes in the code.

Also, whether we want to call this a reputation system, considering it's local only.

**Comment by moshababo** [comment]
@kilrau the reputation isn't merely for blacklisting. It's also to prioritize between peers.

**Comment by sangaman** [comment]
I like the idea of positive peer scores. As for whether it's a reputation system, I don't think that's exactly the best term since it would in fact be local. I think just calling it something like a "peer score" is fine, and it starts at zero and can move in either direction.

**Comment by kilrau** [comment]
increasing reputation = add positive reputation & potentially remove old neg reputation

clearly define positive & negative events

@michael1011 please link to events in code

**Comment by sangaman** [comment]
#470 introduced positive score for successful swaps, I think we can close this.

**Comment by michael1011** [comment]
@kilrau We have one positive event right now which is a [successful swap](https://github.com/ExchangeUnion/xud/pull/470/files#diff-e3b9c918367fab773a683447d6b0ed31R13).

I can't think of any other positive events right now so I agree with @sangaman to close this issue-
