### ISSUE TITLE
Orders are still in order book after successful swap on recovery stage

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud#1794]
Steps:

1. Place 8 sell BTC/ETH orders as a maker
2. Send 1 buy order as a maker that will be matched with all 8 orders (
[Screenshot from 2020-08-06 18-28-00](https://user-images.githubusercontent.com/29906866/89550661-94761900-d812-11ea-835c-f9eb5c0614ea.png)
)
3. Wait first successful match in xud log
4. docker rm -f simnet_lndbtc_1 for maker (after this, channel of taker that was connected to simnet node was closed with no reason)
5. Wait first recovery attempt from maker -> all recovery attempts were failed because of disabled BTC node
6. Return lndbtc node back
7. Wait second recovery attempt -> success for several orders and fail for other
8. Check listorders for maker and taker

Actual result:
Most of orders are still in order book but both users have them in tradehistory (successful orders).
[Screenshot from 2020-08-06 17-40-20](https://user-images.githubusercontent.com/29906866/89550713-a788e900-d812-11ea-8eb7-a2429baddfeb.png)

[returned_orders_xud_taker.log](https://github.com/ExchangeUnion/xud/files/5035885/returned_orders_xud_taker.log)
[returned_orders_xud_maker.log](https://github.com/ExchangeUnion/xud/files/5035886/returned_orders_xud_maker.log)

Note:
For me it looks like only  first order was removed because it was matched before lndbtc restart, but others was not removed because swap flow of them was finished on recovery stage.

**Comment by sangaman** [comment]
Fixing this will require using the swap recovery module *only* for when xud crashes or is otherwise restarted while a swap is ongoing, and then having similar functionality within Swaps that keeps track of orders, swap successes, et.c..
