### ISSUE TITLE
Swap not monitored after connext failed sendpayment and xud restarted

### ISSUE THREAD

**Issue by sangaman** [ExchangeUnion/xud#1799]
https://github.com/ExchangeUnion/xud/pull/1761#issuecomment-665781237

> There is still no monitoring continuation for maker side after maker's xud restart.
> 
> Steps:
> 
>     1. place 9 sell ETH/BTC orders as a maker, fill them all by 1 order of a taker -> most of swaps failed (**29/07/2020 15:33:58.510 in maker's log**)
> 
>     2. monitoring messages in maker logs each 5 mins (**29/07/2020 15:47:33.970 in maker's log**)
> 
>     3. restart maker's xud (**29/07/2020 16:01:13.444 in maker's log**)
> 
>     4. wait -> No monitor messages
> 
>     5. shutdown both envs -> swap err messages in the taker's xud log after disconnecting from all peers. (**29/07/2020 16:17:41.217 in taker's log**)
> 
> 
> [Screenshot from 2020-07-29 19-36-15](https://user-images.githubusercontent.com/29906866/88828815-68381800-d1d4-11ea-9fc2-9951cf37fd9e.png)
> [Screenshot from 2020-07-29 19-36-27](https://user-images.githubusercontent.com/29906866/88828813-6706eb00-d1d4-11ea-96d8-bf3f95074e74.png)
> 
> [monitor_xud_taker.log](https://github.com/ExchangeUnion/xud/files/4996243/monitor_xud_taker.log)
> [monitor_xud_maker.log](https://github.com/ExchangeUnion/xud/files/4996244/monitor_xud_maker.log)
> 
> maker's xud db - [gofile.io/d/7GKTmK](https://gofile.io/d/7GKTmK)
> taker's xud db - [gofile.io/d/uqMD6s](https://gofile.io/d/uqMD6s)

> This is very helpful but after some investigation I'm pretty sure this is a separate issue from this PR and the issue it indends to fix. It's due to the fact that a connext sendpayment call can "fail" while the payment is still in limbo. It's actually somewhat related to #1794, the solution is to not fail the deal when a sendpayment calls, and to have a mechanism within swaps to monitor swaps that are still in an active status even after they've timed out and even after our attempts to send payment have failed, up until we get confirmation that all HTLCs are canceled/expired. Everything in `SwapRecovery` will then only be used for when xud crashes or is restarted while there are active swaps.

**Comment by kilrau** [comment]
This one is definitely still open, opened another issue: https://github.com/ExchangeUnion/xud/issues/1818
