### ISSUE TITLE
`listpeers` should show all pairs of peer

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1801]
I just noticed that listpeers shows only the pairs of a peer that are currently active on my local node too. In my example, lndltc is down and ETH/BTC is the only functioning pair I have. All peers in listpeers show ETH/BTC as their pairs only, even though they have many more pairs. I don't think that's what we want, I htink I want to see all supported pairs of a peer there, even if I do not have them.

**Comment by rsercano** [comment]
May I check this?

**Comment by rsercano** [comment]
Currently active pairs are being defined as swappable pairs and all peers show their active pairs, so it's not actually related with local node. 

So in this case, do we still want to show all pairs including inactive ones? @kilrau

**Comment by raladev** [comment]
There is 2 cases:
1. U dont see pair if u have no currency from this pair
2. U dont see pair if peer has problem with Lnd/connext (they are not synced for example and as a result your node deactivates this currency for this peer)

[Screenshot from 2020-09-11 14-10-08](https://user-images.githubusercontent.com/29906866/92919724-ab271580-f439-11ea-8345-69234ee7a667.png)


So, what we should do in both cases> @kilrau

**Comment by kilrau** [comment]
1. show the pair (this is more or less what this issue is about: show pairs from peers as is, no matter if I have a pair or currency configured on my local node)
2. don't show the pair (current behavior is fine) Remind me again: when/how will it get re-activated?
