### ISSUE TITLE
Replace order call should be atomic

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud#1805]
Steps:
1. buy 2 ltc/usdt 0.01 1
2. buy 3 ltc/usdt 0.01 2
3. buy 2 ltc/usdt 0.01 1 -r 2 - > `6 ALREADY_EXISTS: order with local id 1 already exists`
4. Check order book

Actual result:
orderbook contains only one order (first) because second one was removed, but new was not placed because id error

Expected result:
orderbook contains 2 orders, order replacement is failed.

**Comment by kilrau** [comment]
In short: the order replace call should be atomic, atm it is not (remove can succeed, place can fail)
