### ISSUE TITLE
Replace order call should issue new order with *same id* by default

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1806]
Currently e.g. `buy 2 ltc/btc 0.01 -r 1` places the new transaction with a new (non-1) local id. Workaround is explicitely stating the new order's id, if we want it to be `1` too: `buy 2 ltc/btc 0.01 1 -r 1`. This shouldn't be required and xud should issue the re-place order with the id as the previous one by default.

**Comment by sangaman** [comment]
If this refers to localId only, it shouldn't be too hard to change the current behavior so the new order matches the old order's localId. Am I understanding that right?

**Comment by kilrau** [comment]
> Am I understanding that right?

Perfectly right! @sangaman
