### ISSUE TITLE
Discover node's own external IP

### ISSUE THREAD

**Issue by moshababo** [ExchangeUnion/xud#181]
When joining the network (`pool.connect`), discover node's own external IP address.
This can be done by making an HTTP request to a url like http://ipv4.icanhazip.com/.

This should be used by a node to recognize self in hosts list (avoid connecting to itself #177), and to verify reachability (#182). We might also want to include on `getInfo` call.

**Comment by offerm** [comment]
I'm not sure this is the right solution. A node may have multiple IPs on multiple devices. Also, there can routing rules on the router like port forwarding which you can't see that way.

Instead, I suggest to implement the mechanism done by LND: allow the user to add `externalip` as `host:port` to the configuration file.

**Comment by kilrau** [comment]
Good input @offerm . I'd say the "auto-detect my external IP" of this issue first because it's convenient, covers most cases and needed for #177. The manual "`externalip` as `host:port` to the configuration file" in a second step. You can open a new issue for this, alpha or beta @michael1011 .

**Comment by kilrau** [comment]
Sure, your call @michael1011
