### ISSUE TITLE
periodically cleanup pending app install proposals for connext

### ISSUE THREAD

**Issue by erkarl** [ExchangeUnion/xud#1813]
rest-api-client is going to expose another endpoint `client.rejectInstallApp` to cleanup pending app install proposals.

TBD: when should xud hit that endpoint. We definitely don't want to do this on a timer to avoid weird race conditions.

**Comment by kilrau** [comment]
> We definitely don't want to do this on a timer to avoid weird race conditions.
Agreed, that could "clean up" an in-flight htlc.

The only reliable way I can think of for xud to only clean up apps install proposals of apps that are expired (Status `EXPIRED`?) or more advanced (and given the connext client exposes the current block height) we could calculate if the app is older than x blocks and clean up then, to make sure it must have timed out on xud side.

```
{
  "senderIdentifier": "indra5ZEUGrxw9jre4N7rM3PqF2ULfK3yZN1SeXs1YQW3dzFEZ2XbxZ",
  "receiverIdentifier": "indra6vofLDtPcuzX5a5xbcZXKtrk6pR6pfTjMXr6ehjpWdLmwjqmss",
  "assetId": "0x0000000000000000000000000000000000000000",
  "amount": "25000000000000000",
  "lockHash": "0x6cb2edeaa8742809c2e8480c95b22fe38325840c89a6a7db17ba6af4d3c2e43f",
  "status": "PENDING",
  "preImage": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "expiry": "10657447"
}
```

**Comment by erkarl** [comment]
Rest-api-client now does this on client startup. Think this is sufficient for now?

**Comment by kilrau** [comment]
Yes
