### ISSUE TITLE
xucli doesn't work if L2 is not set up properly

### ISSUE THREAD

**Issue by hatmer** [ExchangeUnion/xud#1815]
### Background

I want to test xud only and don't need to use Lightning/Connext. Xucli cannot be used without the L2 systems fully functioning.

### Steps to reproduce

Clean native install of xud. Compile and run xud without first setting up L2 systems. Attempt to run xucli.

### Expected behaviour

Xud should start and connect to the xud network without requiring L2 systems.

### Actual behaviour

Xucli throws error about LTC/LND/BTC networks not being connected

<img width="1615" alt="Screenshot 2020-08-16 at 14 22 07" src="https://user-images.githubusercontent.com/2366125/90334376-8623bc00-dfcd-11ea-8003-cfecb167f6df.png">

### Logs (/bin/xud)

(node:14514) ExperimentalWarning: The fs.promises API is experimental
16/08/2020 12:31:08.894 [RPC] info: gRPC server listening on localhost:28886
16/08/2020 12:31:09.107 [DB] info: connected to database /home/hatmer/.xud/xud-simnet.db
16/08/2020 12:31:09.133 [LND-BTC] debug: loaded tls cert from /home/hatmer/.lnd/tls.cert
16/08/2020 12:31:09.134 [LND-LTC] debug: loaded tls cert from /home/hatmer/.lnd/tls.cert
16/08/2020 12:31:09.135 [LND-LTC] info: could not load macaroon at /home/hatmer/.lnd/data/chain/litecoin/simnet/admin.macaroon, this is normal before creating a new wallet
16/08/2020 12:31:09.135 [LND-LTC] info: new status: Initialized
16/08/2020 12:31:09.137 [LND-LTC] info: waiting for wallet to be initialized...
16/08/2020 12:31:09.146 [RAIDEN] info: new status: Initialized
16/08/2020 12:31:09.147 [RAIDEN] info: trying to verify connection to raiden with uri: localhost:5001
16/08/2020 12:31:09.159 [RAIDEN] info: new status: Disconnected
16/08/2020 12:31:09.159 [RAIDEN] error: Error: connect ECONNREFUSED 127.0.0.1:5001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
16/08/2020 12:31:09.160 [RAIDEN] error: could not verify connection to raiden at localhost:5001, retrying in 5000 ms: Error: connect ECONNREFUSED 127.0.0.1:5001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
16/08/2020 12:31:09.161 [LND-BTC] debug: loaded macaroon from /home/hatmer/.lnd/data/chain/bitcoin/simnet/admin.macaroon
16/08/2020 12:31:09.162 [LND-BTC] info: new status: Initialized
16/08/2020 12:31:09.162 [LND-BTC] info: trying to verify connection to lnd at localhost:10009
16/08/2020 12:31:09.179 [LND-BTC] info: new status: WaitingUnlock
16/08/2020 12:31:09.180 [LND-BTC] error: could not verify connection at localhost:10009, error: {"code":12,"metadata":{"_internal_repr":{},"flags":0},"details":"unknown service lnrpc.Lightning"}, retrying in 5000 ms
16/08/2020 12:31:09.181 [GLOBAL] info: Node key is encrypted, unlock with 'xucli unlock', 'xucli create', or 'xucli restore'
16/08/2020 12:31:14.147 [RAIDEN] info: trying to verify connection to raiden with uri: localhost:5001
16/08/2020 12:31:14.149 [RAIDEN] error: Error: connect ECONNREFUSED 127.0.0.1:5001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
16/08/2020 12:31:14.150 [RAIDEN] error: could not verify connection to raiden at localhost:5001, retrying in 5000 ms: Error: connect ECONNREFUSED 127.0.0.1:5001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
16/08/2020 12:31:15.139 [LND-LTC] info: new status: WaitingUnlock
16/08/2020 12:31:19.151 [RAIDEN] info: trying to verify connection to raiden with uri: localhost:5001
16/08/2020 12:31:19.153 [RAIDEN] error: Error: connect ECONNREFUSED 127.0.0.1:5001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
16/08/2020 12:31:19.153 [RAIDEN] error: could not verify connection to raiden at localhost:5001, retrying in 5000 ms: Error: connect ECONNREFUSED 127.0.0.1:5001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
16/08/2020 12:31:23.877 [RPC] debug: received call /xudrpc.XudInit/CreateNode
16/08/2020 12:31:24.155 [RAIDEN] info: trying to verify connection to raiden with uri: localhost:5001
16/08/2020 12:31:24.157 [RAIDEN] error: Error: connect ECONNREFUSED 127.0.0.1:5001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
16/08/2020 12:31:24.163 [RAIDEN] error: could not verify connection to raiden at localhost:5001, retrying in 5000 ms: Error: connect ECONNREFUSED 127.0.0.1:5001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
16/08/2020 12:31:24.217 [LND-LTC] info: new status: Disconnected
16/08/2020 12:31:24.218 [LND-LTC] debug: error on initWallet: 14 UNAVAILABLE: failed to connect to all addresses
16/08/2020 12:31:24.218 [LND-LTC] error: could not initialize wallet: 14 UNAVAILABLE: failed to connect to all addresses
{ code: 13,
  message:
   'could not initialize lnd-LTC: 14 UNAVAILABLE: failed to connect to all addresses',
  name: 'UnknownError' }
16/08/2020 12:31:24.230 [RPC] error: call /xudrpc.XudInit/CreateNode errored with code 13: could not initialize lnd-LTC: 14 UNAVAILABLE: failed to connect to all addresses
16/08/2020 12:31:24.243 [LND-BTC] debug: error on initWallet: 2 UNKNOWN: wallet already exists
16/08/2020 12:31:24.245 [LND-BTC] error: could not initialize wallet: 2 UNKNOWN: wallet already exists
16/08/2020 12:31:29.205 [LND-LTC] error: AssertionError [ERR_ASSERTION]: awaitWalletInit should not be called from a status besides Initialized or Unlocked
    at LndClient.<anonymous> (/home/hatmer/xud/dist/lndclient/LndClient.js:358:38)
    at Generator.next (<anonymous>)
    at /home/hatmer/xud/dist/lndclient/LndClient.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/home/hatmer/xud/dist/lndclient/LndClient.js:23:12)
    at LndClient.awaitWalletInit (/home/hatmer/xud/dist/lndclient/LndClient.js:337:42)
    at LndClient.<anonymous> (/home/hatmer/xud/dist/lndclient/LndClient.js:402:30)
    at Generator.next (<anonymous>)
    at /home/hatmer/xud/dist/lndclient/LndClient.js:27:71
    at new Promise (<anonymous>)
16/08/2020 12:31:29.253 [RAIDEN] info: trying to verify connection to raiden with uri: localhost:5001
16/08/2020 12:31:29.274 [RAIDEN] error: Error: connect ECONNREFUSED 127.0.0.1:5001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
16/08/2020 12:31:29.276 [RAIDEN] error: could not verify connection to raiden at localhost:5001, retrying in 5000 ms: Error: connect ECONNREFUSED 127.0.0.1:5001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
16/08/2020 12:31:31.735 [RAIDEN] info: created raiden keystore with master seed and empty password in /home/hatmer/.ethereum
^C16/08/2020 12:31:32.811 [GLOBAL] info: XUD is shutting down
16/08/2020 12:31:32.814 [LND-BTC] info: new status: Disconnected
16/08/2020 12:31:32.824 [CONNEXT] error: cannot set status to Disconnected from NotInitialized
16/08/2020 12:31:32.825 [CONNEXT] error: cannot set status to Disconnected from NotInitialized
16/08/2020 12:31:32.840 [RPC] info: gRPC server completed shutdown
16/08/2020 12:31:32.858 [GLOBAL] info: XUD shutdown gracefully

**Comment by erkarl** [comment]
Related issue: https://github.com/ExchangeUnion/xud/issues/1576

**Comment by kilrau** [comment]
> Related issue: #1576

True, we would need to do that one first. Since #1576 is also needed for https://github.com/ExchangeUnion/xud-docker/issues/140, we should do that one first.
