### ISSUE TITLE
SwapRecovery stops monitoring swap after xud restart

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1818]
This is from makers perspective. What happened: taker filled our `sell eth/btc` order, taker's eth side needed to be collateralized which caused the connext eth payment to timeout (60s) as well as the xud swap (90s) and the eth payment was never sent.

Due to lack of https://github.com/ExchangeUnion/xud/issues/1708, `xud` currently doesn't know about the status of the connext htlc, thus assumes it's up and throws the swap into swap recovery. So far correct.

But then when I went ahead and restarted `xud`, swap recovery was not monitoring the swap anymore. Checking the xud db, the swap state changed to `1` (errored). We need to find out what changed the swap state to `1` and prevent that from happening so that swap recovery continues monitoring the swap.

![image](https://user-images.githubusercontent.com/19181985/90397399-129ab100-e098-11ea-9a8c-0ec689e50ce3.png)

xud log: https://paste.ubuntu.com/p/Y8ZzWhwZJk/

**Comment by raladev** [comment]
looks like duplicate of https://github.com/ExchangeUnion/xud/issues/1799

**Comment by sangaman** [comment]
> looks like duplicate of #1799

Agreed, closing as duplicate.
