### ISSUE TITLE
Fake orders are in orderbook after OrderNotFound err

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud#1838]
### Steps to reproduce

1. Run arby version without throttling as a maker
2. Try to fill orders by small MARKET orders as a taker (Note: u should get several OrderNotFound errors)
3. listorders as a taker

### Actual behaviour

orderbook of taker contains several fake orders, maker has no these orders

[Screenshot from 2020-08-25 20-14-17](https://user-images.githubusercontent.com/29906866/91305262-76695c00-e7b3-11ea-95ed-d5a8d7611b3a.png)
[Screenshot from 2020-08-25 20-12-55](https://user-images.githubusercontent.com/29906866/91305255-75382f00-e7b3-11ea-93e1-0cedbfd39545.png)
[Screenshot from 2020-08-25 20-08-56](https://user-images.githubusercontent.com/29906866/91305250-736e6b80-e7b3-11ea-86fc-81a02022a08d.png)

### Expected behaviour

No fake orders

### Note

https://github.com/ExchangeUnion/xud/pull/1830/files may be the reason, but not sure

### Question

May we avoid situations when taker changes local orderbook without maker's interaction?

**Comment by sangaman** [comment]
> ### Question
> 
> May we avoid situations when taker changes local orderbook without maker's interaction?

What do you mean by this exactly? There have to be some changes due to local matching, but generally we don't remove or add peer orders unless we receive a packet from the peer.
