### ISSUE TITLE
Xud crash for taker after  some sucessful/unsuccessful swaps

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud#1851]
Taker logs:
[testnet_connext_taker.log](https://github.com/ExchangeUnion/xud/files/5151399/testnet_connext_taker.log)
[testnet_utils_taker.log](https://github.com/ExchangeUnion/xud/files/5151400/testnet_utils_taker.log)
[testnet_xud_crash_taker.log](https://github.com/ExchangeUnion/xud/files/5151401/testnet_xud_crash_taker.log)

![Screenshot from 2020-08-31 19-22-10](https://user-images.githubusercontent.com/29906866/91742678-49f07e00-ebbf-11ea-98c0-350337d181a8.png)
!
![Screenshot from 2020-08-31 19-34-04](https://user-images.githubusercontent.com/29906866/91743770-00089780-ebc1-11ea-88af-ca6b265c20fa.png)

**Comment by kilrau** [comment]
Maker logs: https://paste.ubuntu.com/p/t2cpndGT6Q/

**Comment by kilrau** [comment]
Maker:
```
testnet > getbalance

Balance:
┌──────────┬───────────────┬────────────────────────────┬───────────────────────────────┐
│ Currency │ Total Balance │ Channel Balance (Tradable) │ Wallet Balance (Not Tradable) │
├──────────┼───────────────┼────────────────────────────┼───────────────────────────────┤
│ BTC      │ 0.73413619    │ 0.10685344                 │ 0.62728275                    │
├──────────┼───────────────┼────────────────────────────┼───────────────────────────────┤
│ ETH      │ 32.397688     │ 2.89773                    │ 29.499958                     │
├──────────┼───────────────┼────────────────────────────┼───────────────────────────────┤
│ LTC      │ 210.88649808  │ 0                          │ 210.88649808                  │
└──────────┴───────────────┴────────────────────────────┴───────────────────────────────┘
```
```
testnet > tradehistory
Trades:
┌─────────────────┬────────────────┬───────┬─────────────┬────────────────────────────┬───────────┬────────────────────────┐
│ Execution       │ Price          │ Role  │ Order Id    │ Order Id    (Counterparty) │ Swap Hash │ Executed At            │
├─────────────────┼────────────────┼───────┼─────────────┼────────────────────────────┼───────────┼────────────────────────┤
│ Sell 0.0001 ETH │ 0.03813472 BTC │ Maker │ cfb4f140... │ N/A (MediaSolution)        │ 40b91f... │ 8/31/2020, 4:06:52 PM  │
├─────────────────┼────────────────┼───────┼─────────────┼────────────────────────────┼───────────┼────────────────────────┤
```

**Comment by kilrau** [comment]
As just discussed with @sangaman , we would want to catch this error and make xud not crash for this error, just print an error message and keep going. As of now, we can't come up with a path that could be "dangerous" for continuing after a deal successfully completed. It's too late anyways :man_shrugging:
