### ISSUE TITLE
Handling LND without support for hold invoices

### ISSUE THREAD

**Issue by michael1011** [ExchangeUnion/xud#1875]
~~When connecting XUD with encrypted seed to a LND node outside of xud-docker which is *not* unlocked by XUD in the startup process, all swaps fail with:~~

```
08/09/2020 19:46:43.634 [LND-BTC] info: new status: WaitingUnlock
08/09/2020 19:46:43.647 [ORDERBOOK] error: swap between orders e27434d0-f20b-11ea-bded-9d25c44f1374 & 051960a0-f20c-11ea-b218-cb614d1d8fae failed due to UnexpectedClientError
08/09/2020 19:46:43.648 [ORDERBOOK] warn: swap for 200000 failed during order matching due to UnexpectedClientError, will repeat matching routine for failed quantity
08/09/2020 19:46:43.666 [LND-BTC] info: new status: Unlocked
08/09/2020 19:46:43.667 [LND-BTC] info: wallet unlocked
08/09/2020 19:46:43.701 [ORDERBOOK] error: swap between orders ddf7ad60-f20b-11ea-8eee-252d04d42534 & 051960a0-f20c-11ea-b218-cb614d1d8fae failed due to SwapClientNotSetup
08/09/2020 19:46:43.702 [ORDERBOOK] warn: swap for 200000 failed during order matching due to SwapClientNotSetup, will repeat matching routine for failed quantity
08/09/2020 19:46:43.716 [ORDERBOOK] error: swap between orders 5920a760-ed45-11ea-9ac9-6b0a18aadca8 & 051960a0-f20c-11ea-b218-cb614d1d8fae failed due to SwapClientNotSetup
08/09/2020 19:46:43.718 [ORDERBOOK] warn: swap for 100000 failed during order matching due to SwapClientNotSetup, will repeat matching routine for failed quantity
08/09/2020 19:46:47.040 [LND-BTC] info: trying to verify connection to lnd at 10.0.1.14:10009
08/09/2020 19:46:47.873 [LND-BTC] info: new status: ConnectionVerified
```

~~I can't swap on my environment because this behavior occurs every time I attempt a swap~~

I figured out the root cause of this issue: LND was not compiled with support for `invoicesrpc` (hold invoices). XUD should throw proper errors in this scenario so that the user can figure out what's wrong and sanity check the LND node (version and required RPC subsystems) on startup

**Comment by kilrau** [comment]
@sangaman are you taking on this colourful issue?

**Comment by rsercano** [comment]
I'm not sure what's wrong with this issue, **SwapClientNotSetup** seems like a proper error to me 🤔

**Comment by erkarl** [comment]
> I'm not sure what's wrong with this issue, **SwapClientNotSetup** seems like a proper error to me thinking Also I suppose this comes from LND

The current implementation does not display informative error message to the user when lnd is compiled without the hold invoices flag. This results in a bad UX as the user has no idea why the swaps are failing. This issue is about xud figuring out that lnd has no support for hold invoices and displaying a nice message to the user.

**Comment by rsercano** [comment]
I see let me find out how to decide lnd has invoices support or not.

**Comment by kilrau** [comment]
You can e.g. check if the `invoicesrpc` server is running or not

**Comment by rsercano** [comment]
I'm confused :( There's no API way to learn if `invoicesrpc` is working on https://api.lightning.community/#lnd-grpc-api-reference. 

There're invoices methods but no way to ping or check status of it.

**Comment by rsercano** [comment]
Summarized from dc chat:

1. While connecting to LND just before connectionVerified status (so that we ensure connection works) I'll call addholdInvoice with 0 satoshis.
2. If it fails I'll add "hold invoices not supported" message into getinfo and disconnect from LND with proper log message
3. If it succeeds I'll call cancelinvoice for my invoice.
