### ISSUE TITLE
Easy way to cancel orders in CLI

### ISSUE THREAD

**Issue by michael1011** [ExchangeUnion/xud#1878]
As CLI user I am missing an easy way to cancel my own orders. Right now I have to `xucli listorders -j`, find my order and the its ID and copy paste it into `xucli removeorder <id>` which is tedious right now and will be nearly impossible to do once there are more orders on the network

**Comment by kilrau** [comment]
I guess the UI will be the better place to cancel a particular order. But I agree that a "cancel all open orders" functionality, will think about it some more.

**Comment by rsercano** [comment]
If you guys still want to do this, may I take? @kilrau

**Comment by kilrau** [comment]
You got it. UX should be something like this:
```
> xucli cancelallorders
Are you sure you want to cancel all open orders? [Y/n] Y
Cancelled order with id abc123
Cancelled order with id xyz123
Failed to cancel order with id xzy456
No more orders found
```

I bet we can find issues with higher prio though @rsercano

**Comment by rsercano** [comment]
> You got it. UX should be something like this:
> 
> ```
> > xucli cancelallorders
> Are you sure you want to cancel all open orders? [Y/n] Y
> Cancelled order with id abc123
> Cancelled order with id xyz123
> Failed to cancel order with id xzy456
> No more orders found
> ```
> 
> I bet we can find issues with higher prio though @rsercano

Of course, I just couldn't find one except #1668 which literally confuses me a lot 😅 Time to time I'm checking it, but just let me know if there's any other issue I can take other than assigned ones which have higher prio
