### ISSUE TITLE
xud doesn't seem to recognize `IncompatibleVersion` correctly

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1879]
@raladev and I noticed a couple of `IncompatibleVersion` messages after today's upgrade to `1.0.1`. It looks like there might be a problem in sorting versions correctly if a peer is on a different version that I am:

How does my xud know that [current min compatible version `1.0.0-rc.1`](https://github.com/ExchangeUnion/xud/pull/1874/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R3) is lower than `1.0.0` and all of `1.0.0-rc1`, `1.0.0-rc2` and `1.0.0` are compatible?

**Comment by rsercano** [comment]
As I quickly took a look at this, we're comparing versions with [semver npm package](https://www.npmjs.com/package/semver) and it uses https://semver.org/, so to summarize by [quoting](https://semver.org/#spec-item-11);

> Example: 1.0.0-alpha < 1.0.0-alpha.1 < 1.0.0-alpha.beta < 1.0.0-beta < 1.0.0-beta.2 < 1.0.0-beta.11 < 1.0.0-rc.1 < 1.0.0.

**Comment by kilrau** [comment]
Let's do a quick manual test with https://www.npmjs.com/package/semver if: 1.0.0-rc.1 < 1.0.0-rc.2 < 1.0.0 < 1.0.1

**Comment by rsercano** [comment]
![image](https://user-images.githubusercontent.com/3640368/93317564-52c78d80-f816-11ea-902b-622826fd8536.png)

All spits out -1 meaning first given version is lower than second given version, which's 1.0.0-rc.1 < 1.0.0-rc.2 < 1.0.0 < 1.0.1

**Comment by kilrau** [comment]
Well it's working then and why we saw these `IncompatibleVersion` messages remains a mystery. Thanks! Closing.
