### ISSUE TITLE
[Connext]  walletdeposit returns 500 server error

### ISSUE THREAD

**Issue by jgarzik** [ExchangeUnion/xud#1887]
### Background

1. Successful xud setup, using all-default configuration.
2. Successful `walletdeposit eth`.   0.8 ETH appear as expected in the Wallet Balance column of `getbalance`.
3. Attempts to `openchannel` fail with the same error:
```
mainnet > openchannel ETH 0.8
Error: 2 UNKNOWN: failed to open ETH channel for 80000000: connext server error 500: Internal Server Error
```

### Your environment

* version of `xud`: 1.0.1-d04e4bd5    
* which operating system (`uname -a` on *Nix): `Linux whi1 4.15.0-117-generic #118-Ubuntu SMP Fri Sep 4 20:02:41 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
* version of `btcd`, `bitcoind`, `ltcd`, `litecoind`, `geth`, `parity`, `connext`, `lnd` or other chain backend: all xud defaults for light-node:
connext 1.3.3
LND-BTC 0.11.0-beta commit=v0.11.0-beta 
LND-LTC 0.11.0-beta.rc1 commit=v0.11.0-beta.rc1 

* any other relevant environment details:

### Steps to reproduce

1. deposit ETH
2. openchannel on ETH

### Expected behaviour

channel opens

### Actual behaviour

500 server error, shown above

**Comment by jgarzik** [comment]
```
mainnet > status
┌───────────┬────────────────────────────────────────────────┐
│ SERVICE   │ STATUS                                         │
├───────────┼────────────────────────────────────────────────┤
│ bitcoind  │ Ready (light mode)                             │
├───────────┼────────────────────────────────────────────────┤
│ litecoind │ Ready (light mode)                             │
├───────────┼────────────────────────────────────────────────┤
│ geth      │ Ready (light mode)                             │
├───────────┼────────────────────────────────────────────────┤
│ lndbtc    │ Ready                                          │
├───────────┼────────────────────────────────────────────────┤
│ lndltc    │ Ready                                          │
├───────────┼────────────────────────────────────────────────┤
│ connext   │ Ready                                          │
├───────────┼────────────────────────────────────────────────┤
│ boltz     │ Ready                                          │
├───────────┼────────────────────────────────────────────────┤
│ xud       │ Ready                                          │
└───────────┴────────────────────────────────────────────────┘
```

**Comment by jgarzik** [comment]
Tried same with 0.7 ETH, rather than 0.8 as displayed in `getbalance`.

That succeeded.

**Comment by kilrau** [comment]
Thank you for opening this issue! That sounds very much like https://github.com/connext/rest-api-client/issues/93 (gas estimation missing), what do you think guys? @michael1011 @erkarl

**Comment by raladev** [comment]
Yeap, it is definitely gas err.
1. User should pay commission for channel opening (for eth transaction)
2. If there in no enough ETH-> 500 connext err and gas err in connext logs

We just need more elegant err for that like err in lnd:
```
simnet > openchannel BTC 2.49994513 OzoneYellow
Error: 2 UNKNOWN: failed to open BTC channel for 249994513 with OzoneYellow: 2 UNKNOWN: not enough witness outputs to create funding transaction, need 2.5000215 BTC only have 2.49994513 BTC  available
```

**Comment by raladev** [comment]
tested, it is not gas err.

when u trying to open channel for full amount, some micro eth's are added to your amount, as a result u got not enough funds err.

[Screenshot from 2020-09-11 14-45-18](https://user-images.githubusercontent.com/29906866/92922531-a9ac1c00-f43e-11ea-8eba-22808fffee5b.png)
[Screenshot from 2020-09-11 14-45-17](https://user-images.githubusercontent.com/29906866/92922532-aa44b280-f43e-11ea-9404-111ec474bd13.png)

**Comment by erkarl** [comment]
@jgarzik thanks for reporting this. Looks like there was a small precision loss when converting our internal units. I've added a temporary fix to this in https://github.com/ExchangeUnion/xud/pull/1893

Longer term solution is to move all internal amounts to use something like bignumber.js or bn.js.

CC @raladev

**Comment by jgarzik** [comment]
I guess there are two issues?

1. Precision in balances output leads user to use incorrect balance value in commands.
2. Using an invalid (too-large) balance gives a very confusing error message, versus a "X specified amount < Y available balance" message.

**Comment by erkarl** [comment]
> I guess there are two issues?

Exactly. One of them we can fix from xud side. The other needs a proper status code from connext client in order to display the nicer error message to the end user.

>     1. Precision in balances output leads user to use incorrect balance value in commands.
https://github.com/ExchangeUnion/xud/pull/1893 as a quick fix + eventually move away from JavaScript number type. I'll start planning this refactoring as it's annoying to have these issues pop up.

>     2. Using an invalid (too-large) balance gives a very confusing error message, versus a "X specified amount < Y available balance" message.

Connext side: https://github.com/connext/rest-api-client/issues/23

Thanks again for bringing this issue up.

**Comment by kilrau** [comment]
> I'll start planning this refactoring as it's annoying to have these issues pop up.

Here is the issue btw: https://github.com/ExchangeUnion/xud/issues/1797 and I just bumped the prio.
