### ISSUE TITLE
Unable to deposit newly-added ERC20 currency, without environment restart

### ISSUE THREAD

**Issue by jgarzik** [ExchangeUnion/xud#1888]
### Background

1. Successful light client xud setup.
2. Successful walletdeposit ETH.
3. Successfully added DAI via addcurrency.
4. Successfully added ETH/DAI pair via addpair.
5. `walletdeposit DAI` failed:
```
mainnet > walletdeposit dai
Error: 9 FAILED_PRECONDITION: swapClient for currency DAI not found
```

Describe your issue here.

### Your environment

- version of xud: 1.0.1-d04e4bd5
- which operating system (uname -a on *Nix): Linux whi1 4.15.0-117-generic #118-Ubuntu SMP Fri Sep 4 20:02:41 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- version of btcd, bitcoind, ltcd, litecoind, geth, parity, connext, lnd or other chain backend: all xud defaults for light-node:
connext 1.3.3
LND-BTC 0.11.0-beta commit=v0.11.0-beta
LND-LTC 0.11.0-beta.rc1 commit=v0.11.0-beta.rc1

any other relevant environment details:

### Steps to reproduce

see above.

### Expected behaviour

DAI deposit address generated.

### Actual behaviour

error shown above.

**Comment by jgarzik** [comment]
```
mainnet > listpairs
Trading Pairs:
┌──────────────┐
│ Trading pair │
├──────────────┤
│ ETH / BTC    │
├──────────────┤
│ LTC / BTC    │
├──────────────┤
│ LTC / USDT   │
├──────────────┤
│ BTC / USDT   │
├──────────────┤
│ ETH / DAI    │
└──────────────┘

mainnet > listcurrencies

Currencies:
┌────────┬────────┬────────────────────────────────────────────┬─────────────┐
│ Ticker │ Digits │ Token Address                              │ Swap Client │
├────────┼────────┼────────────────────────────────────────────┼─────────────┤
│ BTC    │ 8      │                                            │ Lnd         │
├────────┼────────┼────────────────────────────────────────────┼─────────────┤
│ LTC    │ 8      │                                            │ Lnd         │
├────────┼────────┼────────────────────────────────────────────┼─────────────┤
│ ETH    │ 18     │ 0x0000000000000000000000000000000000000000 │ Connext     │
├────────┼────────┼────────────────────────────────────────────┼─────────────┤
│ USDT   │ 6      │ 0xdAC17F958D2ee523a2206206994597C13D831ec7 │ Connext     │
├────────┼────────┼────────────────────────────────────────────┼─────────────┤
│ DAI    │ 18     │ 0x6B175474E89094C44Da98b954EedeAC495271d0F │ Connext     │
└────────┴────────┴────────────────────────────────────────────┴─────────────┘
```

**Comment by sangaman** [comment]
I think this is likely related to #1746 and #1111. I'll revisit those to make sure the steps above work. Does restarting xud allow the `walletdeposit` call to succeed?

**Comment by erkarl** [comment]
In addition to the above issues we'll also need to activate DAI from the connext node. Otherwise, it won't accept deposits (openchannel will be rejected).

**Comment by jgarzik** [comment]
> In addition to the above issues we'll also need to activate DAI from the connext node. Otherwise, it won't accept deposits (openchannel will be rejected).

How can we reach a point where users supply arbitrary ERC20's?

**Comment by jgarzik** [comment]
> I think this is likely related to #1746 and #1111. I'll revisit those to make sure the steps above work. Does restarting xud allow the `walletdeposit` call to succeed?

Confirmed.   Restarting the entire environment (including xud) allowed `walletdeposit DAI` to succeed.

**Comment by jgarzik** [comment]
After restarting environment, depositing DAI was successful.  It shows up under wallet balances.

Opening a channel fails, as @erkarl predicted:
```
mainnet > openchannel DAI 200
Error: 2 UNKNOWN: failed to open DAI channel for 20000000000: connext server error 500: Internal Server Error
mainnet > openchannel DAI 199.9
Error: 2 UNKNOWN: failed to open DAI channel for 19990000000: connext server error 500: Internal Server Error
mainnet > openchannel DAI 199
Error: 2 UNKNOWN: failed to open DAI channel for 19900000000: connext server error 500: Internal Server Error
```

**Comment by jgarzik** [comment]
Splitting out DAI-payment-channel issue to separate issue.

This issue centers around unable to
1. Add new ERC20 currency
2. Deposit to currency via `walletdeposit`

The workaround is to restart the environment.

**Comment by kilrau** [comment]
> Splitting out DAI-payment-channel issue to separate issue.

Makes sense, thank you! I marked this issue as fixed by https://github.com/ExchangeUnion/xud/pull/1746.
