### ISSUE TITLE
CLI: Show order UUID for reference

### ISSUE THREAD

**Issue by jgarzik** [ExchangeUnion/xud#1891]
The `orderbook` and `listorders` commands do not show the order id (UUID).

As a result, it appears(?) necessary to manually record the UUID, for future cancellation.

**Comment by raladev** [comment]
> The `orderbook` and `listorders` commands do not show the order id (UUID).
> 
> As a result, it appears(?) necessary to manually record the UUID, for future cancellation.

table view does not contain all info about orders to do not make this table too big.

To get id of order u can use `-j` flag for `listorders` commands to get full info about orders - `listorders -j`
orderbook have no info about orders, so u cant get order id using orderbook command.


```

**Comment by jgarzik** [comment]
Thanks.   Looks sufficient; closing.
