### ISSUE TITLE
Activate DAI in connext

### ISSUE THREAD

**Issue by jgarzik** [ExchangeUnion/xud#1894]
(split from #1888)

### Background

1. Successful xud setup, using all-default configuration.
2. Successful `walletdeposit eth`.   0.8 ETH appear as expected in the Wallet Balance column of `getbalance`.
3. Successful `walletdeposit dai`
3. Attempts to `openchannel DAI` fail with the same error.   See paste at end of this issue.

### Your environment

* version of `xud`: 1.0.1-d04e4bd5    
* which operating system (`uname -a` on *Nix): `Linux whi1 4.15.0-117-generic #118-Ubuntu SMP Fri Sep 4 20:02:41 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
* version of `btcd`, `bitcoind`, `ltcd`, `litecoind`, `geth`, `parity`, `connext`, `lnd` or other chain backend: all xud defaults for light-node:
connext 1.3.3
LND-BTC 0.11.0-beta commit=v0.11.0-beta 
LND-LTC 0.11.0-beta.rc1 commit=v0.11.0-beta.rc1 

### Steps to reproduce

1. deposit DAI
2. openchannel on DAI

### Expected behaviour

channel opens

### Actual behaviour

500 server error, shown above

```
mainnet > getbalance

Balance:
┌──────────┬───────────────┬────────────────────────────┬───────────────────────────────┐
│ Currency │ Total Balance │ Channel Balance (Tradable) │ Wallet Balance (Not Tradable) │
├──────────┼───────────────┼────────────────────────────┼───────────────────────────────┤
│ BTC      │ 0.0396386     │ 0.0396386                  │ 0                             │
├──────────┼───────────────┼────────────────────────────┼───────────────────────────────┤
│ DAI      │ 200           │ 0                          │ 200                           │
├──────────┼───────────────┼────────────────────────────┼───────────────────────────────┤
│ ETH      │ 0.796892      │ 0.7                        │ 0.096892                      │
├──────────┼───────────────┼────────────────────────────┼───────────────────────────────┤
│ LTC      │ 0             │ 0                          │ 0                             │
├──────────┼───────────────┼────────────────────────────┼───────────────────────────────┤
│ USDT     │ 0             │ 0                          │ 0                             │
└──────────┴───────────────┴────────────────────────────┴───────────────────────────────┘

mainnet > openchannel DAI 200
Error: 2 UNKNOWN: failed to open DAI channel for 20000000000: connext server error 
500: Internal Server Error
mainnet > openchannel DAI 199.9
Error: 2 UNKNOWN: failed to open DAI channel for 19990000000: connext server error
500: Internal Server Error
mainnet > openchannel DAI 199
Error: 2 UNKNOWN: failed to open DAI channel for 19900000000: connext server error
500: Internal Server Error
```

**Comment by jgarzik** [comment]
In #1888 @erkarl commented:
> In addition to the above issues we'll also need to activate DAI from the connext node. Otherwise, it won't accept deposits (openchannel will be rejected).

**Comment by kilrau** [comment]
Yup, explanation why connext currencies need to be "activated": the connext node where one opens a channel to needs to actually hold a decent amount of this currency to "collateralize" channels - the node needs to have some local balance of this particular currency itself to forward payments. So as of now, a user actually shouldn't be able to add an arbitrary ERC20 token.

Todos:
1. connext client should know about all supported tokens of the node @rhlsthrm @erkarl 
2. xud should only allow adding from this "supported tokens" list, ideally via ticker symbol only @sangaman 
3. brainstorm ideas how we could make it happen that a user indeed could add any arbitrary ERC20 token. Thinking about this a bit, maybe there is room for a new uniswap-style liquidity provider role!?

**Comment by kilrau** [comment]
And we can and should activate DAI of course.

**Comment by erkarl** [comment]
DAI is now activated on mainnet.
