### ISSUE TITLE
Lazy Collateralization

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1896]
We just discussed to keep the scope of https://github.com/ExchangeUnion/xud/pull/1885 as is and tackle https://github.com/ExchangeUnion/xud/issues/1584 next and expose reserved balance internally in xud.

In a third step, this issue is about triggering a request for collateralization for the orders up to the full amount of `reserved balance`, but let the order pass through `placeorder` as long as the connext channel is sufficiently collateralized for this one single order.

**Comment by kilrau** [comment]
Question regarding: https://github.com/ExchangeUnion/xud/pull/1885#issuecomment-692068765 does the node queue collateralization requests if the node is currently busy with another collateralization of this channel? If not, we need to queue in xud for lazy collateralization to work properly.

**Comment by sangaman** [comment]
> Question regarding: [#1885 (comment)](https://github.com/ExchangeUnion/xud/pull/1885#issuecomment-692068765) does the node queue collateralization requests if the node is currently busy with another collateralization of this channel? If not, we need to queue in xud for lazy collateralization to work properly.

It does not, but queuing makes sense since don't want multiple collateral requests happening at the same time. When the collateral request is complete, we can check if there's any shortage of collateral for the orders in the order books and then request at that point in time.
