### ISSUE TITLE
No tor address in getinfo response

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud#1903]
### Actual result
![Screenshot from 2020-09-16 16-38-21](https://user-images.githubusercontent.com/29906866/93345203-35f18100-f83b-11ea-8008-ab0fac97d3b9.png)

### Expected result
Tor address in address field if tor used
Clearnet address in address field if tor is not used

**Comment by kilrau** [comment]
Since this is working in all simnet environments I have, we'd need some more details here. Please check xud logs for what tor is doing.

Also: did lnd's get tor addresses?

**Comment by raladev** [comment]
> Since this is working in all simnet environments I have, we'd need some more details here. Please check xud logs for what tor is doing.
> 
> Also: did lnd's get tor addresses?

if i remember correctly there was lnd adresses and i also another peer saw my address using listpeers.

Closed, can not reproduce for now.
