### ISSUE TITLE
Make `tradinglimits` account for lightning chan reserve

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1945]
**EDIT:** renamed this issue, new goal [below](https://github.com/ExchangeUnion/xud/issues/1945#issuecomment-713448164).

LND `0.12` will return [inbound balance with the `channelbalance` call](https://github.com/lightningnetwork/lnd/pull/4512/files). Since this is considerably more efficient and accurate than our current "iterate through lnd's `listchannels`" approach, we should move to this call too once lndbtc & lndltc 0.12 are released.

Also I just double checked the following:
- lnd's `channelbalance` is simply all `local_balance` fields of all channels accumulated
- same way does `channelbalance` include all `remote_balance` fields of all channels accumulated with the PR above.

Here is the **but**: lnd's `local_balance` and `remote_balance` subtract the `commit_fee`, but **not** the channel reserve `chan_reserve_sat` which is essentially non-usable balance. Question is: do we want to manually subtract channel reserves from our local and remote balances to give the user a correct picture of what balance is actually usable?

**Comment by sangaman** [comment]
> do we want to manually subtract channel reserves from our local and remote balances to give the user a correct picture of what balance is actually usable?

I think it makes sense to subtract channel reserves since it is non tradeable balance. However, to do so wouldn't we still need to iterate through the list of channels?

Also, do we actually know that this new approach would be more efficient or accurate than iterating through the list of channels? I don't know why our current approach wouldn't be accurate, and my guess would be it's at least *roughly* the same in terms of efficiency - either way it's not computationally expensive to iterate through a list of up to a couple dozen channels.

**Comment by kilrau** [comment]
> I think it makes sense to subtract channel reserves since it is non tradeable balance. However, to do so wouldn't we still need to iterate through the list of channels?

Yes, that's why I brought it up. The new PR doesn't include something like total inbound/outbound chan reserve...

> Also, do we actually know that this new approach would be more efficient or accurate than iterating through the list of channels? I don't know why our current approach wouldn't be accurate, and my guess would be it's at least roughly the same in terms of efficiency - either way it's not computationally expensive to iterate through a list of up to a couple dozen channels.

Yep, for us even more accurate since we'd exclude channel reserve.

Summary of the todo's:
- move tradinglimits' `maxBuy` & `maxSell` to iterating through channels (currently we are using lnd's `channelbalance` for `maxSell` I believe)
- subtract chan reserve from tradinglimits' `maxBuy` & `maxSell` 
- rename `reservedOutbound` -> `reservedSell` & `reservedInbound` -> `reservedBuy` for clarity as discussed [here](https://discord.com/channels/547402601885466658/709337789304668160/768153554753028116).

**Comment by rsercano** [comment]
> move tradinglimits' maxBuy & maxSell to iterating through channels (currently we are using lnd's channelbalance for maxSell I believe)

Currently we're already iterating through channels for lnd, correct me if I'm mistaken @sangaman.

> subtract chan reserve from tradinglimits' maxBuy & maxSell

And currently that's how maxSell & maxBuy is being calculated: 
``` 
const swapCapacities = await swapClient.swapCapacities(currency);
      const reservedOutbound = this.outboundReservedAmounts.get(currency) ?? 0;
      const reservedInbound = this.inboundReservedAmounts.get(currency) ?? 0;
      const availableOutboundCapacity = Math.max(0, swapCapacities.totalOutboundCapacity - reservedOutbound);
      const availableInboundCapacity = Math.max(0, swapCapacities.totalInboundCapacity - reservedInbound);

      return {
        reservedOutbound,
        reservedInbound,
        maxSell: Math.min(swapCapacities.maxOutboundChannelCapacity, availableOutboundCapacity),
        maxBuy: Math.min(swapCapacities.maxInboundChannelCapacity, availableInboundCapacity),
      };
```

In here while calculating available outbound & inbound capacities we're subtracting reserved amounts?

**Comment by rsercano** [comment]
And for fee calculation I'm not sure how to handle it, can somebody please guide me?

**Comment by kilrau** [comment]
Channel reserve is already accounted for by now (see https://github.com/ExchangeUnion/xud/pull/1988#issuecomment-724897010) and pre-calculating routing fees is hardly possible so I am closing here.
