### ISSUE TITLE
Incorrect contract address when adding native ETH

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud#1957]
Steps:
1. remove pair ETH/BTC
2. removecurrency ETH
3. addcurrency ETH Connext 18 0x0000000000000000000000000000000000000000
4. listcurrencies

Actual result:
Incorrect token address. As a result connext client cant get data for ETH from indra node.
```
ETH    │ 18     │ 0x0                                        │ Connext  
```
![Screenshot from 2020-10-22 15-50-54](https://user-images.githubusercontent.com/29906866/96875177-9c437200-147f-11eb-9b88-8c7650102bdc.png)

Expected result:
```
 ETH    │ 18     │ 0x0000000000000000000000000000000000000000 │ Connext
```

**Comment by kilrau** [comment]
Want to look into this? @rsercano
