### ISSUE TITLE
Classify peers as `offline`, long-dead peers as `dead`

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1970]
### Background

Currently logs of an "older" xud environment look like [this](https://paste.ubuntu.com/p/NhwB7FY9s5/) when starting/restarting xud. Busy for minutes with a decent load on the tor process trying to connect to *very* dead peers. It takes a while (in my case 6 minutes) until xud finally reconnected to its previous peers.

### Your environment

* version of `xud`: `1.2.0-d4587458`
* which operating system (`uname -a` on *Nix):
* version of `lndbtc`, `lndltc`, `connext` and others:
* any other relevant environment details:

### Steps to reproduce

Restart xud which has 100+ dead peers in the db.

### Expected behaviour

xud immediately connects to previosly connected peers, leaves classified *dead* peers reconnection attempts to the regular scheduled attempts at runtime, but **not** on startup.

### Actual behaviour

xud tries to connect to all peers on startup, leading to behavior described above.

**Comment by kilrau** [comment]
How this could work:
- a counter records *unsuccessful* connection retries per peer and classifies a peer as `offline` after 288 failed consecutive connection attempts (1 day), to `dead` after `1708` failed consecutive attempts (1 week).
- xud doesn't connect to `offline` peers in the first round of re-connection attempts on startup to avoid above described behavior
- xud will stop attempting to connect to `dead` peers altogether
- once a successful connection to (or from) a `offline`/`dead` peer is established the peers `offline`/`dead` status is erased

**Comment by LePremierHomme** [comment]
A more technical design proposal for the basic feature:

1. Add `numConnFailures` field to `Nodes` xud db table.
2. Add 2 fields to `PoolConfig`: `nodeOfflineThreshold` (default: 288), `nodeDeadThreshold` (default: 1708). (I might as well just start with plain constants in the code.)
3. Increment the node entry `numConnFailures` field on every distinct connection failure (**to any address**).  Reset the counter on a successful connection.
4. on xud launch, filter out nodes which their `numConnFailures` pass `nodeDeadThreshold`, and group the nodes where it passed `nodeOfflineThreshold` to initiate the connection after 5-10 (?) min. (If in the meanwhile the node connected to us, this connection attempt will fail. We can actively abort it instead, but i’m not sure it worth the code complexity.)

**Comment by erkarl** [comment]
> A more technical design proposal for the basic feature:
> 
>     1. Add `numConnFailures` field to `Nodes` xud db table.
> 
>     2. Add 2 fields to `PoolConfig`: `nodeOfflineThreshold` (default: 288), `nodeDeadThreshold` (default: 1708). (I might as well just start with plain constants in the code.)
> 
>     3. Increment the node entry `numConnFailures` field on every distinct connection failure (**to any address**).  Reset the counter on a successful connection.
> 
>     4. on xud launch, filter out nodes which their `numConnFailures` pass `nodeDeadThreshold`, and group the nodes where it passed `nodeOfflineThreshold` to initiate the connection after 5-10 (?) min. (If in the meanwhile the node connected to us, this connection attempt will fail. We can actively abort it instead, but i’m not sure it worth the code complexity.)

concept ACK

**Comment by kilrau** [comment]
> A more technical design proposal for the basic feature:
> 
>     1. Add `numConnFailures` field to `Nodes` xud db table.
> 
>     2. Add 2 fields to `PoolConfig`: `nodeOfflineThreshold` (default: 288), `nodeDeadThreshold` (default: 1708). (I might as well just start with plain constants in the code.)
> 
>     3. Increment the node entry `numConnFailures` field on every distinct connection failure (**to any address**).  Reset the counter on a successful connection.
> 
>     4. on xud launch, filter out nodes which their `numConnFailures` pass `nodeDeadThreshold`, and group the nodes where it passed `nodeOfflineThreshold` to initiate the connection after 5-10 (?) min. (If in the meanwhile the node connected to us, this connection attempt will fail. We can actively abort it instead, but i’m not sure it worth the code complexity.)

concept ACK

Regarding the last bullet point: let's not abort for now and see how it behaves, keep it simple

**Comment by sangaman** [comment]
> A more technical design proposal for the basic feature:
> 
>     1. Add `numConnFailures` field to `Nodes` xud db table.
> 
>     2. Add 2 fields to `PoolConfig`: `nodeOfflineThreshold` (default: 288), `nodeDeadThreshold` (default: 1708). (I might as well just start with plain constants in the code.)
> 
>     3. Increment the node entry `numConnFailures` field on every distinct connection failure (**to any address**).  Reset the counter on a successful connection.
> 
>     4. on xud launch, filter out nodes which their `numConnFailures` pass `nodeDeadThreshold`, and group the nodes where it passed `nodeOfflineThreshold` to initiate the connection after 5-10 (?) min. (If in the meanwhile the node connected to us, this connection attempt will fail. We can actively abort it instead, but i’m not sure it worth the code complexity.)

I'm introducing db migrations in #2007, that would be very handy for your first bullet point.

Maybe we should call the field `consecutiveConnFailures`? That seems to be more descriptive/accurate.

I also think we can make the config variables hardcoded, at least at first, I doubt we'll see too many people tinkering with that.

Otherwise, concept ACK.

**Comment by LePremierHomme** [comment]
> I'm introducing db migrations in #2007, that would be very handy for your first bullet point.

So should I work from your branch?

> Maybe we should call the field consecutiveConnFailures? That seems to be more descriptive/accurate.

 👍

> I also think we can make the config variables hardcoded, at least at first, I doubt we'll see too many people tinkering with that.

 👍

**Comment by kilrau** [comment]
> So should I work from your branch?

yep, that would make sense I think

**Comment by sangaman** [comment]
> > So should I work from your branch?
> 
> yep, that would make sense I think

You can do that or just cherry-pick the two relevant commits, and then later you can rebase once that PR is merged.
