### ISSUE TITLE
Extend P2P tests

### ISSUE THREAD

**Issue by michael1011** [ExchangeUnion/xud#200]
We already have P2P sanity tests (#132) but we should also test P2P functionality.

- initialize two `xud` instances and place a few `ownOrder` on both
- connect the `xud` instances to each other and make sure that the handshake was successful and the orders were exchanged
 - add another `ownOrder` to one `xud` and verify that the order gets transmitted to the other `xud`
-  test dropping of orders upon peer disconnection.

**Comment by itsbalamurali** [comment]
Todo once  #132 is merged along with #192

**Comment by kilrau** [comment]
- placeOrder (limit/market)
- cancel order

**Comment by kilrau** [comment]
Basically automate this: https://github.com/ExchangeUnion/xud/issues/191

**Comment by sangaman** [comment]
This was partly addressed by #355 with the `Pool` integration tests which test the handshake.
