### ISSUE TITLE
removeorder responce returns partial removal message instead of full 

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud#2020]
Steps:
1. place order
2. remove it

Actual result:
message says that order was removed partially and full amount of order displayed as remaining
![Screenshot from 2020-12-04 18-20-59](https://user-images.githubusercontent.com/29906866/101183967-342ca200-3661-11eb-8ad1-1d3ff7cd5803.png)

Expected result:
`Order fully removed`

Note:
Partial removing works fine (correct message and value)

**Comment by kilrau** [comment]
Is it "just" the message that is wrong or the matching itself?

**Comment by raladev** [comment]
> Is it "just" the message that is wrong or the matching itself?

just a message
