### ISSUE TITLE
placeorder checks remote balance instead of local for quote currency 

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud#2021]
Precondition:
1. User has local balance for BTC, but does not have remote.

Steps:
1. sell 0.1 LTC/BTC 0.1 1

Actual result:
Validation error
![Screenshot from 2020-12-04 18-37-40](https://user-images.githubusercontent.com/29906866/101185640-2d069380-3663-11eb-849d-e99e7a271f04.png)

Expected result:
successfully placed order

Note:
May be the result of https://github.com/ExchangeUnion/xud/pull/2006

**Comment by sangaman** [comment]
@raladev Can you show the output of `lndbtc-lncli channelbalance` or `lndbtc-lncli listchannels` ?

**Comment by raladev** [comment]
Closed, my mistake, i misused max buy instead of max sell.
Checking works correctly.
