### ISSUE TITLE
Ready status of connext client in getinfo response when connext client is unavalable

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud#2031]
### Steps to reproduce

1. bash xud.sh
2. docker rm -f simnet_connext_1
3. getinfo

### Actual behaviour

Ready status for connext
![Screenshot from 2020-12-08 16-03-20](https://user-images.githubusercontent.com/29906866/101491554-f12a4180-3974-11eb-90e4-7d2730e614a8.png)
![Screenshot from 2020-12-08 16-03-15](https://user-images.githubusercontent.com/29906866/101491557-f1c2d800-3974-11eb-88d2-6ccb3e7b451b.png)

### Expected behaviour

ECONNREFUSED error in status field

**Comment by kilrau** [comment]
This one should be fixed :)
