### ISSUE TITLE
Local order Ids still tracked after order is fully matched

### ISSUE THREAD

**Issue by sangaman** [ExchangeUnion/xud#2045]
Internally matched orders are removed from the trading pair queues but not from the global order book mapping between local order ids and global order ids. This is a memory leak and can also lead to some unexpected behavior, for example it's the underlying cause of #2030.

Related PR #1557.

**Comment by kilrau** [comment]
Not sure which priority this should get since this didn't cause any memory leak for me, probably because it's unlikely for internal (own order) matches to happen in practice.

**Comment by raladev** [comment]
duplecate of https://github.com/ExchangeUnion/xud/issues/1556

**Comment by sangaman** [comment]
> Not sure which priority this should get since this didn't cause any memory leak for me, probably because it's unlikely for internal (own order) matches to happen in practice.

The memory leak is there, but minor. You'd have to do tons of orders before it really started to cause issues.

> duplecate of #1556

Thanks yes this is the same underlying issue.
