### ISSUE TITLE
set order localId (currently generated separately) = globalId

### ISSUE THREAD

**Issue by moshababo** [ExchangeUnion/xud#223]
From a discussion at #175. @sangaman wrote:

> I'm also thinking now we might have a case where an exchange is letting XUD do all the matching and doesn't want to have to create and track their own Ids. Which makes me think maybe localId should be optional when placing an order. Maybe even tracking localIds at all can be something that's configurable? Also something that can be done in a separate PR, but I wanted to see what you thought.

**Comment by kilrau** [comment]
For now we can assume that the vast majority of exchanges will need to have their own localIDs. Something to be implemented in a much later stage. Moved to beta.

**Comment by sangaman** [comment]
In thinking about this more, maybe rather than generating a new UUID for `localId` when none is specified by the client, we just set `localId` equal to the global order id. I'm not thinking of any reason why they can't have the same value, and it would simplify things a bit. I can handle that in a PR and close this issue if that makes sense to you.

**Comment by kilrau** [comment]
localID=global ID in matching mode makes sense to me, a PR of this can close this issue  @sangaman @moshababo

**Comment by kilrau** [comment]
Something for you? @ImmanuelSegol

**Comment by kilrau** [comment]
`localId` is already optional, but momentarily got it's own UUID is generated. This issue is about setting it equal to the `globalId` UUID. Something for you? @erkarl

**Comment by erkarl** [comment]
@kilrau possibly - would be nice to clean this up sooner rather than later.

**Comment by kilrau** [comment]
go for it!

**Comment by sangaman** [comment]
I was actually just thinking about this last night and was going to change it today, I definitely think this would be nice to have and it should be easy to do. Please go ahead if you get a chance.
