### ISSUE TITLE
Add marketOrder to XUCLI

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#232]
Couldn't test this, if it's already working by setting price 0, pls add this into the TypeDoc as comment

**Comment by michael1011** [comment]
The parameter `price` is optional.  If you don't set it a market order will get created. 

I will document it more verbose.

**Comment by kilrau** [comment]
Ok pls do this and close here

**Comment by kilrau** [comment]
Actually a change: I would want `placeOrder` to require a '0' for a market order in CLI+gRPC for security reasons. Don't make this param optional.

**Comment by kilrau** [comment]
Moved to #249, current state is fine for preAlpha
