### ISSUE TITLE
Add market order local quantity check

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#241]
Proposed enhancement of https://github.com/ExchangeUnion/xud/pull/109

Proposal Summary:
Add check if overall quantity in local orderbook for given pair is sufficient to cover the market order, if not don't allow to issue order and return available quantity.

Details: TBD

**Comment by kilrau** [comment]
You are right and I just noticed that, let's keep XIPs for the bigger things. Renamed.

**Comment by sangaman** [comment]
Is this actually desirable? I feel like as a user I would expect xud to accept my order and fill it as best its can.

**Comment by kilrau** [comment]
> Is this actually desirable? I feel like as a user I would expect xud to accept my order and fill it as best its can.

Agree on this. Closed.
