### ISSUE TITLE
CLI Market Order / Limit Order clear distinction

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#249]
1. We would want `placeOrder` to require a '0' for a market order in CLI+gRPC for security reasons. Don't make this param optional. 
2. Change the documentation.

Opened a new issue, so you don't have to change https://github.com/ExchangeUnion/xud/pull/245 but rather open a separate PR for the next milestone.

**Comment by sangaman** [comment]
I don't think I agree with this, particularly for the gRPC layer. I think it's not very intuitive or convenient to require a 0 price be specified, in my mind this is just an internal convention we use within our code base.

On the gRPC layer there's no such thing as a required field. The default for an unspecified number is 0. I think we'd have to create a new call, which I'd probably prefer anyhow to requiring 0 to be specified.

What might be a good idea, and where I can imagine people making typos, is to change our cli commands. We can make `price` a required argument for `placeorder` (and perhaps rename it to `limitorder` or `placelimitorder` if that's not too long), and then we can add a new command called `marketorder` (or `placemarketorder` if we're ok with long commands). But I also don't see it being too common, particularly for exchanges, to be placing orders via the command line either.

**Comment by kilrau** [comment]
gRPC: alright, let's leave it out.
CLI: Exchanges won't use the CLI, but I'm confident we'll have some technically affine users running this on their own machines and since we won't have a UI for the foreseeable future - they'll use the CLI. @michael1011  proposed separate calls for market and limit order before I think, I'm also ok with the long commands actually; at least crystal clear. Other opinions? @michael1011 @moshababo @itsbalamurali

**Comment by michael1011** [comment]
I would leave the gRPC the way it is right now too.

For the CLI separate commands make sense. Although I would prefer to keep them as short as possible (`limitorder` or `placelimit`). 

Another option would be designing the command like this: `placeorder <order_type> <pair_id> <order_id> <quantity> [price]`

**Comment by michael1011** [comment]
:+1: for `limitorder` and `marketorder` then.

Should we just merge #245 and get to this later? I am asking because the milestone of this issue is `alpha`.
