### ISSUE TITLE
 error: Error: ENOENT: no such file or directory, open '/home/sky/.lnd/tls.cert'

### ISSUE THREAD

**Issue by yyy999** [ExchangeUnion/xud#27]
In running ./xud:

 error: Error: ENOENT: no such file or directory, open '/home/sky/.lnd/tls.cert'
How do I do it?

**Comment by sangaman** [comment]
See #20. This error is thrown when [lnd](https://github.com/lightningnetwork/lnd) is not installed, but it can be disabled for testing purposes. I'll leave this issue open until we have a more informative error message.

**Comment by yyy999** [comment]
Ok!
resolved!
