### ISSUE TITLE
add ./xucli to $PATH

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#270]
automatically add ./xucli to $PATH (or similar) and make it executable from anywhere in a `xud getinfo` manner

**Comment by michael1011** [comment]
When I want to add a NPM package to my path I simply install with `sudo npm install -g <package>`. If you agree on that this issue is closely related to #290.

**Comment by sangaman** [comment]
Closing this in favor of #290 and making note of it there.
