### ISSUE TITLE
Notify client about which orders to cancel on peer disconnection

### ISSUE THREAD

**Issue by moshababo** [ExchangeUnion/xud#282]
When the socket with a peer is closed, client need to know to invalidate all its orders. 
At the moment the client is listening to orders on `subscribePeerOrders`, which is also used for order invalidation. We can use it and invalidate each order separately, but it might create performance issues. Benefits: client won't need another listener, nor to write additional handling logic.

Otherwise, we can create a separate gRPC call, perhaps `subscribePeerDisconnections`, which the client will be required to listen to, and to implement order removal by peer id.  
This call could be used regardless to order invalidation.

**Comment by sangaman** [comment]
Notifying the client about peers connecting/dropping might be handy, but if we expect them to rely on a peer disconnected event to remove their orders it does expect the client to have to write their own logic for removing orders by peerId.

If they just subscribe to peer order events, they only have to worry about removing by order id. This does still expect the client to be able to easily and quickly remove orders by id, but this seems pretty straightforward and perhaps is something we should encourage in our documentation. It might be worth looking into being able to put a batch of peer order updates in a single event but i'm not sure it's necessary.

**Comment by kilrau** [comment]
Agree with @sangaman , on a closed socket event we should just stream to the client which orders to remove.

**Comment by sangaman** [comment]
@ImmanuelSegol I think we should maybe discuss again whether this is necessary in light of recent changes. I'd lean towards this being unnecessary - that it's fine for clients to just use `SubscribeRemovedOrders` which will notify them in streaming mode when orders are removed due to a peer disconnecting. @moshababo thoughts?

**Comment by moshababo** [comment]
@ImmanuelSegol Thanks for the initiative, but yes, I think this feature is unnecessary at the moment. We can revise this in the future.
