### ISSUE TITLE
add default values to --help

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#283]
Update the `./xud --help` command: add default values to each command

**Comment by sangaman** [comment]
What do you mean by this exactly? Like example values?

**Comment by kilrau** [comment]
No, the system default where it makes sense. E.g.
```bash
xucli --help
 --db.database       SQL database name                             [string] (Default: "xud")
  --db.port           Port for SQL database                             [number] (Default: 3306)
```

**Comment by sangaman** [comment]
This would be a bit tricky because behind the scenes there are actually no defaults for the command line `xud` executable for most of the arguments. The defaults are whatever is in the config file - or whatever is hardcoded into xud should a particular option not be specified in the config file. Specifying a default value in the `xud` file would actually override whatever's in the config file with default values.

`xucli` is different and all the default values should be specified in the `--help` for any particular command.

**Comment by kilrau** [comment]
My bad, I meant `./xud --help`, not `./xucli --help`.

>This would be a bit tricky because behind the scenes there are actually no defaults for the command line xud executable for most of the arguments. The defaults are whatever is in the config file - or whatever is hardcoded into xud should a particular option not be specified in the config file.

What I mean by defaults is hardcoded into xud. I think it's clear that an entry in `xud.conf` changes these. Don't you think it'll be handy to have them for all these?

```bash
~/xud/bin$ ./xud --help
Options:
  --help                 Show help                                     [boolean]
  --version              Show version number                           [boolean]
  --xudir, -x            Data directory for xud                         [string]
  --db.database          SQL database name                              [string]
  --db.host              Hostname for SQL database                      [string]
  --db.password          Password for SQL database                      [string]
  --db.port              Port for SQL database                          [number]
  --db.username          User for SQL database                          [string]
  --lndbtc.certpath      Path to the SSL certificate for lndBtc         [string]
  --lndbtc.disable       Disable lndBtc integration                    [boolean]
  --lndbtc.host          Host of the lndBtc gRPC interface              [string]
  --lndbtc.macaroonpath  Path of the admin macaroon for lndBtc          [string]
  --lndbtc.port          Port of the lndBtc gRPC interface              [number]
  --lndltc.certpath      Path to the SSL certificate for lndLtc         [string]
  --lndltc.disable       Disable lndLtc integration                    [boolean]
  --lndltc.host          Host of the lndLtc gRPC interface              [string]
  --lndltc.macaroonpath  Path of the admin macaroon for lndLtc          [string]
  --lndltc.port          Port of the lndLtc gRPC interface              [number]
  --p2p.addresses        String array of reachable addresses             [array]
  --p2p.listen           Listen for incoming peers                     [boolean]
  --p2p.port, -p         Port to listen for incoming peers              [number]
  --raiden.disable       Disable raiden integration                    [boolean]
  --raiden.port          Port for raiden REST service                   [number]
  --rpc.host             gRPC service host                              [string]
  --rpc.port, -r         gRPC service port                              [number]
  --webproxy.disable     Disable web proxy server                      [boolean]
  --webproxy.port        Port for web proxy server                      [number]
```

**Comment by kilrau** [comment]
If we print:
```
./xud --help
 --db.database       SQL database name                             [string] (Default: "xud")
  --db.port           Port for SQL database                             [number] (Default: 3306)
```

that would overwrite what I specified in `xud.conf` ? that doesn't make any sense.

**Comment by sangaman** [comment]
Yes, because the current approach is that command line args override the config file. If you pass `--p2p.port 9885` it will use that port regardless of what's in the config file. I believe this is consistent with bitcoind, lnd, etc... and also just makes sense to me because if you're going to bother specifying something in the command line you'd expect it to be used, I would think.

**Comment by michael1011** [comment]
Yeah I agree with @sangaman 

But there has to be a way to do this. What about parsing the config separately and the values in the config override just the default command line parameters?

**Comment by kilrau** [comment]
Yes yes Daniel that is understood and correct. What I'd want is

```
./xud --help
 --db.database       SQL database name                             [string] (Default: "xud")
  --db.port           Port for SQL database                             [number] (Default: 3306)
```

whereas `(Default: X)` represents the *hardcoded* value and doesn't care about anything specified in `xud.conf` or CLI args. That's what I understand as default and would be enough for now.

**Comment by kilrau** [comment]
Simple issue getting complicated...

> The command line tools themselves know nothing about what's the default in xud.

What I'm saying is they should know the hardcoded values of `xud` and print it on `--help`. If that's somehow hard to do then just close, it's simply a nice-to-have and not worth spending too much time coding or discussing :)

**Comment by sangaman** [comment]
Yes it's hard to do. I'd agree it would be nice but I don't think it's practical given the way our code is structured and the features of yargs.
