### ISSUE TITLE
fix `npm run db:init`

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#285]
- Seed nodes & test data into db `xud_test` on `db:init`, no additional commands (this is what this task is about), this works *mostly* on the current master but always ends in some errors. To be cleaned up.
- Seed nodes (only) into `xud` db on first run (done)

**Comment by kilrau** [comment]
when done, bring back https://github.com/ExchangeUnion/xud/pull/286

**Comment by kilrau** [comment]
https://github.com/ExchangeUnion/xud/pull/244#issuecomment-410887432

**Comment by sangaman** [comment]
Closed via #328.
