### ISSUE TITLE
RpcMethods.js getOrders() needs params

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#29]
https://github.com/ExchangeUnion/xud/blob/master/lib/rpc/RpcMethods.js

*getOrders()*

An exchange will only be interested in this method to display some orders in their order book UI. Thus they probably only want to get the best 10 buy and sell orders. I think we need a parameter like an integer for the number of buy and sells (ordered by best price from top to bottom starting with the furthest sell, to the best sell, then starting with the best buy to the furthest buy). 0 returns all.

**Comment by sangaman** [comment]
Number of orders to return is good, it should also take a `pair_id` parameter I'm thinking. I like 0 to indicate a return of all orders, maybe if nothing is passed in it should default to something, say 100 orders from each side of the book? I'll work on this soon, let me know if what I've said makes sense.

**Comment by kilrau** [comment]
default all pairs, default 100 buy and 100 sell also cool

**Comment by Chikel** [comment]
I can tackle this if you'd like.

**Comment by michael1011** [comment]
@Chikel I have already done this in #78

**Comment by moshababo** [comment]
solved by #78
