### ISSUE TITLE
pool.init is called before server is "ready"

### ISSUE THREAD

**Issue by offerm** [ExchangeUnion/xud#294]
Guys,

Can you please check this. 
Looks like pool.init() is called before the server is ready.  pool.init open the listen port and restore connections with peers based on the hosts table. If the server is not ready, some peers may send packets and get wrong responses.

Should init be called at the end of the setup?

**Comment by sangaman** [comment]
I think you are right. I think `pool.init()` should get an `await` and move below `await this.orderbook.init()` but still above where the grpc server is initialized. I just tried that and the server starts up normally, and it definitely makes sense that the orderbook should be initialized before we start connecting to peers - particularly given that GET_ORDERS and ORDERS are among the first packets that will be transmitted.

**Comment by sangaman** [comment]
If you want to open a PR for this feel free, otherwise let me know and I can handle it.

**Comment by offerm** [comment]
Please classify this as a bug for prealpha 2. 

will leave the PR for you

Offer
