### ISSUE TITLE
RPC tp P2P port kills XUD

### ISSUE THREAD

**Issue by offerm** [ExchangeUnion/xud#304]
I sent RPC command to the P2P port of XUD 

`./xucli -p 8885 getinfo`

XUD crashed with:

8/8/2018, 9:41:55 AM [P2P] debug: Received data (127.0.0.1:65512): 
/Users/admin/github/xud/dist/bootstrap.js:13
        throw err;
identity,gzip: SyntaxError: Unexpected token  in JSON at position 0
        ^

8/8/2018, 9:41:55 AM [P2P] Error: Peer was destroyed
warn    at Peer.close (/Users/admin/github/xud/dist/p2p/Peer.js:92:30)
: Unparsable peer message: : SyntaxError: Unexpected token  in JSON at position 0
    at Socket.socket.once (/Users/admin/github/xud/dist/p2p/Peer.js:284:22)
8/8/2018, 9:41:55 AM [P2P]     at Object.onceWrapper (events.js:273:13)
info    at Socket.emit (events.js:182:13)
: Socket closed (127.0.0.1:65512)
    at TCP._handle.close (net.js:599:12)
8/8/2018, 9:41:55 AM [P2P] warn: disconnected peer (127.0.0.1:65512) hostId is missing
Error: Peer was destroyed
    at Peer.close (/Users/admin/github/xud/dist/p2p/Peer.js:92:30)
    at Socket.socket.once (/Users/admin/github/xud/dist/p2p/Peer.js:284:22)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at TCP._handle.close (net.js:599:12)

Process finished with exit code 1

**Comment by sangaman** [comment]
@offerm why close this issue? It seems like something we'd want to handle properly.

**Comment by offerm** [comment]
@san duplicated with #303. I opened it by mistake.
