### ISSUE TITLE
P2P HOSTS response

### ISSUE THREAD

**Issue by offerm** [ExchangeUnion/xud#306]
When providing HOSTS response, include only 👍 

1. outbound active peers. 
2. inbound peers that provided listen port

Never include localhost or 127.0.0.1 nodes in the response (even if outbound).

@kilrau @sangaman  - please consider if we should include inbound peers since we can't really validate the listen port provided by the peer which may be wrong and may lead to connection errors.
My recommendation -  Don't include them for now.

**Comment by sangaman** [comment]
I think the goal should be to only share hosts who have advertised external IPs and listening ports, but we have a couple of things to take care of before we implement that.

**Comment by kilrau** [comment]
Hmm definitely only a temporary fix. Go for the temporary "no inbound hosts in hosts db" fix and do the proper version I started fleshing out here: https://github.com/ExchangeUnion/xud/issues/305 later or don't do anything for now (apart from https://github.com/ExchangeUnion/xud/issues/177) and fix it properly in alpha? What do you prefer? @moshababo @sangaman

**Comment by kilrau** [comment]
Closed in favor of https://github.com/ExchangeUnion/xud/issues/305
