### ISSUE TITLE
Change gRPC default IP range to 0.0.0.0

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#309]
`0.0.0.0:8886`, not `localhost:8886`

**Comment by kilrau** [comment]
True. A simple idea how we could save the exchange from editing the config file when xud is running on a different machine with a different (internal) IP?

**Comment by sangaman** [comment]
I think it will need to be specified in the config file. It can also be passed as a command arg, but config file seems more convenient unless it will change often.

**Comment by kilrau** [comment]
Listening on `0.0.0.0` is definitely not wise and I can't come up with a better way than config. Will add this to the documentation. -> Closed.
