### ISSUE TITLE
Add database update functions to gRPC and CLI

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#313]
add pair
remove pair
empty pairs
add currency
remove currency
empty currencies
add host
remove host
empty hosts
add bannedHost
remove bannedHost
empty bannedHosts

**Comment by sangaman** [comment]
Eh I don't think xud needs to be a db admin tool and have all these calls. I think we should only have calls that make sense for regular operation. `ban` might be a nice feature to have if we want to enable manual banning, and we've discussed elsewhere adding a flag to unban a node on manual connect.

For the pairs and currencies, I do think add/remove calls for both of those make sense.
