### ISSUE TITLE
Add instructions for exchanges

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#319]
Step by step guide:
- proto file generation for different languages

**Comment by sangaman** [comment]
Exchanges won't need to generate protobuf files necessarily. But it would be good to have a developer guide at some point with some examples.

**Comment by kilrau** [comment]
Yep, that's what I want to get out of @liujiafeng622 s feedback.

**Comment by kilrau** [comment]
Add final https://hackmd.io/s/HyjL17Lsm (regtest version @offerm ) to Wiki and make sure the pieces are linked properly
