### ISSUE TITLE
Docker Containers

### ISSUE THREAD

**Issue by moshababo** [ExchangeUnion/xud#32]
We need to set up a configurable docker container automation for all XUD service dependencies, in order to get a functioning dev environment without much hassle. 

To begin with, we need to it for the database dependency (MySQL).

Later, we'll want to add all other dependencies:
* LND
* Raiden
* Different blockchains clients

In addition, we might want to set up a container solution which includes XUD itself, for easy deployment in tests and in production.

**Comment by itsbalamurali** [comment]
I've started working on this, for now, to begin with:

1. Dockerizing XUD & XUCLI.
2. Setting up docker-compose.yml for automating entire dependencies.

**Comment by itsbalamurali** [comment]
Done as part of #58  in the future plan to add Raiden and streamline networking and storage between containers.
