### ISSUE TITLE
Updating orders in priority queues rather than adding & removing

### ISSUE THREAD

**Issue by sangaman** [ExchangeUnion/xud#325]
We currently remove an order to be partially filled from the matching queue, then add it back after changing the quantity. We should be able to do this without removing and adding the order, but simply updating the order that already is in the queue. This is strictly a performance benefit but one that I think should be pretty easy to handle. This issue is just to keep track of it.

**Comment by moshababo** [comment]
I mentioned that in #215, in the first message EDIT clause.

**Comment by sangaman** [comment]
Gotcha, I wasn't sure it was mentioned in any issue. You think it's helpful to have this separate, or close as a dupe?

**Comment by moshababo** [comment]
Better to close it.
