### ISSUE TITLE
Connect: Add port 443 (& 80) fallback

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#340]
Make `port` specification in `./xucli connect host port` *optional*
- if port is specified in connect command only try this specific port
- if no port is specified, try 8885, then 443, then 80.

Prerequisite/Related: https://github.com/ExchangeUnion/xud/issues/182

**Comment by kilrau** [comment]
Please let me know what you think @moshababo @sangaman @offerm @michael1011

**Comment by sangaman** [comment]
I was thinking the fallback would be for the listening, not for connecting. For connecting we should probably be using confirmed listening addresses from the peer we're connecting to, not trying to guess what port they're using.

**Comment by kilrau** [comment]
This is because I'd want to make the port in the `connect` command *optional*.

Reason again UX: I never specified a port when I used teamviewer to connect to another machine. Just a port.

>TeamViewer connects on port 5938, but also tunnels via ports 80 (HTTP) & 443 (SSL) if that is unavailable.

**Comment by sangaman** [comment]
Ok that should be fine.

**Comment by kilrau** [comment]
Thanks for all your opinions!

I have very strong feelings about this and wouldn't have suggested it if I hadn't spent a long time in a place with very restricted things you can do outside of port 80 & 443. So e.g. I was NOT able to run a reachable bitcoin full node there and had to tunnel my way out to be reachable since you simply a) can't open anything else on ISP (forced) routers and b) even if you can, traffic on non-80/443 ports is heavily disturbed or even completely blocked. In conclusion I don't think we can *always* rely on the role model `lnd` and `btcd`/`bitcoind` to be right and say "it's not common, so we shouldn't do it".

I hope we all agree that we want to make
- `xud` as easy to run and
- as censorship-resistant as possible

for me following the https://community.teamviewer.com/t5/Knowledge-Base/Which-ports-are-used-by-TeamViewer/ta-p/4139#toc-hId-649815939 logic is a way into this direction but definitely is only part of it. It goes far beyond with e.g. making packets on 443 indistinguishable from regular SSL packets...

So yes @offerm you are right, there are some more cases to catch like if there are already services running on 443/80 or xud was not run as root on linux, behind a NAT it still would need forwarding, but I couldn't find any convincing reason why it's entirely a bad idea to do this.

Since I don't want to push you into "an agreement" and it's not that important in our current stage, I moved this and related (moved 80/443 part of #182 into #345 ) into beta. Let's do the lightning style concatenated `PubKey@IP:Port` for now! 

@offerm @sangaman

**Comment by sangaman** [comment]
> If indeed a connection can be made via port 80 and 443 it means that a special setup was done (forwarding, etc). In such case, adding externalip=XXXX:443 should not be additional work to the one setting it up.

This is true, even without any changes on our part all it would take to use xud with 443/80 is a line in the config file, one that should be added to the config file in any case should somebody want to be reachable. If you put 443 in there, that's what will be advertised to peers and that's what they will try to connect to. It should also be what's in the connection string in getinfo (once we have that feature).

**Comment by kilrau** [comment]
Moved this to a much later milestone, not important in current stage
