### ISSUE TITLE
Check `banned`, `self` and others BEFORE connection

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#352]
As per https://github.com/ExchangeUnion/xud/pull/315#issuecomment-413402498 all these checks should be done on client side BEFORE connection is attempted.

**Comment by sangaman** [comment]
Self is done in #315, plus we check to make sure we're not already connected, so really only the banned logic needs work.

**Comment by kilrau** [comment]
@sangaman can be closed?

**Comment by sangaman** [comment]
Yes, I believe this is fixed by #592. Closing.
