### ISSUE TITLE
Store an external address if we successfully make an outgoing connection 

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#365]
Store an external address if we successfully make an outgoing connection even if the other peer doesn't advertise a listening address, add "notAdvertised" or similar in this case -> don't share this address with others

**Comment by sangaman** [comment]
One thought that occurred to me is that if we store the last connected address along with the other listening addresses, we'd be sharing that node and address to others. Maybe we should have a separate column in the table `lastAddress` or something that we don't share to others. We try that address first, if one exists, then if it that doesn't work we try to connect to their advertised addresses.

**Comment by kilrau** [comment]
Agree, we should take care that we don't share any non-advertised addresses with others, but don't you already do this check with `connectedPeer.addresses.length > 0)` in https://github.com/ExchangeUnion/xud/pull/393/files ? @sangaman

**Comment by kilrau** [comment]
Tag last successful address of a peer in separate issue: https://github.com/ExchangeUnion/xud/issues/442

**Comment by rsercano** [comment]
Sure, I want to check that do I need to know anything before I start @moshababo @sangaman ?

**Comment by moshababo** [comment]
Just take some time to go through our usage of `NodeList` / `PeerList` inside of `Pool`. If you have any questions, feel free to hassle.
