### ISSUE TITLE
P2P tests not passing on mac

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#369]

**Comment by offerm** [comment]
P2P Sanity Tests
8/21/2018, 7:35:04 PM [GLOBAL][1] info: config loaded
8/21/2018, 7:35:04 PM [GLOBAL][1] info: Local nodePubKey is 0275e367e0002d3decab02761158da4f593689df02adcd169961cfe015966bc292
8/21/2018, 7:35:04 PM [GLOBAL][2] info: config loaded
8/21/2018, 7:35:04 PM [GLOBAL][2] info: Local nodePubKey is 02aa88fe1e63adca0bc5584b71ce1c99e414572a7cadc301b1c9e98b4966f62537
Executing (default): SELECT 1+1 AS result
Executing (default): SELECT 1+1 AS result
8/21/2018, 7:35:04 PM [DB][1] info: connected to database. host:localhost port:3306 database:xud_test
8/21/2018, 7:35:04 PM [DB][1] verbose: Executing (default): CREATE TABLE IF NOT EXISTS `nodes` (`id` INTEGER auto_increment , `nodePubKey` VARCHAR(255) NOT NULL UNIQUE, `addressesText` TEXT NOT NULL, `banned` TINYINT(1), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;
8/21/2018, 7:35:04 PM [DB][2] info: connected to database. host:localhost port:3306 database:xud_test
8/21/2018, 7:35:04 PM [DB][1] verbose: Executing (default): CREATE TABLE IF NOT EXISTS `currencies` (`id` VARCHAR(255) , `tokenAddress` VARCHAR(255), PRIMARY KEY (`id`)) ENGINE=InnoDB;
8/21/2018, 7:35:04 PM [DB][2] verbose: Executing (default): CREATE TABLE IF NOT EXISTS `nodes` (`id` INTEGER auto_increment , `nodePubKey` VARCHAR(255) NOT NULL UNIQUE, `addressesText` TEXT NOT NULL, `banned` TINYINT(1), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;
8/21/2018, 7:35:04 PM [DB][1] verbose: Executing (default): SHOW INDEX FROM `nodes`
8/21/2018, 7:35:04 PM [DB][2] verbose: Executing (default): CREATE TABLE IF NOT EXISTS `currencies` (`id` VARCHAR(255) , `tokenAddress` VARCHAR(255), PRIMARY KEY (`id`)) ENGINE=InnoDB;
8/21/2018, 7:35:04 PM [DB][2] verbose: Executing (default): SHOW INDEX FROM `nodes`
8/21/2018, 7:35:04 PM [DB][1] verbose: Executing (default): SHOW INDEX FROM `currencies`
8/21/2018, 7:35:04 PM [DB][2] verbose: Executing (default): SHOW INDEX FROM `currencies`
8/21/2018, 7:35:04 PM [DB][1] verbose: Executing (default): CREATE TABLE IF NOT EXISTS `pairs` (`id` VARCHAR(255) , `baseCurrency` VARCHAR(255) NOT NULL, `quoteCurrency` VARCHAR(255) NOT NULL, `swapProtocol` ENUM('LND', 'RAIDEN') NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`baseCurrency`) REFERENCES `currencies` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, FOREIGN KEY (`quoteCurrency`) REFERENCES `currencies` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE) ENGINE=InnoDB;
8/21/2018, 7:35:04 PM [DB][2] verbose: Executing (default): CREATE TABLE IF NOT EXISTS `pairs` (`id` VARCHAR(255) , `baseCurrency` VARCHAR(255) NOT NULL, `quoteCurrency` VARCHAR(255) NOT NULL, `swapProtocol` ENUM('LND', 'RAIDEN') NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`baseCurrency`) REFERENCES `currencies` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, FOREIGN KEY (`quoteCurrency`) REFERENCES `currencies` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE) ENGINE=InnoDB;
8/21/2018, 7:35:04 PM [DB][1] verbose: Executing (default): SHOW INDEX FROM `pairs`
8/21/2018, 7:35:04 PM [DB][2] verbose: Executing (default): SHOW INDEX FROM `pairs`
Executing (default): SELECT `id`, `baseCurrency`, `quoteCurrency`, `swapProtocol` FROM `pairs` AS `Pair`;
Executing (default): SELECT `id`, `baseCurrency`, `quoteCurrency`, `swapProtocol` FROM `pairs` AS `Pair`;
8/21/2018, 7:35:04 PM [P2P][1] info: retrieved external IP: 84.111.139.147
8/21/2018, 7:35:04 PM [P2P][1] info: Connecting to known / previously connected peers
Executing (default): SELECT `id`, `nodePubKey`, `addressesText`, `banned`, `createdAt`, `updatedAt` FROM `nodes` AS `Node`;
8/21/2018, 7:35:04 PM [P2P][2] info: retrieved external IP: 84.111.139.147
8/21/2018, 7:35:04 PM [P2P][2] info: Connecting to known / previously connected peers
Executing (default): SELECT `id`, `nodePubKey`, `addressesText`, `banned`, `createdAt`, `updatedAt` FROM `nodes` AS `Node`;
8/21/2018, 7:35:04 PM [P2P][1] info: p2p server listening on 0.0.0.0:9001
8/21/2018, 7:35:04 PM [GLOBAL][1] warn: RPC server is disabled.
8/21/2018, 7:35:04 PM [P2P][2] info: p2p server listening on 0.0.0.0:9002
8/21/2018, 7:35:04 PM [GLOBAL][2] warn: RPC server is disabled.
8/21/2018, 7:35:04 PM [P2P][1] debug: Connected pre-handshake to peer localhost:9002
8/21/2018, 7:35:04 PM [P2P][1] debug: Received data (localhost:9002): 
8/21/2018, 7:35:04 PM [P2P][1] info: Socket closed prior to handshake (localhost:9002)
8/21/2018, 7:35:04 PM [P2P][1] warn: error while opening connection to peer 02aa88fe1e63adca0bc5584b71ce1c99e414572a7cadc301b1c9e98b4966f62537: Peer was destroyed
    1) should connect successfully
    ✓ should fail connecting to the same node
8/21/2018, 7:35:04 PM [P2P][1] debug: Connected pre-handshake to peer localhost:9002
    2) should disconnect successfully
8/21/2018, 7:35:04 PM [P2P][1] debug: Received data (localhost:9002): 
8/21/2018, 7:35:04 PM [P2P][1] info: Socket closed prior to handshake (localhost:9002)
8/21/2018, 7:35:04 PM [P2P][1] warn: error while opening connection to peer 02aa88fe1e63adca0bc5584b71ce1c99e414572a7cadc301b1c9e98b4966f62537: Peer was destroyed
{ [AssertionError: expected promise to be rejected with an error including 'already connected' but it was fulfilled with 'Not connected']
  message:
   'expected promise to be rejected with an error including \'already connected\' but it was fulfilled with \'Not connected\'',
  showDiff: true,
  actual: 'Not connected',
  expected: 'already connected' }
8/21/2018, 7:35:04 PM [P2P][1] debug: Connected pre-handshake to peer localhost:9002
8/21/2018, 7:35:04 PM [P2P][1] debug: Received data (localhost:9002): 
8/21/2018, 7:35:04 PM [P2P][1] info: Socket closed prior to handshake (localhost:9002)
8/21/2018, 7:35:04 PM [P2P][1] warn: error while opening connection to peer thewrongpubkey: Peer was destroyed
    ✓ should fail when connecting to an unexpected node pub key
8/21/2018, 7:35:04 PM [P2P][1] warn: Cannot attempt connection to self
    ✓ should fail when connecting to self
8/21/2018, 7:35:04 PM [P2P][1] warn: error while opening connection to peer notarealnodepubkey: connect ECONNREFUSED 127.0.0.1:9003
    ✓ should fail connecting to a non-existing node
Executing (default): TRUNCATE `nodes`
8/21/2018, 7:35:04 PM [GLOBAL][1] info: XUD shutdown gracefully
8/21/2018, 7:35:04 PM [GLOBAL][2] info: XUD shutdown gracefully


  4 passing (695ms)
  2 failing

  1) P2P Sanity Tests
       should connect successfully:

      AssertionError: expected 'Not connected' to equal 'Connected to peer 02aa88fe1e63adca0bc5584b71ce1c99e414572a7cadc301b1c9e98b4966f62537'
      + expected - actual

      -Not connected
      +Connected to peer 02aa88fe1e63adca0bc5584b71ce1c99e414572a7cadc301b1c9e98b4966f62537
      
      at Object.<anonymous> (test/p2p/sanity.spec.ts:48:26)
      at Generator.next (<anonymous>)
      at fulfilled (test/p2p/sanity.spec.ts:4:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  2) P2P Sanity Tests
       should disconnect successfully:
     Node (02aa88fe1e63adca0bc5584b71ce1c99e414572a7cadc301b1c9e98b4966f62537) is not connected

**Comment by sangaman** [comment]
`8/21/2018, 7:35:04 PM [P2P][1] warn: error while opening connection to peer 02aa88fe1e63adca0bc5584b71ce1c99e414572a7cadc301b1c9e98b4966f62537: Peer was destroyed`

@offerm It looks like the two instances on the same machine are unable to connect with each other. Have you every tried doing this manually? I wonder if it is some sort of firewall issue. I'd be curious if you could spin up separate instances on separate processes listening for p2p connections on ports 9001 and 9002 and try to connect the node on 9001 to the node on 9002, that's essentially what's being attempted here.

**Comment by offerm** [comment]
Yes, two instances on the same machine have no problem.

The problem here can be seen in this line:
`8/21/2018, 7:35:04 PM [P2P][1] debug: Received data (localhost:9002):`
The message to xud2 handled by xud1.

My guess is that this is a grpc problem and that the test should change to run the xuds as separate OS processes and not as objects in the same process.

**Comment by sangaman** [comment]
I don't think it's a grpc problem because the grpc servers are disabled for these tests. You can see `8/21/2018, 7:35:04 PM [GLOBAL][2] warn: RPC server is disabled` in the output for example. There shouldn't be any communication over grpc for these tests.

I'm still not sure what the problem is. Could you try deleting your test db, deleting the stored node keys from disk (or move them temporarily) and retrying?

The log output you copied means that peer 1 received data from peer 2, not completely unexpected.

**Comment by offerm** [comment]
Agree. Nothing to do with RPC. My mistake. I said RPC and I meant socket. 

Deleted all databases, took the latest code from the master, deleted all nodekeys and I still see these failures.  Anyone with mac can confirm?

**Comment by moshababo** [comment]
Just checking

**Comment by moshababo** [comment]
@offerm I don't see this problem on my mac.

**Comment by offerm** [comment]
This is still open

**Comment by moshababo** [comment]
I didn't manage to reproduce it, and since it's passing on travis, I don't think I should dig too much into it.

The log line you pointed (`8/21/2018, 7:35:04 PM [P2P][1] debug: Received data (localhost:9002):
`) might suggest that something wasn't working properly, but i'm not sure if it's related to your env or not. 

In regards to running these tests in a multi-process mode - that indeed should be the next stage in the p2p testing. It requires some infrastructure work first.

**Comment by offerm** [comment]
@moshababo which version of node are you using. I'm at 10.8.0.

**Comment by kilrau** [comment]
waiting for @offerm to close this

**Comment by offerm** [comment]
I confirm working!
