### ISSUE TITLE
Share peers

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#386]
- Share currently connected peers only, not entire 'nodes' table
- Connect to newly received peers dynamically at run time (after receiving nodes via `GET_NODES`)

**Comment by sangaman** [comment]
I can take care of the first bullet point. The second bullet point is mistaken, we do connect to newly received nodes when received not only on startup. For the third point, you mean gossiping to all our peers every time we connect to a new peer? I think that would get very noisy. Rather, we've discussed having the ability to query peers to send their known nodes.

**Comment by sangaman** [comment]
I think better than a query interval may be a way to manually trigger it, like through an rpc call. Maybe let's open another issue for that to discuss because I think it's not exactly related to the first point.

**Comment by kilrau** [comment]
EDIT: moved 3rd bullet point into: https://github.com/ExchangeUnion/xud/issues/402
