### ISSUE TITLE
Create node key

### ISSUE THREAD

**Issue by sangaman** [ExchangeUnion/xud#39]
Use the https://www.npmjs.com/package/secp256k1 to create and save a key pair to uniquely identify an xud node and to sign/verify messages and orders. Look into how this key can be saved to disk in encrypted format.

**Comment by moshababo** [comment]
What's the common practice of saving private keys as a part of the application data? 
Why plain disk file and not the database?
And if it's encrypted, where will you save the encryption key?

**Comment by sangaman** [comment]
I'm most familiar with keys and other sensitive data being encrypted and saved to disk. Database is an option, but it's not something we'll be needing to query on any regular basis. I'm thinking it is decrypted on start and then kept in memory as long as xud is running. The encryption key wouldn't be saved, just remembered like a password.

**Comment by kilrau** [comment]
Agree with Daniel's answer.

**Comment by moshababo** [comment]
If it's not handled automatically then, what you describe means that each `xud` launch will require a password input, if the user have one, and if he don't then he'll create one and will get a new pubKey?

**Comment by sangaman** [comment]
Yeah, I think launching on the first run would generate a new key and prompt the user to provide an optional encryption password. If the user provides a password, they'd need to enter it each time xud is started.

**Comment by kilrau** [comment]
Close? @sangaman

**Comment by sangaman** [comment]
I'll close when the encryption is merged.

**Comment by kilrau** [comment]
Encryption part moved to Alpha: https://github.com/ExchangeUnion/xud/issues/184
