### ISSUE TITLE
Track pending outgoing connections to peers

### ISSUE THREAD

**Issue by sangaman** [ExchangeUnion/xud#398]
Right now, on startup it's common to get a flood of `NODES` packets all at once which have a lot of overlap, which then results in multiple outgoing connection attempts to those nodes. There's no mechanism currently to check if we're attempting to connect to a given node. For this issue I suggest that we track a `pendingPeers` Map in Pool which maps peer's node pub keys to the unopened `Peer` object. When the peer connection either succeeds and the open event is fired, or fails and the close event is fired, we remove the peer from `pendingPeers` and add to `peers` if successful.

**Comment by moshababo** [comment]
So you're suggesting to ignore nodes which their pubkey is already listed on `pendingPeers`?

**Comment by sangaman** [comment]
Exactly.

**Comment by moshababo** [comment]
Sounds good to me. If we'll want to support parallelism (specially due to connection retries, which can take ages), we'll need to introduce `address` in addition or instead of `pubKey`.

**Comment by kilrau** [comment]
Introducing `pendingPeers` will ensure we only try to connect to a given `pubKey` once throughout the whole lifetime, right (not only on startup...)? @sangaman 

If yes, that's what we need!

**Comment by sangaman** [comment]
Yeah, well we already have checks in place to not attempt a connection to a peer we're already connected to. This will check to make sure we're not attempting a connection a peer we're already *attempting* to connect to.

**Comment by kilrau** [comment]
Ok thx. As per `pendingPeers` contains `pubKey`@`IP`:`port`, otherwise

**Comment by sangaman** [comment]
I think just nodepubkey would be enough actually, since all outgoing connections reference a peer nodepubkey, we just check if we have a pending peer for the given nodepubkey.

**Comment by sangaman** [comment]
Yeah that's true. But I'm pretty sure I prefer the serial approach, otherwise I think we'd see this same burst of failing connection attempts should anyone have a lot of listening addresses configured.

**Comment by robertsdotpm** [comment]
I'll take this issue

**Comment by sangaman** [comment]
That would be great, I haven't started any work on it yet. Let me know if you have any questions at all.
