### ISSUE TITLE
P2P Improvements Overview

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#401]
This issue is to track P2P improvements which we want to have done in `alpha.2`:

* Switch off P2P functionality by default https://github.com/ExchangeUnion/xud/issues/434
* Permanently disconnect from a node https://github.com/ExchangeUnion/xud/issues/336
* Try to connect to each node only ONCE https://github.com/ExchangeUnion/xud/issues/398
* Learn about new nodes at runtime https://github.com/ExchangeUnion/xud/issues/262
* Store successful connected peers, even though no listening address advertised https://github.com/ExchangeUnion/xud/issues/365
* Tag last successful address of a peer https://github.com/ExchangeUnion/xud/issues/442
* Enhance shared peer info https://github.com/ExchangeUnion/xud/issues/403
* GET_NODES periodically https://github.com/ExchangeUnion/xud/issues/402
* Check `banned` before connection attempt https://github.com/ExchangeUnion/xud/issues/352
* Peer/Node data structures https://github.com/ExchangeUnion/xud/issues/185
* Advertise version https://github.com/ExchangeUnion/xud/issues/154

**Comment by moshababo** [comment]
Open issues:
* Advertise version #154: we're waiting with it for later stage.
* Reconnect to last successful address of a peer first #402: let's continue the discussion.

**Comment by sangaman** [comment]
We should already have logic to reconnect to the last successful address of a peer per #496.

**Comment by kilrau** [comment]
#154 -> `alpha.3`
#402 -> `alpha.4` (reconnect to last successful address is not part of it as @sangaman pointed out)

**Comment by moshababo** [comment]
Yes, I fixed the title.

**Comment by kilrau** [comment]
Only #154 & #402 are left, won't need this overview issue anymore. Closing.
