### ISSUE TITLE
[Concept] Safety net for market orders

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#405]
Safety limit: convert market into multiple limit orders with retries up to a max % from mid market price at time of order issuance

**Comment by kilrau** [comment]
> I'm not sure I follow exactly

Takes the mid market price at the moment of order issuance (saves it in `midmarketprice`), then creates limit orders based on this to fill currently available orders per orderbook. Checks that prices of these don't exceed +- X% from `midmarketprice`. If some of the limit orders fail, retries limit orders based on order book at this time, again checks that don't exceed +- X% from `midmarketprice`. Keeps running until all filled.

> Is this in use on exchanges?
Not that I'm aware of.

**Comment by sangaman** [comment]
I'd be hesitant to do this, it seems fairly complex (particularly in splitting a market order into limit orders) and I'm not sure we want to fiddle with the concept of a market order, particularly when interfacing with exchanges that do use regular market orders. Maybe there are some other safety checks we could consider, but ultimately my feeling is that this responsibility falls on the users and especially exchanges. Even if we have a feature like this, it's still  possible to put in the wrong quantity, wrong price on a limit order, etc... For exchanges, they can apply the same checks they use internally on the orders they submit to XU.

**Comment by kilrau** [comment]
Complex, I agree and definitely not a focus (that's why 1.0.0). This feature is not meant for exchanges, but for individuals trading via `xud`. I would want to leave it open to revisit later.

**Comment by reliveyy** [comment]
I think we could leave this order splitting logic implementation to the API user. And I suggest we should not use market order in this case to make the market order conceptually the same as [the original definition](https://www.investopedia.com/terms/m/marketorder.asp). 

And for some market order variants we should use other order types to distinguish with the original market like the stop order, iceberg order and etc. IMO complex order could be dismantled as basic orders + event hooks and expose those functionalities as core module API.

**Comment by kilrau** [comment]
Alright. Everybody ok to close this?
