### ISSUE TITLE
Create database

### ISSUE THREAD

**Issue by moshababo** [ExchangeUnion/xud#41]
When authenticating through `sequelize` to the database server by specifying a specific database which does not exists, an exception is thrown. 

A possible solution would be to try to connect by specifying a specific database anyway, and if exception is thrown, reconnect without specifying one. Create the database with a raw query, and then either reconnect to the server or just define a new database context (should work in theory).

Other solution would be to always connect without specifying a specific database, create it if it does not exists, and then define the database context. If the database context trick doesn't work, and reconnecting is needed, then it's not a good solution.

**Comment by itsbalamurali** [comment]
Would be closed as part of #36

**Comment by itsbalamurali** [comment]
Closing this issue as this is done and merged as part of #58
