### ISSUE TITLE
Swap: failures & other exceptions

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#413]
Successful swaps are covered in https://github.com/ExchangeUnion/xud/issues/422, this issue is about implementing swap failure events (https://github.com/ExchangeUnion/xud/pull/380 prepared events for this).

* `cancelSwap` packet, which can be sent by maker or taker any time during the 3s interval to 
cancel the swap as a bilateral agreement. -> remove peer order, continue matching
* swap time-out (3s from DEAL_RESPONSE to Pre-image release) -> remove peer order, dummy penalize event and continue matching
* order invalidated -> remove peer order, dummy penalize event and continue matching
* check if rate of incoming HTLC matches DEAL rate, if not cancel swap and try next
* generic error -> ?

**Comment by sangaman** [comment]
This is partly addressed by #380. After that is merged. After that is merged I'll put in more handling around failed (and completed) swaps.

**Comment by kilrau** [comment]
this needs to be completed for https://github.com/ExchangeUnion/xud/issues/161
