### ISSUE TITLE
P2P Bootstraping

### ISSUE THREAD

**Issue by moshababo** [ExchangeUnion/xud#42]
We need to fully define and our peer discovery methods, which are the most appropriate for our kind of P2P network and application, and the fallback hierarchy.

Ideas can be taken from [libp2p](https://github.com/libp2p/js-libp2p/tree/master/examples/discovery-mechanisms) and [bitcoind](https://en.bitcoin.it/wiki/Satoshi_Client_Node_Discovery).

**Comment by kilrau** [comment]
@itsbalamurali Please come up with a detailed proposal and we do another iteration.

**Comment by sangaman** [comment]
A few ideas:

- One or more hardcoded or configurable seed nodes that share the IP addresses of known xu nodes. This is what bitcoin does. I figure Exchange Union can operate a seed node.
- Once connected, peers share information about other known peers.
- In the case of public exchanges, we might want some way to verify a particular node key and/or IP address belongs to an exchange. This might be tied to seed nodes, or perhaps some directory or standardized way for exchanges to verify their identity.

**Comment by kilrau** [comment]
Assigned to @itsbalamurali

**Comment by moshababo** [comment]
This issue was split to different ones.
