### ISSUE TITLE
SWAP: protocol improvements

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#421]
1. Eliminate ` SWAP_REQUEST` packet: taker creates the preimage and hash and initiates the swap
2. Eliminate `SWAP_RESPONSE` by adding a function to lnd to stream / be queried for preimage. So the maker's `xud` can forward the preimage from one `xud` to the other without waiting for the taker to send it over the wire --> check required changes

Summary: in order to support partial matches we decided to go for:

> Swap protocol V2
> Swap version 2 reduces the need for swapRequest message from the taker to the maker and allows the actual swap to start sooner. To do that the following changes take place:
> 
> The r_hash and the r_preImage are set by the taker and not by the maker.
> The taker sends to the maker aswapRequest message which includes the r_hash.
> The maker confirms with swapResponse message
> The taker initiates the swap
> upon success the taker issue a swapResponse message (to be renamed to swapConmpleted) to the maker.
> Impact on Deal Status
> swapRequested status is not needed
> amountSent - set when sending amounts with sendPaymentSync. Prior status dealAgreed when maker and dealRequested when taker
> swapDone - set by taker when getting a response from sendPaymentSync which includes the preImage. Prior status should be preImagerevealed. Set by maker when getting from maker the swapResponse message with the preImage.

**Comment by offerm** [comment]
@kilrau @sangaman hold horses on this. We are not done yet with the swap. Remember that we did the happy flow.

We still need to deal with expiry calculation of the HTLCs. For this we may need to share some information in the P2P packets (like the route and how many hopes are in route). This may also impact the decision if the maker should start the swap or the taker.

**Comment by kilrau** [comment]
Why moved to beta? @offerm This is a bit far away. Please consult with @sangaman and me next time.

**Comment by offerm** [comment]
@kilrau see https://hackmd.io/s/SJ2qZUzdX

This is also relevant to 
#161 - when should we consider the swap as done
#413 
#407 
#421

Waiting for a green light to move.

**Comment by sangaman** [comment]
I shared some questions/concerns on gitter, we can move the discussion to here if you'd rather and I'll copy over my comments.

**Comment by kilrau** [comment]
Messages: `SwapRequest`, `SwapResponse`, `SwapError`, and `SwapComplete`

**Comment by kilrau** [comment]
> #161 - when should we consider the swap as done

For now I'd say once `swapConmpleted`, but we definitely need to get rid of it. Maker could just not send it and then it will mess up our status'. How much adjustment to LND needed to push a preimage to an external source? @offerm

**Comment by kilrau** [comment]
Basic question to make sure my understanding is right: at the moment there is no way for `XUD_B` to get the preimage from `LND_B` once it was revealed by `LND_A`, correct? @offerm @sangaman

**Comment by sangaman** [comment]
There is, it's in the `sendPaymentSync` response. It's just not currently configured to save that value (it only logs it), but it should be pretty easy to have the `swap.completed` event fire when `sendPaymentSync` succeeds for XUD_B, or when XUD_A reveals the preimage on the other side of things.

**Comment by offerm** [comment]
Yep

**Comment by offerm** [comment]
Can this be closed?

**Comment by kilrau** [comment]
How about @offerm 

> What was not implemented in this PR (@kilrau ):
> 
> emit of swap.accepted - this has to do with orderbook integration on the maker side. Looks like integration should be done before the swap is accepted.
> emit swap.rejected - currently, the maker has no execution path that leads to rejection. To be implemented with some TODOs
> quantity/proposedQuantity - This also has to do with orderBook integration. TBD
> handling timeouts/peer disconnection.
