### ISSUE TITLE
Fix LND PR

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#440]
- https://github.com/ExchangeUnion/xud/issues/430
- remove protobuf dependency - add to rpc.proto file in lnd
https://github.com/lightningnetwork/lnd/pull/1820#discussion_r214472772
- commit & follow-up fixes

**Comment by offerm** [comment]
Done by an update to resolver PR (LND).

OK to close? @kilrau

**Comment by kilrau** [comment]
Yep
