### ISSUE TITLE
Querying peers for orders of specific pairs

### ISSUE THREAD

**Issue by sangaman** [ExchangeUnion/xud#454]
We want to be able to specify a pair id in the `GET_ORDERS` packet to query only orders for that specific pair. This will be useful if, for instance, we add a new trading pair while xud is running.

Edit: A followup issue, although one that could possibly be addressed at the same time as this one, is sending this specified `GET_ORDERS` packet to peers that support the pair when a new pair is added.

**Comment by rsercano** [comment]
I would like to check this as soon as #496 is merged, I liked the "good first issue" labels btw. :)

**Comment by sangaman** [comment]
Great, feel free to start working on it whenever. And yeah, I tried to label the relatively simple issues as "good first issues" - unfortunately I didn't come with too many. We've done a good job tracking the core pieces of functionality in issues but those are also usually the most challenging ones, still a lot of small improvements to make as well I'm sure. I'll try to keep in mind making and labeling issues that are not too complicated.
