### ISSUE TITLE
Track node reputation events & score

### ISSUE THREAD

**Issue by sangaman** [ExchangeUnion/xud#457]
Offshoot of #185. We want to track node behavior scores for reputation and banning purposes.

- Track reputation events and record each instance of a negative event, including the type of event and time of occurrence.
- Track positive reputation events as well - at this point I'm thinking this would consist of successfully completed swaps/trades, maybe we could also award points for sustained uptime with low pings or something along those lines. I think it would be excessive to record every swap strictly for reputation purposes, although maybe if we track each successful swap/trade for historical/info purposes we could simply use that same data for calculating reputation.
- Have hardcoded (or maybe configurable) scores assigned to each event.
- On startup, load the reputation events for each unbanned node and calculate a score. For example, if timing out on a packet request is -10 points, and completed swaps are each +1 point, a peer with 2 timeouts and 5 swaps would have a score of -15 points.
- If a peer's score falls below a certain threshold, we ban the peer and notify the peer of the negative events that caused us to ban them.
- We can also use this score to determine which nodes get shared in response to a `GET_NODES` request.
- We might want to set a "statute of limitations" for reputation events as well. We can periodically purge events older than a certain date (maybe ~1 month), this would have scores based more on recent than historical behavior and also prevent db bloat.

**Comment by kilrau** [comment]
Dependency: https://github.com/ExchangeUnion/xud/issues/336

**Comment by michael1011** [comment]
Closed by #470
