### ISSUE TITLE
Trading Test Environment v2

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#472]
Continuation of [v1](https://github.com/ExchangeUnion/xud/issues/191):
* 3 VMs: xud1,2,3 all LND enabled (BTC/LTC), raiden disabled
* 1 separate VM: running one SIMNET BTCD and one SIMNET LTCD. BTCD serves all BTC-LNDs, LTCD serves all LTC-LNDs of xud1,2,3. There should be a script that mines a new block every 5 seconds.
* public "requestChannel(LND URI, currency, amount)" method to call at xud1,2,3, (it's a separate script, not part of XUD) which triggers xud1,2,3 to open a channel back to me. Advanced: Automatically open an outgoing channel on the second currency with max capacity. We might only open this for whitelisted `xud` pubkeys to avoid abuse.
* continous deployment: xud1,2,3 get updated automatically on latest master: idea -> dockerhub -> kubernetes pull new image, check kubernetes scripts in /test
* trading bot as a market maker for testing, so I'd say: todays rate, place 10 buy and 10 sell limit orders .0001, quantity 0.01 from each other BTC & LTC. When they are filled, replace them - keep it simple for now.

**Comment by kilrau** [comment]
> Do you see any issue with this setup?

Not at all, sound great!, Updated description

**Comment by kilrau** [comment]
Closed this one https://github.com/ExchangeUnion/xud/issues/508, you wanna take over? @offerm

**Comment by kilrau** [comment]
@michael1011  and me will work on https://github.com/ExchangeUnion/xud/issues/191 first, can you help us with this one after? @offerm

**Comment by offerm** [comment]
Update 
Continuation of v1:

> 3 VMs: xud1,2,3 all LND enabled (BTC/LTC), raiden disabled

done

> 1 separate VM: running one SIMNET BTCD and one SIMNET LTCD. BTCD serves all BTC-LNDs, LTCD serves all LTC-LNDs of xud1,2,3. There should be a script that mines a new block every 5 seconds.

done

> public "requestChannel(LND URI, currency, amount)" method to call at xud1,2,3, (it's a separate script, not part of XUD) which triggers xud1,2,3 to open a channel back to me. Advanced: Automatically open an outgoing channel on the second currency with max capacity. We might only open this for whitelisted xud pubkeys to avoid abuse.

in the making by @michael1011 

> continous deployment: xud1,2,3 get updated automatically on latest master: idea -> dockerhub -> kubernetes pull new image, check kubernetes scripts in /test @itsbalamurali 

Working on it
