### ISSUE TITLE
DeprecationWarning on startup and CLI usage

### ISSUE THREAD

**Issue by offerm** [ExchangeUnion/xud#475]
Do we know what the reason for this is?

>(node:55458) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

Complicated fix?

**Comment by offerm** [comment]
@sangaman 
Why close it? 
Even if we don't handle now we should leave it open so we will remember it.
I also think it is a nice issue for any new team member to deal with.

Reopen. 
@kilrau please decide when this should be done.  Not sure exchanges will be happy with this `security warning`....

**Comment by michael1011** [comment]
We should just deal with this if we want to support Node.js v10 right now or in the near future. And I think we definitively should because according to the [Node.js release schedule](https://github.com/nodejs/Release) Node.js v10 will become `Active LTS ` simultaneously to v8 in October 2018.

**Comment by sangaman** [comment]
From what I understand this is still supported in v10, and will only be dropped in a future release, so it doesn't interfere with v10 support I don't think. The deprecated code is in our generated proto files, so it's an issue with the proto generation dependencies.

I think it's probably the `grpc-tools` package that we need updated, they haven't published an npm release in roughly a year, although there's much newer releases on their github. I've previously commented on an issue asking for a new release and it sounds like they will eventually get around to it. In the meantime I suppose we can see if pointing to their latest release from github in package.json resolves this, but I'm fine with waiting for a release.

**Comment by kilrau** [comment]
Not pressing, but definitely keep this open, we'll revisit this in November once v10 is LTS and plans are clearer.

**Comment by michael1011** [comment]
I found a workaround in [this issue](https://github.com/grpc/grpc-node/issues/438):
```
sed -i -- 's/new Buffer(/Buffer.from(/g' lib/proto/*.js
```

It is quite hacky and `sed` doesn't exist on Windows but I wanted to let you know.

**Comment by ImmanuelSegol** [comment]
@michael1011 Seems good for now, we will just change it later on.
I will try to find something for windows 👍
