### ISSUE TITLE
new RPC - listSwapDeals

### ISSUE THREAD

**Issue by offerm** [ExchangeUnion/xud#477]
Suggest creating an RPC that extract the list of SwapDeals done. 

We have interesting data there list status, state, errormessae, createtime, executetime, completetime that the educate us and help to debug.

For now, we can show information from memory but in the long run, we should store/extract from the database.

**Comment by sangaman** [comment]
Do we want to store all swap deals to the database, including failures? I think it would make sense (separate from this PR) to write finished deals to the database and remove them from memory.

**Comment by offerm** [comment]
Since we deal with "real" money, we need to record everything.
Minimum would be a log file which is not getting lost easily.

Better to log to database swap, orders, etc. Everything that deal with
money.

In general, we should never permanently delete these objects. It is ok to
delete from memory but only when backed to a persistent storage.

IMHO

**Comment by sangaman** [comment]
Sounds good to me. Although we are not putting orders themselves in the database, we'd have a record of any that get filled via swaps.

**Comment by kilrau** [comment]
Yes we want to save all successful and failed swaps in the db. See https://github.com/ExchangeUnion/xud/issues/161
So this issue is about implementing a RPC call to query these.

Feel free to put proposals for the datafields please into 161 :)

**Comment by sangaman** [comment]
Question on this, should this query the db? If we are only keeping "active" swap deals in memory - which makes sense to me - but means that there won't be many swaps available at any given times (only ones that are in progress). If so, it would seem a precursor is actually saving completed swaps to the db. I figure we'd want to set a limit on what we query, and not return the full history of swaps each time we call this.

**Comment by ImmanuelSegol** [comment]
I will make a pr for this issue along with issue #562 I'm working on.

**Comment by kilrau** [comment]
Yes, I believe this should query the db @sangaman , hence dependent on https://github.com/ExchangeUnion/xud/issues/562 . But important for exchanges to see 'results' of their testing.

**Comment by kilrau** [comment]
Do you need help on this one? @ImmanuelSegol

**Comment by ImmanuelSegol** [comment]
@sangaman @kilrau What data from the swap deal should we return?

**Comment by sangaman** [comment]
My inclination is to go with everything in the database.

**Comment by sangaman** [comment]
I'd probably wait until #623 is merged, at which point I think we'll want to do a join on the new `orders` table. I'll provide more details soon.

**Comment by sangaman** [comment]
Closing this in favor of a single rpc call for swaps/trades - #1567.
