### ISSUE TITLE
TS & nodemon

### ISSUE THREAD

**Issue by moshababo** [ExchangeUnion/xud#48]
When running `npm run dev`, `nodemon` should start watching only TypeScript compilation is done.

**Comment by Chikel** [comment]
Now that there are no TS errors, we can first run `tsc` then run both watchers (tsc and nodemon) parallel. The problem here is that `tsc -w` first compiles then watch (which is of course redundant).

**Comment by moshababo** [comment]
Wouldn't TS compile only changed modules?

**Comment by Chikel** [comment]
It will first compile all input files, then watch and compile changed files.

**Comment by moshababo** [comment]
Yes, it seems that on an initial compilation, TS compiles everything regardless to whether changes happened or not. So in this case we'll have to listen to TS compilation, and only after it finishes, launch `nodemon` in parallel. Something which is probably not possible through the CLI. 
So we'll leave this out for now.
