### ISSUE TITLE
getinfo does not show lnd error any more

### ISSUE THREAD

**Issue by offerm** [ExchangeUnion/xud#488]
@sangaman on August 18 you committed `refactor getinfo service call`

That commit made `error` not to be shown.

Was that on purpose?

I will issue a PR for getInfo and going to fix this problem. Let me know if this is a bug or you removed it intentionally

**Comment by sangaman** [comment]
I don't think it was intentional, we'd want to know the error if get info fails so go ahead.

**Comment by offerm** [comment]
This was fixed already.
Can be closed
