### ISSUE TITLE
xud1,2,3 - setup for swap to support routing

### ISSUE THREAD

**Issue by offerm** [ExchangeUnion/xud#508]
In currently working to finalize SWAP support. 
Basically, the only thing left is to properly support SWAP when the taker and maker do not have direct channels between them.

To test this we need a more complicated environment. 

I suggest to setup xud1,2,3 with BTCD, LTCD support, install LNDs on each and connect them with channels. Once this is working we need latest XUD and proper setup.

It would also be great if we can setup CD for these nodes so they will "refresh" everytime we merge to master.

@kilrau can this be done? Do you want me to set it up?

**Comment by kilrau** [comment]
What you describe is all in:
https://github.com/ExchangeUnion/xud/issues/191
https://github.com/ExchangeUnion/xud/issues/472

closing this one.

**Comment by kilrau** [comment]
And yes would be great if you could take over #472
