### ISSUE TITLE
Peer connection and LND info

### ISSUE THREAD

**Issue by offerm** [ExchangeUnion/xud#513]
For executing a swap the taker and maker should be ower of the peer PubKeys of BTC/LTC.

This information is now provided as part of the handshake when the nodes connect.

Problem: Assume A and B (nodes). A connects to B. at the time A connects to B it's LND processes are down so A does not have PubKeys to share with B. Later the LNDs processes are up and A connects to them but B is unaware of PubKeys and can't swap with A.

**Comment by sangaman** [comment]
Yeah, this falls under handshake state updates, which are currently supported by the p2p layer but are not being triggered yet. I believe I know what needs to be done for this, I'll handle it soon.

**Comment by offerm** [comment]
Don't you think it is simpler to have this info in the swap request?

It is also somehow relevant to accepting orders from the user and from
peers.

**Comment by sangaman** [comment]
It's probably a little bit simpler yes, but I think the handshake approach is worthwhile for a couple of reasons:

1. The lightning will be changing very rarely if ever, and when they do it will probably be while `xud` is offline I would guess.
2. There'd potentially be a lot of redundant data transmission with communicating the keys for each swap and it's not ideal for production use.
3. We might want to handle the case you mention differently in the future - maybe we don't want to start making p2p connections until we've verified connections to all the lnd clients that are supposed to be active for instance. 
4. We will need to have the ability to update handshake state anyway for other purposes, so the added complexity of updating lightning pubkeys is minimal I think.

Also given that it's already using the handshake approach, it would be work to switch it back again.

**Comment by kilrau** [comment]
Agree with Daniel, our goal is to have the swap protocol as lightweight as possible so we shouldn't go back to exchanging keys on swap. Fix it via handshake updates and that's it. I put this into the next milestone.
