### ISSUE TITLE
addcurrency cli command issue 

### ISSUE THREAD

**Issue by moshababo** [ExchangeUnion/xud#527]
After #511 merged, `addcurrency` CLI command stopped working. The CLI is expecting an upper-case `swap_client` argument, while it's being applied on a camel-case enum.

**Comment by sangaman** [comment]
Good catch, although I definitely think we should take care of this by alpha.1 - don't want to have known bugs in releases if possible plus this is an easy fix.

**Comment by kilrau** [comment]
Assigned @moshababo , but feel free to take care @sangaman @michael1011

**Comment by ImmanuelSegol** [comment]
Can I take this?

**Comment by sangaman** [comment]
I'm handling this now since we want it fixed before the alpha.1 release.
