### ISSUE TITLE
Swap improvements

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#528]
Missing according to @offerm:

1. Allow maker to reduce the quantity suggested by the taker's SWAP_REQUEST message. I suggest not to touch this until order book integration is done and there is a good feedback/visibility to the user.
2. Timeouts on RPC calls (queryroutes, sendToRoutes, sendPayments, getinfo) are missing. We should add these and handle them.
3. sanity - taker to check the r_preimage it got from sendPaymentSync and compare it with the deal.preImage. Not very important
4. cleanup - remove swap.reject and swap.accepted if there is no use of these. Should be done after orderBook integration
4. support totalCltvDelta - This is needed to prevent a route which results in a too big lock time. This can be done now or we wait until [LND's #1941](https://github.com/lightningnetwork/lnd/pull/1941) is accepted.
5. fees - LND's sendPayment fees should somehow be limited. This is supported on LND's side with --fee_limit. Need to decide how to support it on XUD. Also with a config option (we can also name it `fee_limit`, default is 3% of the payment amount as currently used by eclair) Issue: https://github.com/ExchangeUnion/xud/issues/915
6. Multi routes - currently the maker to taker payment is limited to one route (best). Supporting multi-route is not complicated but should be done once we have a testing environment.

**Comment by offerm** [comment]
@sangaman @kilrau  any idea on this one
```
fees - LND's sendPayment fees should somehow be limited. This is supported on LND's side with --fee_limit. Need to decide how to support it on XUD.
```

should we add -fee_limit to our setup?

**Comment by kilrau** [comment]
I'd say so, yes. With a reasonable default (e.g. eclair has 3% of the payment amount)

**Comment by kilrau** [comment]
Status? @offerm

**Comment by offerm** [comment]
Suggest to move down in the milestones.

**Comment by kilrau** [comment]
Hmm ok, all of the bullet points in the issue description still open? @offerm

**Comment by sangaman** [comment]
I believe they're all still open, but none particularly urgent as I see it.

**Comment by kilrau** [comment]
Moved down to `alpha.4`

**Comment by kilrau** [comment]
Moved down (after raiden integration)

**Comment by kilrau** [comment]
Also moved to `post-1.0.0`, wouldn't want to touch the swap protocol from here

**Comment by kilrau** [comment]
Can we go through these point by point and decide which one we want and then open sub-issues with details each. Then close here. @offerm @sangaman @erkarl @michael1011
