### ISSUE TITLE
Publish existing orders on subscribeAddedOrders

### ISSUE THREAD

**Issue by moshababo** [ExchangeUnion/xud#534]
All existing orders need to be published so the client can be fully synced with the order book state, in case he subscribed on a non-empty state.

https://github.com/ExchangeUnion/xud/pull/500#issuecomment-424957594

**Comment by sangaman** [comment]
Yeah I think this is a useful feature to have, I'm going to propose this for the next milestone. I think ideally whether to get back existing orders should be optional, with a boolean field in the request, although we can have it return existing orders by default.

**Comment by kilrau** [comment]
Important, but not realistic for alpha.2 which I just extended to 28th, moved to alpha.3

**Comment by kilrau** [comment]
I'm thinking of returning existing order in the stream upfront as default as this sounds like what I'd want as an exchange and an option/boolean to switch it off.

**Comment by sangaman** [comment]
Yeah, having that be the default behavior would make sense actually. I'd be in favor.

**Comment by kilrau** [comment]
All clear with this one? @ImmanuelSegol
