### ISSUE TITLE
Check that we don't already have an r_hash for swap requests

### ISSUE THREAD

**Issue by sangaman** [ExchangeUnion/xud#547]
Currently, we don't have any checks up front when handling a swap request to see if we currently have or ever had a swap for that r_hash. We definitely don't want to allow reuse of preimages or anything like that, so we should detect this and reject the swap.

**Comment by erkarl** [comment]
Going to work on this one.

**Comment by sangaman** [comment]
Great, I think it makes sense to merge this after #569 so that we can check archived deals along with active deals, but you can open the PR now and it shouldn't be too hard to adjust it afterwards.

**Comment by ImmanuelSegol** [comment]
@erkarl I kinda solved this in #569 :(

**Comment by erkarl** [comment]
@ImmanuelSegol No harm done. Thanks for letting me know. I'll take a look.

**Comment by kilrau** [comment]
So as far as I understand @ImmanuelSegol https://github.com/ExchangeUnion/xud/blob/8540da03e95950fa67e2a60890fdd9f5dacf681e/lib/swaps/Swaps.ts#L81 saves hashes in `  private hashs = new Set<string>();` so now we only need to check against this when starting a new swap @erkarl

**Comment by sangaman** [comment]
Yes that's right, we still need the check for existing r_hash even after #569 is merged.
