### ISSUE TITLE
Minor swap refactoring/renaming

### ISSUE THREAD

**Issue by sangaman** [ExchangeUnion/xud#551]
Below is a list of minor and/or superficial refactorings to the swaps related code that I think would be desirable:

- Rename `SwapErrorPacket` to `SwapFailedPacket`. My thinking is that a swap failure is not always due to an "error" per se, it could just be rejected even when everything is functioning as expected. This also aligns with the `swap.failed` event name.
- On error/failure responses, send an enum failure reason rather than a string. This involves less data transmission between peers, and more importantly it makes checking the error or failure reason easier since we don't need to compare exact strings where a typo could mess things up and go undetected by the compiler.
- Rename `SwapResponsePacket` to `SwapAcceptedPacket`. As it's set up currently, the swap response always indicates acceptance of the swap, so I think this name is a bit more descriptive. 
- Rename `SwapDealRole` to `SwapRole`. I think the "Deal" part is redundant and the role applies not just to the deal.
- Rename `SwapDealPhase` to `SwapPhase`. Same as above.
- Rename `SwapDealState` to `SwapState`. Same.
- Rename `stateReason` to `errorReason`. It seems like the only way this field is being used is when swaps fail, and the reason for the "Active" and "Completed" states seems obvious. Also if we go with an enum failure reason, this field can possibly use the same enum type instead of a string.
- Rename `myRole` to `role`. I think the "my" is implied.

Let me know if you agree or disagree on anything in particular.

**Comment by sangaman** [comment]
Another minor thing to change is switching `r_hash` and `r_preimage` to camel case `rHash` and `rPreimage` to be consistent with the project-wide variable naming. This is also consistent with how those variables are generally named internally in lnd, it's mainly the rpc layer where snake_case is used.

**Comment by moshababo** [comment]
Sounds fine to me.
