### ISSUE TITLE
Handle remove order request when order is on hold for pending swap

### ISSUE THREAD

**Issue by sangaman** [ExchangeUnion/xud#552]
With the possibility that an order is on hold for a pending swap, we need to handle the case when we receive a request to remove such an order from the order book. I'm thinking the best approach would probably be to hold off on removing that order until any holds are removed, but there are a few things to consider.

- Don't allow any new holds to be placed on an order that we are in the process of removing
- How should we respond to a `removeOrder` request if the order gets fully swapped - do we just respond with the "order not found" error as if the order never existed in the first place?
- Off the top of my head the approach I'd go for is to listen to the `swap.failed` and `swap.paid` events and recheck if `order.hold === 0` after each one, does that sound reasonable?

**Comment by kilrau** [comment]
I'll take this one, related https://github.com/ExchangeUnion/xud/issues/587#issuecomment-433472493

**Comment by kilrau** [comment]
Only applicable for matching mode.

Your suggestion sounds good. Would definitely go for a different error message, sth along the lines "order currently swapping, order will be automatically removed if swap doesn't succeed".

**Comment by kilrau** [comment]
> I don't think this would apply only to matching mode - in non-matching mode you can still submit orders to xud and remove them. There's the same possibility that someone tries to swap your order at the same time as you try to remove it.

I understand what you are saying is that the exchange could still try to invalidate/remove its `ownOrder` while it's currently being swapped with a peer BUT this is something we strictly should avoid IMO by XUD removing the order from the exchange *before* finalizing a swap with a peer. An exchange is not used to a "pending removal" or failed removal. This would be new functionality to implement which we want to avoid as much as possible in `nomatching` mode. If an order is in the order book and unfilled, it can be removed. Do you agree? @sangaman 
Nevertheless adding the functionality to `nomatching` mode doesn't hurt.

> And instead of an error message I'm adding a field to the response to indicate whether a portion of the order was on hold. I don't think it's an "error" per se since the order will still be removed eventually, just that some of it was in the middle of being swapped.

Sounds good.
