### ISSUE TITLE
xucli output enhancements [WIP]

### ISSUE THREAD

**Issue by sangaman** [ExchangeUnion/xud#558]
This issue is to track enhancements to the output from `xucli` to make it prettier and more user-friendly than the JSON outputs it's currently spitting out

A major point is the `getorders` output, which is currently a mess once you have more than a few orders. We should be displaying only key information and preferably in a table.

Generally speaking we'd want to convert epoch times into local date/times, enum numbers into their corresponding key strings, hide data that is not relevant to the user, and generally make output more concise and readable. Colors would be a bonus.

I figure this can be done across multiple PRs, so if you want to work on a particular command or feature just comment here and reference this issue in the PR.

https://www.npmjs.com/package/cli-table - This package looks promising for when we need to display tabular data, such as with `getorders`.

**Comment by sangaman** [comment]
A suggestion from @offerm 

> My feedback relates to the CLI for buy and sell.
> As a user, I'm expecting to understand what is going on. If I place an order the outcome should be something like
> 'accepted and waiting' (with data)
> 'partially executed' (with data)
> 'fully executed' (with data)
> etc

**Comment by erkarl** [comment]
Going to work on this one.

**Comment by kilrau** [comment]
Check https://sparkswap.com/img/top-fold-terminal.gif @erkarl

**Comment by kilrau** [comment]
https://github.com/ExchangeUnion/xud/issues/620 takes care of the [described](https://github.com/ExchangeUnion/xud/issues/558#issuecomment-428205056) place buy/sell order output.

**Comment by kilrau** [comment]
How about a 'command preview' based on the alphabetically first (on first use of CLI session) or last used command?
![image](https://user-images.githubusercontent.com/19181985/48129236-2a20f500-e289-11e8-8467-0277971355f1.png)

**Comment by sangaman** [comment]
Off the top of my head I don't know how that would be done, but if it's doable then it would be nice for sure.

**Comment by erkarl** [comment]
I'd push this under future improvements/someday/nice to have.

**Comment by kilrau** [comment]
This issue is about going through all CLI outputs and format them properly to be more friendly and readable. Mostly creating tables for `list` and `getinfo`.

**Comment by rsercano** [comment]
I suppose all related issues already have PR. Let me know if there's additional work required

**Comment by kilrau** [comment]
All have PRs or separate issues. Closing here.
