### ISSUE TITLE
Store swapdeals to database, remove from memory

### ISSUE THREAD

**Issue by sangaman** [ExchangeUnion/xud#562]
We want to persist swap results (whether successful or failed) to the database for historical/informational purposes. This will require a new table in the database. Probably not every property of a `SwapDeal` needs to be persisted, but certainly enough to know what the swap was for, how much, with who, when it completed, etc...

Once a result has been persisted, we can remove it from the collection of swap deals stored in memory. However, I'm thinking we probably want to maintain in memory a list of payment hashes that we've used in the past, so that we don't reuse one (see #547). For that reason, we may also want to load all payment hashes from the database on startup.

**Comment by ImmanuelSegol** [comment]
I think I will give this a shot if that's ok.

**Comment by sangaman** [comment]
Fine with me, thanks.

**Comment by kilrau** [comment]
Can this issue be closed? @sangaman 

Do we store failures? @moshababo  Could lead to a bloated database in the long run. I'd put a limit on storing failed swaps, like e.g. only the last 1000 failed ones.

**Comment by sangaman** [comment]
@offerm was in favor of storing everything including failed swaps and I agreed, I think it's fine for now and eventually we can add scripts to prune old failed swaps from the database I figure.

**Comment by kilrau** [comment]
Ok, so good to close here?

**Comment by kilrau** [comment]
What's the primary key? r_hash? @sangaman @offerm
