### ISSUE TITLE
Refactor peer penalizing/banning logic

### ISSUE THREAD

**Issue by sangaman** [ExchangeUnion/xud#566]
Currently, there's logic in Peer.ts around penalizing and banning peers. When the score exceeds a threshold, it emits a `ban` event, which in turn triggers a manual ban. We should change this so the `Peer` object doesn't track scores or decide when to ban - we have that logic in Pool.ts and NodeList.ts. Instead, it should emit an event when a reputation event occurs, which in turn should trigger calling the `addReputationEvent` method.

**Comment by ImmanuelSegol** [comment]
@sangaman Should I add new `ReputationEvent` for:

- Unparsable peer message

- Invalid peer message

- Unknown peer message type

**Comment by sangaman** [comment]
Yes, we have a lot of TODOs throughout the codebase where we should be penalizing peers, if you want to create events for those and make a reasonable guess for a score that would be great.
