### ISSUE TITLE
Mark lnd as Disconnected when calls to it fail

### ISSUE THREAD

**Issue by sangaman** [ExchangeUnion/xud#573]
We ought to handle the case where calls to lnd fail, whether it be a single failure or some number of multiple consecutive failures. The reason for this is that when lnd goes down for any reason, we lose the ability to perform any swaps for that lnd's currency. If we continue to place orders and attempt swaps for any trading pairs involving that currency, we will cause many swap failures and peers may ban us. Handling an lnd instance that goes down may involve canceling all our orders for any trading pairs affected by that instance, and not accepting new orders until we reestablish connectivity.

We may also consider periodically calling `getInfo` on lnd to ensure that we get a timely response and that the state is nomral, `synced_to_chain` is true, and so on.

**Comment by sangaman** [comment]
Yes, we probably need further discussion on the afterthought of periodically pinging `lnd` to make sure it's working, but the first part of disabling the LndClient if calls to `lnd` fail due to connectivity errors or anything we don't expect to recover from automatically can be worked.

**Comment by kilrau** [comment]
Please prepare the code to include pings to raiden and other swap nodes, not only LND. @ImmanuelSegol

**Comment by sangaman** [comment]
I'd recommend opening a PR just for the lnd side of  things first.

**Comment by kilrau** [comment]
Agree, let's do that @ImmanuelSegol

**Comment by kilrau** [comment]
use `SubscribeInvoices` streaming call to detect if lnd is down
