### ISSUE TITLE
Don't write files to disk during automated tests

### ISSUE THREAD

**Issue by sangaman** [ExchangeUnion/xud#574]
Currently, xud will potentially write files to disk during automated tests, namely the node key file and tls.cert. We should ensure that the tests do not write any files, nor make any other persistent changes.

**Comment by kilrau** [comment]
something for @erkarl or @moshababo ?

**Comment by kilrau** [comment]
Did you look into details here already? An overview what needs to be done and how long it might take? @moshababo

**Comment by moshababo** [comment]
Closed by #950.
