### ISSUE TITLE
Option to stream all existing orders up front on SubscribeAddedOrders

### ISSUE THREAD

**Issue by sangaman** [ExchangeUnion/xud#582]
Currently, subscribing to added orders only notifies you of newly added orders. We should add a boolean flag to the SubscribeAddedOrdersRequest that specifies whether to return existing orders. When this is true, we should write all existing orders to the stream up front.

**Comment by moshababo** [comment]
#534 duplication?

**Comment by sangaman** [comment]
Oops, my mistake I couldn't remember if it existed and couldn't find it.
