### ISSUE TITLE
Automated integration/simulation testing with lnd & multiple xuds

### ISSUE THREAD

**Issue by sangaman** [ExchangeUnion/xud#588]
This issue is to track setting up automated tests that spin up `btcd` & `ltcd` using either simnet or regtest networks, along with multiple `xud` instances each with its own pair of `lnd` instances for btc and ltc. The goal is to be able to simulate actual usage of `xud` and test full integration with external components and services. Currently, we cannot test order execution with swaps in an automated fashion.

Some questions to consider:

- Should these tests be written in Go or Typescript? It seems like Go would present less of a challenge for spinning up `lnd`, `btcd`, and `ltcd` . Ultimately I'd go with whatever is simplest/easiest.
- Should these tests be in a separate repository? That would be fine with me as long as we can properly integrate it into the build/test process for this one, such that Travis tests automatically for PRs in this repo and that we can test locally using a script from this repo.
- Naming: We have "integration" tests already that test integration between separate classes/components within xud. So we could call these "simulation" tests since they simulate actual usage of xud. 
- Overlap with existing tests: I was originally thinking that the existing p2p sanity tests and perhaps the Service.spec.ts test would be obsolete, although it probably wouldn't hurt to keep them even if there's some redundancy. Still, a lot of the functionality for both the p2p layer and the API layer is dependent on working swaps and lnd instances.

Writing comprehensive test cases is beyond the scope of this issue, but once this is complete we can address those.

**Comment by moshababo** [comment]
I'm starting to work on this. 

I think we should focus on this high-level integration tests to be run in a single machine, and thus not as a full network simulation. Let me know if you agree on this.

**Comment by moshababo** [comment]
I'm going to start working on this soon.

I think we should focus on this high-level integration tests to be run on a single machine, and thus not as a full network simulation. Let me know if you agree on this.

**Comment by moshababo** [comment]
We can obviously still call them simulation tests.

**Comment by erkarl** [comment]
I like the idea of starting with a single machine to lower complexity.

**Comment by moshababo** [comment]
I opened a new golang repo for the tests, with the initial commit PR. Lets continue the discussions there. 

https://github.com/ExchangeUnion/xud-simulation
