### ISSUE TITLE
Meaningful failed / successful doesn't provide a useful response

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#601]
Missing info:
- historical matches
- failed swaps (maybe as `placeOrder` response)

Proposed Calls:
`listSwapDeals`
`listTrades`

**Comment by sangaman** [comment]
We already have an issue for `ListSwapDeals`, then I think we should split this up into separate issues for storing successful trades and creating a `ListTrades` rpc call, as well as returning failed swaps in the `PlaceOrder` response. Mind if I create issues for those and close this in favor of those? I also don't think alpha.2 will be realistic unless we extend the date for that.

**Comment by kilrau** [comment]
ok, please go ahead create these and close here @sangaman
