### ISSUE TITLE
Add failed swaps to placeOrder (buy/sell) response

### ISSUE THREAD

**Issue by sangaman** [ExchangeUnion/xud#609]
It might be useful to know whether a placed order attempted to swap with any peer orders but failed. Currently `placeOrder` only returns information about successful swaps and internal matches. We could make it also return failed swaps. I figure for each failed swap we'd want to know the `orderId` and maybe `quantity` and `peerPubKey`, maybe the error message for why the swap failed`? Comment if you can think of anything else that might be worth returning.

**Comment by kilrau** [comment]
So instead of only persisting it in the db as per https://github.com/ExchangeUnion/xud/issues/562 you suggest also to return failed swap info in `placeOrder` sync until a swap succeeds, correct?

`orderID`, `pair`, `quantity`, `price`, `peerPubKey`, error message

**Comment by sangaman** [comment]
It would be for both the sync and streaming place order calls, but yeah otherwise that's right. Altho even if a swap never succeeds, we'd still want to return any swaps that failed.

**Comment by kilrau** [comment]
Solves parts of https://github.com/ExchangeUnion/xud/issues/620

**Comment by kilrau** [comment]
Output today:
```
admins-MacBook-Pro-2:xud admin$ xucli buy 0.0025 LTC/BTC 1.105
swapped 0.001 LTC with peer order 62e45ed0-eccb-11e8-a9ee-5d8556a34cdc
remaining 0.0015 LTC entered the order book as 92a14980-eccb-11e8-bb8f-69b162a0c6a5
admins-MacBook-Pro-2:xud admin$ 
```

How it should be:
```
$ xucli buy 0.0025 LTC/BTC 1.105
matched 0.001 LTC with peer order 62e45ed0-eccb-11e8-a9ee-5d8556a34cdc
matched 0.0015 LTC with peer order 87e44ed9-xxxx-xxxx-xxxx-xxxxxxxxxx
swapped 0.001 LTC with peer order 62e45ed0-eccb-11e8-a9ee-5d8556a34cdc
failed to swap 0.0015 LTC with peer order 87e44ed9-xxxx-xxxx-xxxx-xxxxxxxxxx
remaining 0.0015 LTC entered the order book as 92a14980-eccb-11e8-bb8f-69b162a0c6a5
```
