### ISSUE TITLE
Limit Order (IOC)

### ISSUE THREAD

**Issue by offerm** [ExchangeUnion/xud#622]
EDIT by @kilrau : we want IOC only for now: https://github.com/ExchangeUnion/xud/issues/622#issuecomment-557157547

I suggest to support FOK & IOC with limit  orders.

Use case:

with getorders I see a peer order that I wish to take.
since I never use market orders :-) I issued a limit order targeting the peer order.

The matching with the peer order failed for some reason (peer order does not exists anymore, swap failed, etc), As a result my take order entered the book and broadcasted to all my peers. This was not my intention.
FOK - fill the order or kill it.
IOC - fill immediate or cancel 

reference - http://optionstradingbeginner.blogspot.com/2009/01/fill-or-kill-fok-immediate-or-cancel.html

**Comment by kilrau** [comment]
... which we could take and simulate market orders if we wanted/needed to. Other thoughts? @sangaman @moshababo

**Comment by moshababo** [comment]
Sounds good to me.

**Comment by sangaman** [comment]
This would be simple enough to do, it's basically a limit order (with a price) where we set `discardRemaining` to true. It can be an optional flag on the `placeOrder` request.

**Comment by kilrau** [comment]
Let me know what you think @offerm @moshababo @sangaman 

**Summary** 

`placeOrder` with flag `fok` (Limit Fill-or-Kill, make sure `fok` flag doesn't work with Market):
search order book for match of total quantity (no partial matching allowed)
    if match found & swap successful
        remove matched order as usual
    else cancel order and return discarded remaining order

`placeOrder` with flag `ioc` (Limit Immediate-or-Cancel, make sure `ioc` flag doesn't work with Market):
search order book for match (partial matching allowed)
    for match found & swap successful
        remove matched order as usual
    `discardRemaining` quantity, nothing enters the order book

CLI UX Example FOK:
```
$ xucli buy 0.0001 LTC/BTC 1.1 --fok
{
  "internalMatchesList": [],
  "swapResultsList": [],
  "remainingOrder": {
    "price": 1.1,
    "quantity": 0.0001,
    "pairId": "LTC/BTC",
    "id": "0298b691-e26f-11e8-bc86-4938fbce63e9",
    "peerPubKey": "",
    "localId": "0298b690-e26f-11e8-bc86-4938fbce63e9",
    "createdAt": 1541582704761,
    "side": 0,
    "isOwnOrder": true,
    "discarded": true
  }
}
```
CLI example IOC:
```
$ xucli buy 0.0001 LTC/BTC 1.1 --ioc
{
  "internalMatchesList": [],
  "swapResultsList": [],
  "remainingOrder": {
    "price": 1.1,
    "quantity": 0.0001,
    "pairId": "LTC/BTC",
    "id": "0298b691-e26f-11e8-bc86-4938fbce63e9",
    "peerPubKey": "",
    "localId": "0298b690-e26f-11e8-bc86-4938fbce63e9",
    "createdAt": 1541582704761,
    "side": 0,
    "isOwnOrder": true,
    "discarded": true
  }
}
```

**Comment by offerm** [comment]
FOK can be tricky with XUD.

To properly support it we need all the swaps to use the same preimage and
the taker should release the preimage only if and when he got the payment
from the maker for all the swaps initiated by taker.

IOC and AON can be easier to implement.

We can redefine FOK in a way that it must be matched with a single maker
order. This may create a situation in which the match will not be done with
the best price order.

**Comment by kilrau** [comment]
FOK: I already defined it in the way you described for the reason you described (https://github.com/ExchangeUnion/xud/issues/622#issuecomment-436562651: `no partial matching allowed` means match with one order or none.

Addition to your reason: we could theoretically only support partial matches with the **same taker** anyways, but not with different takers since they all would need to agree on using the same pre-image which is impossible. And yes this may result in a not-best price match, but still at or below the limit price which is the definition of [FOK](http://optionstradingbeginner.blogspot.com/2009/01/fill-or-kill-fok-immediate-or-cancel.html). So I think we are good here.

Don't see a great use case for AON for now.

**Comment by offerm** [comment]
> Addition to your reason: we could theoretically only support partial matches with the same taker anyways, but not with different takers since they all would need to agree on using the same pre-image which is close to impossible. 

Why the same preImage can't be used for multiple makers? Should not be a problem since we have a single taker and multiple makers.

**Comment by kilrau** [comment]
Prio bump: hedgy needs this

We want IOC only (allows partial execution) so that hedgy can use these instead of market orders.
