### ISSUE TITLE
XUD without LND channels

### ISSUE THREAD

**Issue by offerm** [ExchangeUnion/xud#636]
Need to handle the case when XUD is running without LND channels for BTC or LTC.

Today, The system allows orders to be entered and matching can be done (but fails).

The more generic case is `no capacity to allow the trade` - when the user enter an order, check if this order can technically be executed due to input/output capacity and balances. We should keep in mind that the situation is dynamic and may change (so maybe a warning or config which defines how this should be handled).

Similarly, when we accept a peer order, we can check if technically we can trade it.

**Comment by kilrau** [comment]
Doesn't https://github.com/ExchangeUnion/xud/issues/240 capture this? 

I believe entering and matching should be allowed and just failing needs to be made comprehensive. As you said channels are very dynamic and can be even topped up in future, thus we would want allow orders to enter the order book and be matched. A warning upon order entering sounds good though. All added in #240 . Check if this can be closed. @offerm

**Comment by kilrau** [comment]
Enhanced #240 to capture all, closing this
