### ISSUE TITLE
DB migration script needed

### ISSUE THREAD

**Issue by offerm** [ExchangeUnion/xud#652]
listen ports didn't open.
got this error in log

```
11/9/2018, 8:01:26 AM [GLOBAL] info: config loaded
11/9/2018, 8:01:26 AM [GLOBAL] info: Local nodePubKey is 02db8d5f43940fa1632ad2e2c0761b608e54fcca9c7502f961d17e290e66ad99a6
11/9/2018, 8:01:26 AM [DB] info: connected to database xud.db
11/9/2018, 8:01:26 AM [LND] info: macaroons are disabled for lnd at localhost:10002
11/9/2018, 8:01:26 AM [LND] info: LndClient status: Disconnected
11/9/2018, 8:01:26 AM [LND] info: trying to verify connection to lnd with uri: localhost:10002
11/9/2018, 8:01:26 AM [LND] info: macaroons are disabled for lnd at localhost:10001
11/9/2018, 8:01:26 AM [LND] info: LndClient status: Disconnected
11/9/2018, 8:01:26 AM [LND] info: trying to verify connection to lnd with uri: localhost:10001
11/9/2018, 8:01:26 AM [GLOBAL] error: SequelizeDatabaseError: SQLITE_ERROR: no such column: rHash
    at Query.formatError (/Users/admin/xud-simnet/xud/node_modules/sequelize/lib/dialects/sqlite/query.js:423:16)
    at afterExecute (/Users/admin/xud-simnet/xud/node_modules/sequelize/lib/dialects/sqlite/query.js:119:32)
    at replacement (/Users/admin/xud-simnet/xud/node_modules/sqlite3/lib/trace.js:19:31)
    at Statement.errBack (/Users/admin/xud-simnet/xud/node_modules/sqlite3/lib/sqlite3.js:16:21)
11/9/2018, 8:01:26 AM [LND] info: LndClient status: ConnectionVerified
11/9/2018, 8:01:26 AM [LND] info: LndClient status: ConnectionVerified
```

Impact: all sim-net nodes are down.

**Comment by erkarl** [comment]
Deleting the database `xud.db` worked for me. There was a breaking database change without migration.

**Comment by offerm** [comment]
Even that is a lot of work. I have at least 5 machines where this should be done.
Also, I'm not sure what the impact of this is on the cloud servers. I don't want to configure the sim-net again.

**Comment by erkarl** [comment]
I think we should introduce migrations in the near future to prevent situations like these.

**Comment by offerm** [comment]
So, I solved it manually by removeing the `xud.db` on all instances and restart.

Will change the title too.

**Comment by sangaman** [comment]
Sorry I just saw this, yes it's due to breaking changes in the database structure. I'm hoping there shouldn't be any more for a while, and yes it would be nice to automatically upgrade/migrate in the future, particularly when there are more users.

**Comment by kilrau** [comment]
I was aware because we discussed about it, but the db PRs were not listed in the "BREAKING CHANGES" section in the `alpha.3` changelog. Something to pay attention to. And maybe we can adjust the commit template and force to add a "How to deal with it" section for breaking changes.  Agree that scripts etc. are not worth the effort since most likely not reusable.

Anyhow, no drama - all internal still.

**Comment by kilrau** [comment]
Can be closed? @offerm

**Comment by offerm** [comment]
This one can be closed.

Suggest to have an issue for migration script.

@sangaman each change of the database should bring with it the code needed for migration,
