### ISSUE TITLE
Comprehensive SwapFailureReason

### ISSUE THREAD

**Issue by sangaman** [ExchangeUnion/xud#671]
This is partly an offshoot of #661 (and would be good to implement before that PR is solved). Right now we only set a string error message on swaps when they fail/error. We can keep that for details on the error (like the error message returned from lnd), but it would also be nice to have a clearly defined reason for the failure where we can easily do something like `if (swapDeal.failureReason === ____ ) { ...`.

The swap failure reason would be sent with the swap failure packet and added to the database when a swap is persisted.

**Comment by kilrau** [comment]
Sounds good and sounds like this should be the first thing todo? @offerm ?

**Comment by sangaman** [comment]
Oh sorry I meant to assign to myself - I actually already have some code written for this (from when I was working on #627). It's nothing much so offer can do it if he's looking for something, but I already have some of the changes in mind.
