### ISSUE TITLE
CLI - buy/sell fails due to grpcOrder.setHold

### ISSUE THREAD

**Issue by erkarl** [ExchangeUnion/xud#674]
Using latest master (03b8cd4f3f9f327f1444a2c9a142bfd8875f19cf) `xucli buy/sell` commands error with the following output:
```
[RPC] error: grpcOrder.setHold is not a function
```

Caused by: #645 

CC @ImmanuelSegol @sangaman

**Comment by ImmanuelSegol** [comment]
@erkarl It works for me on master branch.

**Comment by sangaman** [comment]
Sorry I just saw this. `xucli buy` is working for me as well, can't reproduce. @erkarl, did you make sure you compiled after getting the latest from master?

**Comment by erkarl** [comment]
@ImmanuelSegol @sangaman 

Turning it off and on again worked. I was using `dev:watch` which I assumed would copy `lib/proto` to `dist/proto`.

Sorry for the false alarm.
