### ISSUE TITLE
Caching Channel Balance Thresholds

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#680]
We want to cache the following values:
`<coin>_channel_min_in` (default 15% of total channel capacity, all <coin> channels aggregated)
`<coin>_channel_min_out` (default 15% of total channel capacity, all <coin> channels aggregated)

**This issue is just about caching the value**, we'll take care of rebalancing & other actions like [sending alerts](https://github.com/ExchangeUnion/xud/issues/864) in follow-up PRs. The % should be configurable either via `xud.conf`/cli paramter requiring a restart, better even with a separate cli call not requiring to restart xud. The cached values should be updated every 60s and immediately after each trade.

**Comment by kilrau** [comment]
Since both parties of a channel will reach the threshold at the same time (assuming both use the default), there needs to be a negotiation who takes over re-balancing/splicing.

**Comment by kilrau** [comment]
Could you help me think this through? @offerm @sangaman

**Comment by kilrau** [comment]
Assigned to you since you were dealing with similar checks @erkarl

**Comment by sangaman** [comment]
Oh I think this would actually be closed by #850, can you confirm @erkarl ?

**Comment by erkarl** [comment]
@sangaman Yes, it feels pretty related.

@kilrau as of now we're caching the maximum outbound channel balance values (per currency) every 60 seconds. I'm not completely clear on the X% max in/out rule.

**Comment by sangaman** [comment]
Oh actually I think I overlooked that this is supposed to be dealing with rebalancing. That's a complicated issue as far as I know, could you provide more details of what you have in mind @kilrau ?

**Comment by kilrau** [comment]
Sry for the super-late reply.

> caching the maximum outbound channel balance 

Great - I see #850 via [channelBalance](https://github.com/ExchangeUnion/xud/blob/master/lib/service/Service.ts#L120) is already aggregating outbound (local) balances of all channels for one currency! Now we'd need the same for the inbound (remote) balances, to do a sanity check there too - added a [comment](https://github.com/ExchangeUnion/xud/pull/863#issuecomment-478952642).

> I'm not completely clear on the X% max in/out rule.

This issue is about defining thresholds to throw alerts (not in scope of this issue, I just opened #864 for this) when one side of the channel falls below a certain percentage of the channels total (inbound+outbound) capacity. But thanks for questioning this, all channels aggregated doesn't make sense just yet. We are going for a "direct channel" strategy, hence we should throw alerts if one particular channels is unbalanced. These are the proposed cached values which automatically should be updated by :
`<coin>_channel_min_in` (15% of total channel capacity)
`<coin>_channel_min_out` (15% of total channel capacity)

This is what this issue is about: caching these 2 values. General "direct channels" discussion [here](https://github.com/ExchangeUnion/xud/issues/865).

> Oh actually I think I overlooked that this is supposed to be dealing with rebalancing. That's a complicated issue as far as I know, could you provide more details of what you have in mind @kilrau ?

It's just about caching the channelBalance value, not dealing with any rebalancing. That's indeed complicated and for a later stage.

**Comment by kilrau** [comment]
Does it make sense to you to cache these two values as preparation for #864 ? Or would you prefer to do it all at once - also fine! @erkarl

**Comment by erkarl** [comment]
Let's keep this issue for caching these values and deal with the alerts separately.

**Comment by kilrau** [comment]
Agree to skip inbound balance, because no direct lnd api call available, plus dependent on other nodes to open channels to my node anyways. So this issue is about implementing a configurable threshold on aggregated channel outbound balance. @erkarl

**Comment by rsercano** [comment]
> Agree to skip inbound balance, because no direct lnd api call available, plus dependent on other nodes to open channels to my node anyways. So this issue is about implementing a configurable threshold on aggregated channel outbound balance. @erkarl

Hi @kilrau is this still valid, should we cache only outbound balance's configured percentage ?

**Comment by kilrau** [comment]
> Hi @kilrau is this still valid, should we cache only outbound balance's configured percentage ?

LND `0.12` will return [inbound balance with the `channelbalance` call](https://github.com/lightningnetwork/lnd/pull/4512/files). So we should do both. The PR is already merged, you can run lnd master to test.
