### ISSUE TITLE
placeorder enhancements

### ISSUE THREAD

**Issue by offerm** [ExchangeUnion/xud#690]
place order should be enhanced to show all events from order entry until order is entered to the book as ownorder.

we should always present the orderId (even if no own order created).

**Comment by sangaman** [comment]
What specifically do you have in mind besides #609 (failed swap events)? That would then cover all matches, swaps, and failed swaps, plus any remaining quantity that gets added to the order book.

**Comment by offerm** [comment]
This wha I see today:

```
admins-MacBook-Pro-2:xud admin$ xucli buy 0.0025 LTC/BTC 1.105
swapped 0.001 LTC with peer order 62e45ed0-eccb-11e8-a9ee-5d8556a34cdc
remaining 0.0015 LTC entered the order book as 92a14980-eccb-11e8-bb8f-69b162a0c6a5
admins-MacBook-Pro-2:xud admin$ 
```

I don't see the matches (it was matched against 2 orders) and I don't see the failure. I also don't see that the peer orders is removed from the book or that the quantity reduced.

If I do that :

```
admins-MacBook-Pro-2:xud admin$ xucli buy 0.0005 LTC/BTC 1.105
swapped 0.0005 LTC with peer order 94dfeee0-eccb-11e8-a9ee-5d8556a34cdc
admins-MacBook-Pro-2:xud admin$ 
```

I even  don't see my order ID.

**Comment by sangaman** [comment]
The failed swap events are being handled in #609 as I said. Is there a successful match/swap that you expected to see that wasn't there? Or was the 2nd match the failed one?

We can return the orderId even when fully matched, that's not a problem. If we just want to make this issue about returning that orderId, then after this and #609 is solved it sounds like you'll have everything you're looking for.

**Comment by kilrau** [comment]
Moved this to https://github.com/ExchangeUnion/xud/issues/609#issuecomment-444764981, closing here.
