### ISSUE TITLE
ExecuteSwap -> remove peerPubKey

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#694]
This call shouldn't require any peerPubKey since exchanges order gets mapped with XU `oderID` which has all info including the peerPubKey. Remove, not optional.

**Comment by moshababo** [comment]
We recently refactored (#589) the peer orders to be grouped by `peerPubKey`. So this would require scanning all the orders, or maintaining separate map (not a good idea).

**Comment by sangaman** [comment]
I was thinking of scanning all orders, which shouldn't be that bad. Calling `has` on all the peer order maps should be fast, I believe it's a constant time operation.

I was thinking of maybe having `peerpubkey` be an optional parameter to skip the lookup, but maybe it's just a source for possible confusion. Or we could drop peerpubkey from the cli, and keep it on the actual grpc call.

**Comment by kilrau** [comment]
I think best drop it in both places. UX first :1st_place_medal:
