### ISSUE TITLE
webproxy tests: api/v1/nodeinfo/?node_pub_key=foo returns 500

### ISSUE THREAD

**Issue by programarivm** [ExchangeUnion/xud#703]
I just added a ddtd test for the webproxy in https://github.com/ExchangeUnion/xud/pull/700

    node node_modules/.bin/mocha -r ts-node/register test/webproxy/nodeinfo/HttpStatus422.spec.ts

Output obtained:
```
...

[RPC] error: nodePubKey must be specified
Xud.GetNodeInfo 3 INVALID_ARGUMENT: nodePubKey must be specified

...

1) api/v1/nodeinfo
       GET responds with http status 422:

      Uncaught AssertionError: expected 500 to equal 422
      + expected - actual

      -500
      +422
...
```
This is because a `422` status code should be returned when requesting `api/v1/nodeinfo/?node_pub_key=foo`.

**Comment by programarivm** [comment]
Closed. Sorry about this, just updated the url to `http://localhost:${config.webproxy.port}/${endpoint}/foo` instead of `http://localhost:${config.webproxy.port}/${endpoint}/?node_pub_key=foo` and the webproxy responds as expected with `404`.

**Comment by kilrau** [comment]
Great! Would you also be interested in earning XUC for fixing this? @programarivm

**Comment by programarivm** [comment]
Thank you! That sounds really good, the only thing is that I have to manage my time to commit on a regular basis. Let me see if I can fix this one.

**Comment by programarivm** [comment]
I am not too clear about the webproxy returning this:
```
expect(text.code).to.equal(3);
```
I think it makes sense that it'll be transparent to users in a sense that won't inform about the gRPC service being used.

That way, the webproxy response should look like this:
```
{
  "status": 400,
  "text": "Bad Request"
}
```
