### ISSUE TITLE
webproxy tests: api/v1/nodeinfo/foo returns an HTML doc instead of a JSON response

### ISSUE THREAD

**Issue by programarivm** [ExchangeUnion/xud#704]
I just run this test in https://github.com/ExchangeUnion/xud/pull/700:

    node node_modules/.bin/mocha -r ts-node/register test/webproxy/nodeinfo/HttpStatus404.spec.ts

Here is the output obtained:

```
...

1) GET responds with http status 404


  0 passing (788ms)
  1 failing

  1) api/v1/nodeinfo
       GET responds with http status 404:
     Uncaught AssertionError: expected 'text/html; charset=utf-8' to include 'application/json'
...
```

This is because `test/webproxy/nodeinfo/HttpStatus404.spec.ts` expects a JSON object with a gRPC status code `5 NOT_FOUND`:

```
  ...
  it('GET responds with http status 404', (done) => {
    chai.request(`http://localhost:${config.webproxy.port}/${endpoint}/foo`)
                .get('/')
                .then((res: ChaiHttp.Response) => {
                  expect(res.status).to.equal(404);
                  expect(res).to.be.json;
                  let text = JSON.parse(res.text);
                  expect(text.code).to.equal(5);
                  done();
                }, (err: any) => {
                  throw err;
                });
  });
  ...
```

**Comment by kilrau** [comment]
Great! Would you also be interested in earning XUC for fixing this? @programarivm

**Comment by programarivm** [comment]
Thank you! That sounds really good, the only thing is that I have to manage my time to commit on a regular basis. Let me see if I can fix this one.

**Comment by programarivm** [comment]
I am not too clear that the webproxy should return this:
 
```
expect(text.code).to.equal(5);
```
I wonder if it makes sense that it will be transparent to users in a sense that won't inform about the gRPC service being used. 

That way, the webproxy response should look like this:

```
{
  "status": 404,
  "text": "Not Found"
}
```
