### ISSUE TITLE
max channels size vs what we need for trading using real LTC/BTC rate.

### ISSUE THREAD

**Issue by offerm** [ExchangeUnion/xud#711]
Current channel limitation for BTC is ~0.16777 BTC.
Current channel limitation for LTC is ~10.066 LTC (60*~0.16777)

The channels that we currently open on `simnet` environment have capacity of 0.1 BTC and 0.1 LTC. We push half of the capacity to the peer so the channel can be used in both directions. so the capacity of each side is 0.05 BTC

currently 1 litecoin = 0.0081 BTC. 
1 BTC = 123 LTC

If we want to trade 0.001 BTC to LTC we need  0.123 which we don't have since the LTC channel is also small. 

We can easily increase the LTC channel to 10 LTC which will allow trading small BTC amount using the `real` rate. 

However, the main question is about the min/max order size that we would like to support for the LTC/BTC pair.  The current LND limitation limits us to a maximum of 0.08 BTC  (if all conditions are right and we have the needed capacities on one side of the channel).  Once we execute that trade the channel will not be able to be used in that direction any more.

0.08 BTC is ~400 USD which is very small for a trade (I think).

Looks like we need to decide what we want and increase the LND limitation to supports us.

@kilrau

**Comment by kilrau** [comment]
> We can easily increase the LTC channel to 10 LTC which will allow trading small BTC amount using the real rate.
> We can easily increase the LTC channel to 10 LTC which will allow trading small BTC amount using the real rate.

I don't see a problem with that

> Looks like we need to decide what we want and increase the LND limitation to supports us.

I'd go for 1 BTC = 100 LTC, rate and small quantities as default orders on xud1,2,3: <0.01 BTC and <0.1 LTC. I will also add a hint for this to the wiki once that's done, so let me know @offerm

**Comment by offerm** [comment]
Made the suggested change - The channels are now 1.6 BTC and 9.6 LTC. When creating a channel, half is pushed to the peer so each side has 0.8 BTC and 4.8 LTC. 

Assuming the rate is 1 BTC = 100 LTC, we would need 80 LTC to trade the 0.8 BTC. We only have 4.8 LTC. 

Likewise,  0.01 BTC  would trade against 1 LTC. Since we only have 4.8 LTC in the channel this will create a stress very fast.
0.1 LTC would trade against 0.001 BTC - This would hold water since it allows more trades to take place.

So a "normal" order would be `buy` 0.1 LTC/BTC limit 0.01.

Problem: 
0.001 BTC (0.1 LTC)  is ~ 40 USD. This can't be used for exchange to exchange liquidity. 

I see no other solution but to increase the channel capacity to allow channels with up to 100,000 USD capacity. 
What do you think? @kilrau

**Comment by offerm** [comment]
Here is the current order book or LTC/BTC @ bitstamp
<img width="750" alt="screen shot 2018-12-01 at 22 56 37" src="https://user-images.githubusercontent.com/9712754/49332800-6d3a6380-f5bc-11e8-8453-3a39e5b86556.png">

**Comment by kilrau** [comment]
done
