### ISSUE TITLE
[Overview] Reconnect to peer after disconnection (Improvements)

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#721]
Improvement of https://github.com/ExchangeUnion/xud/pull/695:
* #738 - Reconnect after receiving AlreadyConnected disconnecting reason
* #739 - Reconnect only for outgoing peers. No need to reconnect incoming peers.
* Bug: A will not reconnect to B when B is down with xucli shutdown
* Bug: If A and B are connected (both can initiate the connection) and you take B down (kill), start B, wait a minute, Kill again ----> A will not attempt reconnect (reason is not cleared).
* Change max time between reconnections to 5 minutes (@offerm) vs. incremental increasing delay between retries (https://github.com/ExchangeUnion/xud/issues/311#issuecomment-413327480)
* Reset the counter only when we made a good connection.
* ~~The reconnection process will stop after 168 hours for some reason.~~
* ~~(duplicate) handle xucli shutdown (https://github.com/ExchangeUnion/xud/pull/695#issuecomment-443851789)~~

**Comment by erkarl** [comment]
> The reconnection process will stop after 168 hours for some reason.

Looks like this is currently an intentional feature in the code:
https://github.com/ExchangeUnion/xud/blob/master/lib/p2p/Peer.ts#L430

Do we want to remove it?

**Comment by sangaman** [comment]
I think it makes sense to keep it or, at most, extend it. We don't want to keep retrying connections forever. I thought a week was enough time to decide that further attempts to reconnect aren't worth the trouble. Is there any particular reason to lift this limit?

**Comment by kilrau** [comment]
No need to change from my side. Stopping after 168h is exactly how we [defined it before](https://github.com/ExchangeUnion/xud/issues/311#issuecomment-413327480) (604800s = 168h = 7d).

Not sure how this ended up on this list. Feel free to remove @erkarl . Also pls add issue/pr links for everthing you are working on so that we keep an overview here.
