### ISSUE TITLE
[Concept] Handling of trading fees (nomatching mode)

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#723]
Based on our [technical paper](https://github.com/ExchangeUnion/Docs/blob/master/XU-TechnicalPaper.md#38-exchange-earnings), this issue defines handling trading fees for exchanges running `xud` in `nomatching` mode:
* as **taker**, exchanges subtract trading fees from the user account, not in the match itself
Approach a) let the exchange subtract the fee from the swap amount before calling `executeSwap`. Bad: more implementation for exchange
Approach b) `xud` does this. Bad: fee structures of exchanges tend to be complicated and updated regularly. An exchange would have to maintain this.
* as **maker** when orders get propagated to peers the fee has to be added for the taker to see the full order price. Same here:
Approach a) let the exchange add the fee to the order amount. Bad: more implementation for exchange
Approach b) `xud` does this. Bad: fee structures of exchanges tend to be complicated and updated regularly. An exchange would have to maintain this.

**Comment by kilrau** [comment]
Reviving this too. Feedback pls @erkarl @sangaman

**Comment by sangaman** [comment]
I am a little fuzzy on this. I think I would want exchanges to only send to xud the amounts and prices they actually want for swaps, and then subtract fees from the user balances in their own accounting system. What's the shortcoming there?

**Comment by kilrau** [comment]
> What's the shortcoming there?

It needs to be implemented by the exchange.

**Comment by sangaman** [comment]
I'm thinking that either way the exchange would need to take some steps to configure xud to use their preferred fee policy, and in that case they'd be limited by the fee policies that xud offers. I'm still thinking it makes more sense to leave it up to the exchange to pass the exact amounts it wants swapped to xud and figure out their fees on their own. At the least we can wait to see if configuring fees within xud is a feature that's actually requested and get details then.

**Comment by kilrau** [comment]
Ok, agree. Approach a) then - exchange's are responsible to add/subtract fees. This should definitely find it's way into the documentation though. Could you add it in-code now so that Slate will pick this up later? @sangaman

**Comment by kilrau** [comment]
Not relevant anymore. Closing.
