### ISSUE TITLE
xud crash 01 (+order not found bug)

### ISSUE THREAD

**Issue by reliveyy** [ExchangeUnion/xud#729]
[xud.log](https://github.com/ExchangeUnion/xud/files/2648655/xud.log)

[XUD]ExecuteSwap: order_id=727eb1f0-f7e4-11e8-b384-c3957b6da77d, peer_pub_key=03fd337659e99e628d0487e4f87acf93e353db06f754dccc402f2de1b857a319d0, quantity=0.001

1. From the log it told me the order with id `727eb1f0-f7e4-11e8-b384-c3957b6da77d` is not found. But the order existed in the order book. (could reliably reproduce at the time, can't reproduce today)
2. gRPC crash (xud process is still running)

**Comment by reliveyy** [comment]
Tried to swap with another order and `xud` crash again

[xud2.log](https://github.com/ExchangeUnion/xud/files/2648690/xud2.log)

**Comment by reliveyy** [comment]
I installed `xud-simnet` in an vagrant vm (ubuntu/bionic64)
1. Running [the xud-exchange-integration-example](https://github.com/reliveyy/xud-exchange-integration-example)
2. Type `connect <host> <port>` or just `connect` to your `localhost:8886`
3. Type `orderbook` see the full orderbook
4. Type `login alice`
5. Type `buy 0.001` or `sell 0.001` then `xud` crash down and `xucli` cannot get response either.

**Comment by kilrau** [comment]
Updated Yangyang's description above. It's the gRPC crashing/being unresponsive, not `xud` itself. The `xud` process is still running. @moshababo

**Comment by sangaman** [comment]
If an order is missing, you should get a NOT_FOUND grpc error without any crashes. You should be able to verify this by using a fake order id.

When the order is found for the `ExecuteSwap` call, it's removed up front (or only part of it if the quantity specified is less than available). I'm thinking it would be nice to log a message that we've begun the execute swap rpc call tho, I'll open a PR for that.

From the logs, it looks like the swap is failing for reasons unrelated to the rpc layer. I'm seeing `UnknownPaymentHash` messages which I believe can result from an improperly configured swap resolver. Have you verified that you're able to swap with this current setup? From the logs, it looks like all attempted swaps have failed.

**Comment by sangaman** [comment]
Just to be clear, is the `xud` process itself crashing? What's the output from the `xucli` calls?

**Comment by kilrau** [comment]
> Just to be clear, is the `xud` process itself crashing?

No. `xud` process is still up.

>  What's the output from the xucli calls?

`Error: 14 UNAVAILABLE: Connect Failed`

**Comment by kilrau** [comment]
> NOT_FOUND grpc error without any crashes. You should be able to verify this by using a fake order id.

Correct, crashes appear independent from `NOT_FOUND`. We are not seeing the `NOT_FOUND` bug today, so can't reliably tell why they appeared yesterday. Anyhow, let's ignore it for now.

gRPC consistently crashes in different situations. Swap is working. It looks like the gRPC crashes  (`Error: 14 UNAVAILABLE: Connect Failed`) happen independently from `NOT_FOUND` or swap success/failures. Our guess is, that somehow the DNS/network condition plays a role because that's the only unstable and random factor we got here.

**Comment by kilrau** [comment]
closing this
