### ISSUE TITLE
ListOrders `all` flag

### ISSUE THREAD

**Issue by ImmanuelSegol** [ExchangeUnion/xud#748]
If `all` is `true` we return all existing orders, else we return a select number of orders.
We should decide how to select orders to display if -`all=false`:
1) Return by date.
2) Return the 10 best (closest to mid-market price) orders.
3) Some other factor.

@kilrau @sangaman @moshababo Opinions?

**Comment by kilrau** [comment]
2.

**Comment by sangaman** [comment]
I firmly believe that this option doesn't make sense for the `SubscribeAddedOrders` call. The point of that call is to be in sync with orderbook.

What is the reason for wanting this option? I tried to explain in #628 why I don't think performance is a concern.

**Comment by kilrau** [comment]
Sry, just noticed now that the description said 'SubscribeAddedOrders`. Fixed that. This issue is about adding an `all` flag to `GetOrders`/`ListOrders` ([new])(https://github.com/ExchangeUnion/xud/pull/709).
