### ISSUE TITLE
Test failing: should buffer a max buffer length

### ISSUE THREAD

**Issue by ImmanuelSegol** [ExchangeUnion/xud#755]
This [test](https://github.com/ExchangeUnion/xud/blob/25f66fe6e7b65e27ea9d477cc57fc6c4d8426182/test/unit/Parser.spec.ts#L282) fails spontaneously(on Travis local test work consistently), its a bit annoying because it can force you to rerun the test multiple times.

**Comment by kilrau** [comment]
Any approach what to do against it? @moshababo

**Comment by moshababo** [comment]
Problem was solved in previous handshake refactoring.
