### ISSUE TITLE
Peers disconnect

### ISSUE THREAD

**Issue by offerm** [ExchangeUnion/xud#758]
@Moshe @sangaman Looks like the latest master is faulty. After connecting nodes, they are disconnected very fast (15 seconds) while claiming for  `stalling`. This is urgent as xud-simnet is basically not working now

Can be seen between xud1 and xud3.   or any other peer running the latest master and connected to these two. Note that xud2 is using an old master and has no issue.

**Comment by sangaman** [comment]
I've been digging at this for a while and I've narrowed down the issue to the `OrdersPacket` which is always coming up with an incorrect hash. I'm working on a solution now.
