### ISSUE TITLE
`xud-simulation` on build

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#765]
https://github.com/ExchangeUnion/xud-simulation/pulls didn't get merged in yet. This issue is about testing the simulation and making it work on travis build (other suggestions?)

**Comment by kilrau** [comment]
Let us know once you figured out how to do this @reliveyy

**Comment by kilrau** [comment]
In the call you mentioned you are still struggling with this one. Could you provide some details on where you are stuck? Maybe others can help @moshababo

**Comment by moshababo** [comment]
As discussed recently, `xud-simulation` repo should be moved under `xud` repo, to avoid unnecessary complications when testing different branches.
