### ISSUE TITLE
remove order is not being send to peers

### ISSUE THREAD

**Issue by offerm** [ExchangeUnion/xud#767]
My node (A) is connected to xud1,2,3.

listorders shows 2 x sell 2.5@0.0079 (one order from xud1 and one order with xud2).

Using CLI: 
```
xucli buy 2.5 LTC/BTC 0.0079
```
I swap with one of the nodes (xud1 in this case):
```
swapped 2.5 LTC with peer order 29dff850-07c0-11e9-a5e9-eba6222927d0
```
Post swap the sell order is replaced by the bot on xud1 and my node shows again 2 sell orders.

checking `xucli getorders` on xud3 shows 3 x  sell 2.5@0.0079 (one from xud3 and TWO from xud1).

The log does not show any remove order from xud1.

Very easy to reproduce.

**Comment by sangaman** [comment]
Looks like this is a similar bug/cause as #758, where superfluous fields are being hashed by the sender for the Order Invalidation packet and then failing validation on the receiver's end, thus the orders are not being invalidated by the receiver.

**Comment by offerm** [comment]
Not solved. 
Now, not only that the executed order is not being removed from peers the counter order is also added with a price of zero.

<img width="898" alt="screen shot 2018-12-26 at 8 14 40" src="https://user-images.githubusercontent.com/9712754/50434568-5ac6f780-08e6-11e9-9d88-b2b0ed590c7c.png">

**Comment by sangaman** [comment]
Looks like this is the key change that needed to happen in addition to my fix above, OrderInvalidationPackets were being converted into the wrong type of packet. https://github.com/ExchangeUnion/xud/pull/774/commits/27e289bff72ca0c137430e843d01082bfa7ebd3d

Thanks offer for finding this.
