### ISSUE TITLE
gRPC enhancement for Raiden

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#792]
This is a placeholder

**Comment by kilrau** [comment]
Let's start filling in things here @sangaman @offerm

**Comment by offerm** [comment]
Don't remember saying that we need gRPC to connect to Raiden. Raiden is [now] using gRPC to connect to the resolver. 

XUD should connect to raiden via HTTP. Easy API.

**Comment by sangaman** [comment]
Yes Raiden uses a REST HTTP API. We already have a decent amount of code for communicating with Raiden in RaidenClient.ts. I think we can probably close this as there are other issues tracking Raiden progress.

**Comment by kilrau** [comment]
If I recall correctly, by this we meant to enhance `xud`'s gRPC to support everything we need for raiden. Anyhow, `xud`'s gRPC should be generic enough to support raiden, goes without saying, so closing.
