### ISSUE TITLE
Switch to "hodl invoice"

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#798]
https://github.com/lightningnetwork/lnd/pull/2022/ will be the new standard and our https://github.com/lightningnetwork/lnd/pull/1820 won't get merged. Hence we should switch at some point. We'll definitely wait for 2022 to be in master tho.

**Comment by kilrau** [comment]
Still not merged, moving to next milestone.

**Comment by kilrau** [comment]
Merged.

**Comment by kilrau** [comment]
I think we can tackle this one
* once 0.6 released
* if we are done with the [raiden simnet setup](https://github.com/ExchangeUnion/xud/issues/866)
* if we are blocked by [raiden team decision on SHA256](https://github.com/ExchangeUnion/xud/issues/870)

**Comment by sangaman** [comment]
I will take a look at this before our call to get an idea of how big a lift this change will be for us.

**Comment by sangaman** [comment]
Here's a quick overview of what needs to happen for xud to support hold invoices:

- We need to start using invoices which we're not currently. We'd still generate the hash and preimage and call `AddHoldInvoice` with the has. I'm thinking we can actually send the swap request packet and call `AddHoldInvoice` in parallel to eliminate an extra step of waiting.
- After the invoice is created call `SubscribeSingleInvoice` to be notified when someone tries to pay it.
- Call `CancelInvoice` and end the subscription if the swap fails or times out.
- When someone tries to pay as reported by `SubscribeSingleInvoice`, do our existing resolve hash routine and call `SettleInvoice` once we have the preimage.
- Lnd needs to be built with the `invoicesrpc` flag to enable the hold invoices functionality.

**Comment by kilrau** [comment]
You can work with an official release now: https://github.com/lightningnetwork/lnd/releases/tag/v0.6-beta @sangaman ⚡️
