### ISSUE TITLE
Fresh install - problem with lndrpc.proto

### ISSUE THREAD

**Issue by offerm** [ExchangeUnion/xud#80]
Installed xud for the first time. Tried to follow the instructions  on [https://github.com/ExchangeUnion/xud](url):

Started xud from bin directory without a config file resulted with:

> 2018-5-19 20:53:30 error: TypeError: Cannot read property 'ns' of null
    at Object.load (/home/offerm/github/xud/node_modules/grpc/index.js:146:29)
    at new LndClient (/home/offerm/github/xud/dist/lib/lndclient/LndClient.js:31:52)
    at Xud.<anonymous> (/home/offerm/github/xud/dist/lib/Xud.js:49:34)
    at Generator.next (<anonymous>)
    at fulfilled (/home/offerm/github/xud/dist/lib/Xud.js:4:58)
    at <anonymous>

Had to create a config file and change 

> rpcprotopath = "lndrpc.proto"

to

> rpcprotopath = "../lndrpc.proto"

**Comment by michael1011** [comment]
You are right. This is an issue with the readme. `xud` should either be run in the root directory of the repository or with `npm start`.

**Comment by offerm** [comment]
Yes. Starting from XUDHOME with npm is OK.

If one goes by the readme and fix the lndrpc manually she will get the following error  on getinfo:

> 2018-5-19 22:12:12 debug: RPC server request: {"method":"getInfo","id":1,"jsonrpc":"2.0"}
E0519 22:12:12.839404574  114166 ssl_transport_security.cc:190] ssl_info_callback: error occured.

> E0519 22:12:12.839457173  114166 ssl_transport_security.cc:979] Handshake failed with fatal error SSL_ERROR_SSL: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure.
> 2018-5-19 22:12:12 error: RPC server request (1) error undefined
> E0519 22:12:13.841028264  114166 ssl_transport_security.cc:190] ssl_info_callback: error occured.
> 

Best would be if xud will not be sensitive for current wd.

**Comment by sangaman** [comment]
Thanks @offerm, this is something we've known about but haven't fixed yet. We definitely want to be able to run `xud` from any directory. I think now that we're using `dotenv`, probably the best approach is to move the proto file path from the config file to the `.env` file and make it an absolute path.

**Comment by offerm** [comment]
Thanks @sangaman, as a minimum I think the setup instructions should be changed.

**Comment by sangaman** [comment]
Resolved by #85.
