### ISSUE TITLE
Improve swaps error handling

### ISSUE THREAD

**Issue by moshababo** [ExchangeUnion/xud#807]
* Add `SwapFailures` to `PlaceOrderResult`. Otherwise we're just getting the final results, but have no idea about swap attempts which failed. (@sangaman @kilrau please verify that we want this)

* Propagate meaningful errors from `Swaps.executeSwap` (taker side), and log them once in the higher layer (`OrderBook.PlaceOrder`). Same for the maker side. 

* Calling `Swaps.getRoutes` and it's underlying `lnd.queryRoutes` throws exception on failure (when there's no channel, channel isn't active, channel local balance isn't sufficient, etc.). At the moment it's not handled properly and `lnd`s internal errors are returned ("target not found", "unable to find a path to destination").

**Comment by kilrau** [comment]
> * Add `SwapFailures` to `PlaceOrderResult`. Otherwise we're just getting the final results, but have no idea about swap attempts which failed. (@sangaman @kilrau please verify that we want this)

Not sure. Is it inconsistent to have swap failures in the async call, but not in the sync version? I'd rather just write these in the db (please confirm that we already do this @moshababo ). Waiting for @sangaman opinion

**Comment by sangaman** [comment]
For the first bullet point, I'm not really sure whether it's needed. Originally we were OK with the current behavior of only returning the failures for the asynchronous call, is there a new reason why we would change this? I personally don't have much of a preference but I wouldn't want to change something unless there's a reason.

For the other two bullet points I think is improved slightly by #806, but I've realized myself that we could have neater exceptions from the `executeSwap` method.

**Comment by kilrau** [comment]
Thx Daniel! Swap failures are already recorded in the db, correct?

**Comment by sangaman** [comment]
Yes correct, the only ones we don't record are the ones proposed to us but which be reject (like if the order is no longer available). We save all requested swaps and all accepted swaps whether the fail or succed.

**Comment by kilrau** [comment]
Can you take out the first bullet point then if you agree? @moshababo

**Comment by moshababo** [comment]
I thought it would be good to have it for the sake of UX and consistency with the async version. If i'm using `PlaceOrderSync`, I don't get this info, and having it saved in the DB doesn't help me to understand from the response why my order didn't trigger a swap.

**Comment by moshababo** [comment]
Another thing: we provide `subscribeSwaps` RPC endpoint, which is used mainly to stream maker swaps (swaps which were initiated by a peer). It doesn't stream swap failures - so there's no way to know about them, besides looking in the logs. I think it beneficial to support it, to allow clients to easily monitor issues, and to react to them. It's basically the other side of adding the swap failures support to `PlaceOrderSync`. 
What do you think about it?

In addition, from looking at the code, I don't see that we save swap failures to the database. 
We save trades, whether they are internal matches or swaps. But if it's a swap, we save it only if it succeeded. There's also no way to differ between the swap procedure outcomes (success/failure) in the table structure. @sangaman am I missing something?

**Comment by moshababo** [comment]
Another thing: we provide `subscribeSwaps` RPC endpoint, which is used mainly to stream maker swaps (swaps which were initiated by a peer). It doesn't stream swap failures - so there's no way to know about them, besides looking in the logs. I think it beneficial to support it, to allow clients to easily monitor issues, and to react to them. It's basically the other side of adding the swap failures support to `PlaceOrderSync`. 
What do you think about it?

**Comment by sangaman** [comment]
> Another thing: we provide `subscribeSwaps` RPC endpoint, which is used mainly to stream maker swaps (swaps which were initiated by a peer). It doesn't stream swap failures - so there's no way to know about them, besides looking in the logs. I think it beneficial to support it, to allow clients to easily monitor issues, and to react to them. It's basically the other side of adding the swap failures support to `PlaceOrderSync`.
> What do you think about it?

We should know about failures in swaps that we initiate in the response to the `PlaceOrder` or `ExecuteSwap` calls. I see what you're saying, though, about wanting to know if swaps that we don't initiate are failing, right now the only way to know is to look at the logs like you said.

I'd be OK with addressing this in a separate issue. Do you want to open it? And do you think it might make sense to deal with this in a separate `SubscribeSwapFailures` call?

**Comment by kilrau** [comment]
I also believe that would be more than great to have and should actually have come from me. Thanks for this @moshababo ! From a product point of view, I don't see a great benefit from having a separate `SubscribeSwapFailures` call, also we don't have this concept of having failures/errors in a separate call so far as far as I'm aware. But there might be a technical reason to keep swap failures separate (e.g. spamming with failure events; so exchange can choose to discard this call if it gets spammed). If not, I'd prefer to have it in the same call. I went ahead and opened [the issue](https://github.com/ExchangeUnion/xud/issues/817). Assigned it to you @sangaman since you are the one who can do it the fastest 💨
