### ISSUE TITLE
Upgrade vulnerable dependencies

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#811]
https://github.com/ExchangeUnion/xud/network/alerts

**Comment by kilrau** [comment]
The moment I opened this I just saw your https://github.com/ExchangeUnion/xud/tree/resolve-alerts branch @sangaman  👍 

Close this when merging.

**Comment by sangaman** [comment]
Thanks, I finally got all the new dependencies straightened out (also had to update https://github.com/ExchangeUnion/grpc-dynamic-gateway) by identifying a bug in the `grpc-tools` code, but fortunately the maintainer of that project was responsive and the fix was merged and published same day.
