### ISSUE TITLE
Add SwapFailures to `subscribeSwaps` RPC

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#817]
As discussed in [#807](https://github.com/ExchangeUnion/xud/issues/807#issuecomment-467909052) the `subscribeSwaps` RPC endpoint (used to stream swaps which were initiated by a peer) doesn't stream swap failures - so there's no way to know about them, besides looking in the logs. We should add the same `SwapFailure` events here too. It's basically the other side of adding the swap failures support to `PlaceOrderSync`.

**Comment by sangaman** [comment]
My thinking in separating this into a separate call is its a different message type and the action one would take in case of a successful swap and a failed swap are very different. Also I can see cases where one isn't interested in the failed swaps, or might *only* be interested in failed swaps (for example, an admin monitoring tool). Thoughts @moshababo?

**Comment by moshababo** [comment]
@sangaman sounds fine to me. We should include support for the `include_taker` option, same as for the current `subscribeSwaps`.
