### ISSUE TITLE
Simnet: mempool based mining & (one-time) reset

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#823]

**Comment by kilrau** [comment]
More details needed? @offerm

**Comment by offerm** [comment]
How often should we mine when there is nothing on the mem-pool?

This is important as new blocks are used to manage the lifetime of pending HTLCs and channels.

**Comment by kilrau** [comment]
A recommendation would be good :)

Since HTLC's expire usually in a matter of days even for multiple hops on lightning, maybe:
* 1/4h for BTC
* 1/h for LTC
* Not sure about raiden

**Comment by offerm** [comment]
Suggest to close the for now. We mine a new BTC, LTC, raiden every 2 minutes now. 
Don't think we should complucate it. 

Raiden and LND are using blocks as a timer so we can't do based on transactions in mempool only

**Comment by kilrau** [comment]
Closing in favor of https://github.com/ExchangeUnion/xud/issues/895
