### ISSUE TITLE
Add minimum viable RaidenClient REST API integration

### ISSUE THREAD

**Issue by erkarl** [ExchangeUnion/xud#826]
Offshoot from https://github.com/ExchangeUnion/xud/issues/797

## Base Client requirements
- [x] getInfo (for general sanity checks before attempting the swap)
  - [x] isConnected
  - [x] getAddress
- [x] sendPayment (for swaps)
- [x] getChannels (for xucli channelbalance)

### Everything else
- open channel
- close channel
- depositing to channel
- join token network
- bootstrap token network
- register token
- check if token registered

Everything else classifies as nice to have functionality since we do the same manual channel management for Lightning implementations as well. Ultimately, xud should abstract channel management away from the end user, but it is not required for ERC20 <-> BTC/LTC swaps.

**Comment by kilrau** [comment]
Added feedback directly above.
