### ISSUE TITLE
xud-simnet instability

### ISSUE THREAD

**Issue by offerm** [ExchangeUnion/xud#834]
@sangaman 

the test1,2,3 servers are now running fine. Had to deal with the bot to make it working.

One thing that I noticed is that [lndltc] and [lndBTC] should change to [lnd.LTC] and  [lnd.BTC] and that if you use [lnd.ltc] or [lnd.btc] the system will not error but will not work properly. 

While the test servers looks "fine" there are some issues:

On a remote machine (my laptop), after fetch+pull of xud-simnet I have these problems:
1. xud-simnet-start looks good but xud-simnet stop does not stop the xud process
2. xud fail to connect with the seed servers. @moshababo 

Can you please check it? 

Once this works we need to check that opening a channel is working and that swap is working.

**Comment by sangaman** [comment]
I'm looking into it now.

**Comment by offerm** [comment]
> Just an update here, the `xud-simnet-stop` script wasn't identifying the xud process correctly which Offer has fixed.
> 
> The issue with the failed connections is only happening on Offer's machine currently, working elsewhere. We haven't gotten to the bottom of yet but his machine never receives the `SessionInit` packet even though the seed nodes attempt to send it.

Not only on my machine. Also see this on a cloud machine.
Moreover, this problem may lead to an xud crash. 
@moshababo

**Comment by sangaman** [comment]
@offerm Do you want to see if #836 helps with the connection issues you're seeing? I came across it while trying to figure this issue out, although I'm not sure if it's related. It may at least prevent the crashes.

**Comment by offerm** [comment]
So, I managed to improved the situation by upgrading node to version 10.15.3.

Now, I manage to connect to test1 and test2 but test3 does not complete the handshake and disconnect after 15 seconds. 
I see the same problem also with my cloud xud

If you think #836 can help here - please merge it and we will see

**Comment by sangaman** [comment]
Gotcha, do you happen to know which version of node you were on before?

I merged the PR and things are looking stable on my end with regard to the seed nodes, if you can confirm on your end I think we can close this.

**Comment by kilrau** [comment]
Gave this a quick test:
* `xud-simnet-stop`
* `xud-simnet-start` (successfully updated to latest master & synced to chain)
* ends up in 

```
~/xud-simnet$ xud-simnet-start
starting all processes
btcd started
ltcd started
lndbtc started
lndltc started
xud started
sync lndbtc to chain
.
lndbtc synced to chain
sync lndltc to chain
.
lndltc synced to chain
xud didn't start properly. No litecoin support
```

I guess I need to start from scratch?

**Comment by sangaman** [comment]
Did you do `git pull` in the `xud-simnet` directory first? If you're still getting that error I'd try dropping your `xud-wd` directory and trying again.

**Comment by offerm** [comment]
Run bash -x xud-sumnet-start and see where it fails

**Comment by kilrau** [comment]
Did the manual `git pull` before `xud-simnet-start` , that updated the scripts
```
 scripts/xud-simnet-channels | 4 ++--
 scripts/xud-simnet-start    | 3 ++-
 scripts/xud-simnet-stop     | 4 ++--
 3 files changed, 6 insertions(+), 5 deletions(-)
```
and fixed it. Connection working now. Swaps not working due to `getRoutes` error:
```
17/03/2019 14:00:33.350 [SWAPS] debug: error calling getRoutes for LTC to 02f5e0324909bdb635d4d6a50aa07c517db5$
17/03/2019 14:00:33.350 [ORDERBOOK] error: swap between orders fb2e4cb0-48a5-11e9-a963-ab3383ef58a5 & b3f83160$
17/03/2019 14:00:33.350 [ORDERBOOK] warn: swap for 0.25 failed during order matching due to UnexpectedLndError$
17/03/2019 14:00:33.350 [ORDERBOOK] debug: repeating matching routine for b3f83160-48f7-11e9-81fd-8f4506cc7070$
17/03/2019 14:00:33.350 [ORDERBOOK] debug: reduced order fb2e4cb0-48a5-11e9-a963-ab3383ef58a5 by 0.25 quantity$
17/03/2019 14:00:33.350 [ORDERBOOK] debug: matched with peer 03fd337659e99e628d0487e4f87acf93e353db06f754dccc4$
17/03/2019 14:00:33.351 [SWAPS] debug: error calling getRoutes for LTC to 02f5e0324909bdb635d4d6a50aa07c517db5$
17/03/2019 14:00:33.351 [ORDERBOOK] error: swap between orders fb2e4cb0-48a5-11e9-a963-ab3383ef58a5 & b3f83160$
```

**Comment by sangaman** [comment]
I think we can close this issue then?

**Comment by offerm** [comment]
Once swap is back, yes

**Comment by sangaman** [comment]
Closing this as swaps are working for me currently on master and I think the original issues are addressed as well.
