### ISSUE TITLE
Set log level via API

### ISSUE THREAD

**Issue by sangaman** [ExchangeUnion/xud#835]
It would be helpful for debugging purposes to be able to change the logging level within xud without having to restart it. We should be able to create an API call that does this, with a call that uses an enum parameter for the available log levels.

**Comment by erkarl** [comment]
This would be an useful feature for debugging production environments. If I'm not mistaken the current solution would be to stop the server -> adjust the log verbosity level -> start the server?

**Comment by sangaman** [comment]
Currently yes that's what's needed to change the log level, which can be inconvenient/time-consuming.

**Comment by engwarrior** [comment]
Pls provide estimate for this task.

**Comment by kilrau** [comment]
Would you be interested in this one? @rsercano

**Comment by rsercano** [comment]
Dynamically changing winston's log level is a mess, I'm open to suggestions at this point @sangaman

**Comment by sangaman** [comment]
I think I found a way to do it, I'll open a PR soon.
