### ISSUE TITLE
seed nodes keep disconnecting

### ISSUE THREAD

**Issue by offerm** [ExchangeUnion/xud#839]
the connection to the seed nodes is not stable.

log attached

[xud.log](https://github.com/ExchangeUnion/xud/files/2976279/xud.log)

**Comment by sangaman** [comment]
It looks like your node is sending `GetNodes` requests but not getting any responses. I don't know why yet but I'll look into it further.

**Comment by offerm** [comment]
@sangaman you are right. My node is sending getNodes request which is not being responded.

The getNodes packet is ignored due to a check in lib/p2p/Peer.ts:619 - isPacketSolicited(packet)

If this returns false the packet will be ignored and will lead to connection failure. 

Now, isPacketSolicited(packet) returns false if the connection is not market `open`.  Marking the connection as `open` is done only after the server sends `getNodes`.

So,  if A connects to B and B receives a `getNodes` from A before  B issues a `getNodes` itself the packet from A will be ignored and disconnected will happen. 

The handshake code between A and B is not symmetric.
A sends `sessionInit`
B sends `ack`
A wait for the `ack` from A
A compute encryption key (CPU)
B sends `sessionInit`
A sends 'ack`
B wait for the `ack` from A
**B compute encryption key (CPU)**

While B is doing the last 2 operations A is already sending `getNodes` to B. 

The new Encryption code increases the chance that the `getNodes` from A will arrive at B  before B marks the connection as `open`

**Comment by sangaman** [comment]
Awesome, thanks for this analysis that makes a lot of sense. I should be able to come up with a fix tonight.
