### ISSUE TITLE
Enable support for WETH

### ISSUE THREAD

**Issue by erkarl** [ExchangeUnion/xud#846]
In order to support `WETH` and other tokens/currencies the system needs slight modifications in various places. Below is a nondefinitive list of TODOs:

- refactor `Swaps.calculateSwapAmounts` to use configurable amount of subunits per token for each currency - https://github.com/ExchangeUnion/xud/blob/master/lib/swaps/Swaps.ts#L82 - PR: https://github.com/ExchangeUnion/xud/pull/860
- require `OrderBook.addCurrency` to specify ERC20 contract address when adding currencies linked to Raiden - https://github.com/ExchangeUnion/xud/blob/master/lib/orderbook/OrderBook.ts#L203 - PR: https://github.com/ExchangeUnion/xud/pull/855
- make `WETH` enabled by default when initializing a new database - https://github.com/ExchangeUnion/xud/blob/master/lib/db/DB.ts#L89 - PR: https://github.com/ExchangeUnion/xud/pull/856
- modify `RaidenClient.getRoutes` and `getHeight` to be compatible with current swaps implementation - PR: https://github.com/ExchangeUnion/xud/pull/861

Not needed for initial WETH<->BTC/LTC swaps:
- make `Service.channelBalance` return channelbalance for all the registered currencies (currently only works for BTC, LTC and WETH) - https://github.com/ExchangeUnion/xud/blob/master/lib/service/Service.ts#L126

**Comment by kilrau** [comment]
As far as I understand we can wait for [raiden or someone else to officially deploy](https://raiden-network.readthedocs.io/en/stable/onboarding.html?highlight=tokennetwork) the `TokenNetwork` contracts for all these ERC20s. Us doing all this work is not the way to go I believe. I'm fine with with 1.0 having `WETH` only if this didn't happen by then.

But `xud`-internals should be prepared to handle ERC20 generic and not tied to `WETH`, that's clear I believe.

**Comment by erkarl** [comment]
Just to clarify - this issue is about having the internals of xud ready to support additional tokens/currencies.

Example TODO: https://github.com/ExchangeUnion/xud/blob/master/lib/service/Service.ts#L126

**Comment by kilrau** [comment]
Ok great! Maybe collect these TODO's here?

**Comment by erkarl** [comment]
Updated the original post and title. Still wip, but it's a good starting point.
