### ISSUE TITLE
Unit tests: MatchingEngine

### ISSUE THREAD

**Issue by moshababo** [ExchangeUnion/xud#86]
Should add unit tests for MatchingEngine class, for the following static methods:
* getMatchingQuantity (some old tests which don't cover partial quantities scenarios already exists)
* splitOrderByQuantity
* match

**Comment by kilrau** [comment]
If @michael1011 s tests are enough for now, pls close @moshababo

**Comment by moshababo** [comment]
Yes they are enough for now. We'll probably reopen this in a later on.
