### ISSUE TITLE
Integrate Raiden into Simnet 

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#866]

**Comment by kilrau** [comment]
@erkarl preferred to help out if you are busy with your other issues

**Comment by kilrau** [comment]
Offer made some progress on this in the past days. Almost working, main blocker: https://github.com/ExchangeUnion/xud/issues/892

**Comment by offerm** [comment]
This is almost done. 
Not usable due to #892  - my feeling is that I will need to rebuild the chain.

**Comment by kilrau** [comment]
I believe this is done, if so pls close @offerm

**Comment by offerm** [comment]
@kilrau still missing - Raiden channel opening and order placement (bot)  for WETH/BTC

**Comment by kilrau** [comment]
Ok, let's do that

**Comment by kilrau** [comment]
Ongoing. Current problems:
a) retry for SanitySwap (WETH) (@sangaman )
b) not passing secretHash for a WETH/BTC swap (@erkarl ).

**Comment by offerm** [comment]
The Sanity swap for WETH currently fails (no resolver end point). Raiden will provide the failure to XUD after 50-60 blocks (30-60 minutes). XUD retries the WETH swap every few minutes. As a result Raiden will have a huge list of pending-failed payments.

To deal with that I'm try to provide the response back to XUD much faster. Working on a raiden PR for it (if I will make it).

Once I have this I would need the #830 support. Which looks like blocked by the LND invoice.
