### ISSUE TITLE
sha256 <-> keccak256 problem

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#870]
Terms:
- `p_i = MVHz...`
- `hash_lnd = sha256(p_i)`
- `hash_raiden = keccak(p_i)`
- Swap: Taker -> lightning -> Maker, Maker -> Raiden -> Taker

The problem can be described using two scenarios:
1. According to todays swap protocol (taker creating preimage `p_i`, sending `hash_lnd` to maker): maker creates raiden-payment back with `hash_lnd`: taker obviously can't unlock raiden-payment  because it corresponds to a totally different preimage. Conclusion: not an option
2. New swap protocol: Taker (or maker, doesn't matter) creates both, `hash_lnd` & `hash_raiden`. Maker uses `hash_raiden` hash to create raiden-payment back to Taker. Problem: Maker has no option to verify `hash_lnd` & `hash_raiden` hash correspond to the same preimage. Ergo a malicious taker could have used two different preimages to create these and in that way steal makers funds. Conclusion: not an option

Two solution approaches:
1. Central (but cyrptographically blindfolded, like watchtower) party creating both `p_i`, `hash_lnd`, `hash_raiden`. Evaluation: very complicated
2. Make Raiden SHA256 compatible. This anyways is currently being discussed within the raiden team since ETH 2.0, [among others will add SHA256 support](https://ethresear.ch/t/multihashing-in-ethereum-2-0/4745). Evaluation: sounds like the best and most reasonable option so far though. Now we should evaluate if we a) want to work on an opt-in SHA256 contract (compare precomiled 0x0000000000000000000000000000000000000002 that was used e.g. in https://medium.com/coblox/connect-all-the-blockchains-atomic-swap-78b38fff42e) or b) want to wait for it to be added by the Raiden team. If & Timing: unsure

**Comment by michael1011** [comment]
My two cents: I would go for option 2 and try to cooperate with the Raiden team as much as possible. If they decide that they want to support SHA256 we could support them actively with that because we really need it for our swaps.

Option 1) doesn't sound like a good idea since it requires a certain degree of trust and introduces a single point of failure to the system.

**Comment by sangaman** [comment]
Good point on why using two hashes won't work. And I also feel that option 1 would be quite challenging to implement and not trustless (although a creative solution).

Making Raiden SHA256 compatible seems like the easiest and most sustainable path for sure. I figure it can be added as an "alternative" rhash value or an as an option to use SHA256 for the hash function.

**Comment by erkarl** [comment]
Thanks for bringing this up as I didn't fully grasp after yesterday's call how we're going to solve this. Do we have an idea how much effort 2.A) would be?

**Comment by kilrau** [comment]
> Thanks for bringing this up as I didn't fully grasp after yesterday's call how we're going to solve this. Do we have an idea how much effort 2.A) would be?

@offerm How could this look like & what's your effort estimation on this?

**Comment by kilrau** [comment]
Update: we are waiting for a decision on implementation details from the raiden team

**Comment by kilrau** [comment]
Closing this issue since we decided for option 2. Implementation details can be tracked here: https://github.com/ExchangeUnion/xud/issues/882
