### ISSUE TITLE
Show channelbalance for all the registered currencies

### ISSUE THREAD

**Issue by erkarl** [ExchangeUnion/xud#879]
It currently only works for BTC, LTC and WETH - https://github.com/ExchangeUnion/xud/blob/master/lib/service/Service.ts#L126

**Comment by ImmanuelSegol** [comment]
@erkarl Is this my issue or yours? don't want to do double work.

**Comment by erkarl** [comment]
@ImmanuelSegol sorry - I fixed this issue as a side effect of doing https://github.com/ExchangeUnion/xud/pull/918
