### ISSUE TITLE
xud crash on raiden start

### ISSUE THREAD

**Issue by offerm** [ExchangeUnion/xud#884]
xud is configured to use raiden

Starting xud when raiden is down.

xucli getinfo:
```
  "raiden": {
    "error": "connect ECONNREFUSED 127.0.0.1:5001",
    "address": "",
    "channels": 0,
    "version": ""
  }
```

starting raiden causes xud to crash

```
xud@xud-test-2:~$ xucli getinfo
Error: 14 UNAVAILABLE: Connect Failed
```
log shows nothing 
If you start raiden befor xud there is no problem.

Also if raiden stops - xud don't detect it. Not sure if this is a problem or not.

**Comment by kilrau** [comment]
> Also if raiden stops - xud don't detect it. Not sure if this is a problem or not.

It is. Connection to the raiden client should have a pulled heartbeat, [just like lnd](https://github.com/ExchangeUnion/xud/pull/762).

**Comment by erkarl** [comment]
I believe this is fixed in: https://github.com/ExchangeUnion/xud/pull/876 - could you confirm you still have the bug with that patch applied?

**Comment by erkarl** [comment]
Testing this without connected peers I get the following output (working as intended):
```
[1] 12/04/2019 15:43:26.927 [RAIDEN] error: could not verify connection to raiden at localhost:5001, retrying in 5000 ms
[1] 12/04/2019 15:43:31.927 [RAIDEN] info: trying to verify connection to raiden with uri: localhost:5001
[1] 12/04/2019 15:43:31.932 [RAIDEN] info: RaidenClient status: ConnectionVerified
```

**Comment by sangaman** [comment]
Yes this definitely looks like the same issue as #876.

**Comment by sangaman** [comment]
Should be fixed in the latest master, we can close this if we get confirmation that the crash doesn't happen any more.

**Comment by kilrau** [comment]
@offerm

**Comment by offerm** [comment]
Yes, looks OK now. Thanks.
