### ISSUE TITLE
[Concept] Torrent blockchain for full nodes

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#890]
Includes:
* bitcoin testnet3+mainnet (Work with @rootzoll: https://github.com/rootzoll/raspiblitz/tree/v1.2/home.admin/assets)
* litecoin testnet+mainnet (Work with @rootzoll: https://github.com/rootzoll/raspiblitz/tree/v1.2/home.admin/assets)
* eth geth ropsten/rinkeby+mainnet (research needed)

Find a way to automatically update torrents on a regular base and distribute new torrent file to seeders.

**Comment by kilrau** [comment]
@reliveyy will do some research on which torrent clients to use with the alpine linux image. I could find two options:

deluge:
* https://pkgs.alpinelinux.org/package/edge/testing/x86_64/deluge
* https://deluge-torrent.org/

rTorrent
* https://pkgs.alpinelinux.org/package/edge/community/x86_64/rtorrent
* https://github.com/rakshasa/rtorrent/wiki
* https://github.com/StayPirate/alpine-rtorrent

I would also want to make each node seeding the blockchains on default when they are online. We can add an option to switch that off. Objections?

Ideas on details how to automatically create an updated blockchain torrent in regular intervals and how to distribute this one to seeders of the older torrent? @erkarl @reliveyy

**Comment by erkarl** [comment]
Conclusion from the call: don't do it since we're switching to Neutrino.
