### ISSUE TITLE
Fix geth private chain block lookup bug

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#892]
This issue is to track progress on fixing raiden to not lookup old blocks to hit a snag with geth: https://github.com/raiden-network/raiden/issues/3673#issuecomment-482952562

Fixing geth is the long term solution (issue opened, see in raiden issue above), but this could take some time.

**Comment by offerm** [comment]
Also relevant https://github.com/ethereum/go-ethereum/issues/19146

**Comment by offerm** [comment]
I created a patch for raiden (as part of the xud-raiden) PR that ignores the missing logs.

With this patch raiden can start but it can't really be used.

**Comment by kilrau** [comment]
Ok. Do we know WHY raiden needs these events?

**Comment by LefterisJP** [comment]
Yes, raiden needs blockchain events because this is how it learns about what has happened in the blockchain. This is the "typical ethereum" way of dealing with blockchain. You query old events to learn what happened, and you poll an event to reach to things happening now.

**Comment by kilrau** [comment]
That makes sense. We'll go an figure out how to fix this problem with missing historic events in geth. Thanks @LefterisJP

**Comment by kilrau** [comment]
geth `eth_getLogs` fixed on latest master
