### ISSUE TITLE
Trading new ERC20 token requires restart

### ISSUE THREAD

**Issue by erkarl** [ExchangeUnion/xud#898]
Currently, when adding a new ERC20 token requires a restart because we're associating the swap client (Raiden) with currencies while starting up xud. Currencies that are added at runtime are not immediately associated with the swap client. That will result in the following error message in case of buy/sell orders:
```
Error: 2 UNKNOWN: unable to find swap client for currency WETH
```

**Comment by kilrau** [comment]
Is that why @offerm put a restart into the simnet script?

```
Pair WETH/BTC added
Restaring xud
Ready!
```

If so, let's fix both!
