### ISSUE TITLE
Change error message when trying to trade currencies with no channels

### ISSUE THREAD

**Issue by erkarl** [ExchangeUnion/xud#899]
With the recent addition of sanity checks before placing own orders to orderbook we're verifying that we have sufficient outbound balance.

When the user has no channels for that currency we're currently showing an error:
```
Error: 2 UNKNOWN: WETH does not have sufficient outbound balance of: 100000000000000000
```

@offerm and @kilrau pointed out that this message is misleading. This issue is about changing the error message to:
`<CURRENCY> doesn't have open channels.` 
in the event of 0 open channels.

**Comment by offerm** [comment]
@erkarl also we better use the decimals and the  show the amount as 1.0 and not 100000000000000000

**Comment by kilrau** [comment]
Moved `post-1.0.0`, not important enough
