### ISSUE TITLE
Combine `SubscribeAddedOrders` and `SubscribeRemovedOrders` to ensure correct order

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#903]

**Comment by sangaman** [comment]
https://stackoverflow.com/questions/48890049/best-approach-to-stream-multiple-types-with-grpc has some good input on this sort of issue from a google engineer. The recommended approach is to have separate calls for separate message types where ordering is not a concern, but a combined call where ordering is a concern. After combining the two calls described here, we'll be consistent with that approach.
