### ISSUE TITLE
[xud simulation] Implement more tests (p2p)

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#919]
P2P:

- [ ] Wrong identity: Alice connects to Bob expecting a random public key. Bob should reject the connection due to auth invalid target.

- [ ] Banning: If Alice bans Bob, connection attempts from both directions should fail.

- [ ] Unbanning: If Alice unbanned Bob, connection attempts from both directions should succeed.

- [ ] Duplicate connection: If Alice and Bob are already connected, connection attempts from both directions should get blocked.

**Comment by moshababo** [comment]
Already implemented by #916. Feel free to add more scenarios or to close this.

**Comment by kilrau** [comment]
Telepathy, I didn't see the PR. Added closing statement to the PR description. Good stuff!
