### ISSUE TITLE
Deprecated dependencies

### ISSUE THREAD

**Issue by ImmanuelSegol** [ExchangeUnion/xud#930]
`(node:8800) [DEP0091] DeprecationWarning: crypto.DEFAULT_ENCODING is deprecated.
(node:8800) [DEP0010] DeprecationWarning: crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
(node:8800) [DEP0011] DeprecationWarning: crypto.Credentials is deprecated. Use tls.SecureContext instead.`

See [link](https://nodejs.org/api/deprecations.html)

**Comment by kilrau** [comment]
Let's try to update all outdated dependencies.
