### ISSUE TITLE
Order placement verification

### ISSUE THREAD

**Issue by offerm** [ExchangeUnion/xud#932]
I'm trying to place a buy and sell order for WETH/BTC. I see at least two issues here:
```
2019/05/01 05:51:27 [DEBUG] Placing order: {0.0305 350000000 WETH/BTC  BUY} 
2019/05/01 05:51:27 [ERROR] Could not place orders: {0.0305 350000000 0 WETH/BTC} - rpc error: code = Unknown desc = WETH outbound balance of 0 is not sufficient for order amount of 35
00000000000000000
```
- Since this is a BUY order, I would like to get WETH and pay with BTC. For that I don't need to have WETH outbound balance.
- This order should be prevented since I don't have any Raiden channel. 

```
2019/05/01 05:51:27 [DEBUG] Placing order: {0.0315 350000000 WETH/BTC  SELL} 
2019/05/01 05:51:27 [DEBUG] Order added: price:0.0315 quantity:350000000 pair_id:"WETH/BTC" id:"29384370-6bd5-11e9-b365-0db8c15a4f61" local_id:"29384370-6bd5-11e9-b365-0db8c15a4f61" cr
eated_at:1556689887527 side:SELL is_own_order:true 
```
- for this order I do need WETH balance (which I don't have).
- Should not be able to open this order as I don't have raiden channel.

Was done on xud1

**Comment by kilrau** [comment]
The same check on lightning e.g. with a LTC/BTC order works, correct? @offerm 

Sounds like an issue with the sanity checks on raiden @erkarl

**Comment by offerm** [comment]
I'm not sure if it is done correctly and all the BTC and LTC channels have both incoming and outgoing capacity.
Should be checked.

**Comment by kilrau** [comment]
Incoming can't be checked easily on lightning since no separate api call, only outgoing (local) and total channel balance as far as I'm aware. I'll wait for @erkarl to jump in.

**Comment by offerm** [comment]
`Incoming = total - outgoing `


easy to get localbalance and remote balance. 
```
        {
            "active": true,
            "remote_pubkey": "03114cda7206e92def08a35fc4039aba59394604fef9171ef19dbd5f938ce9387b",
            "channel_point": "2d160c7674e335becc707175f0702227d27aa8388f17a70993d6f3e8f94fd419:1",
            "chan_id": "532850822611337217",
            "capacity": "225000000000",
            "local_balance": "112500000000",
            "remote_balance": "112499963800",
            "commit_fee": "36200",
            "commit_weight": "724",
            "fee_per_kw": "50000",
            "unsettled_balance": "0",
            "total_satoshis_sent": "20",
            "total_satoshis_received": "20",
            "num_updates": "69",
            "pending_htlcs": [
            ],
            "csv_delay": 4693,
            "private": false
        }
```

**Comment by sangaman** [comment]
Looks like maybe there's a mixup somewhere in the balance check logic, I'll take a look.

FWIW we can definitely check the incoming available balance as well, but it's a little bit more involved (having to get all channels and loop through them, vs a single `ChannelBalance` call for outbound balance) and for the first phase we just went with outbound balance.

**Comment by sangaman** [comment]
I see the bug in the balance check logic, I'll open a PR to fix shortly.

**Comment by erkarl** [comment]
@offerm should now be fixed in master. Thanks @sangaman for the fix.
