### ISSUE TITLE
Integrate raiden swaps into simulation tests

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#933]

**Comment by offerm** [comment]
@moshe @kilrau we may be able to use the `sanity` swap as first step.
This is mainly ready so the main task is to check where we fail.

**Comment by sangaman** [comment]
Is this issue supposed to track raiden swap testing within the simulation tests? Or should we close in favor of #934?

**Comment by kilrau** [comment]
EDIT: this issue tracks
1. manual testing of raiden swap with logging of details where it fails
2. integration of raiden swap into simulation tests

so it's in addition to #934

**Comment by kilrau** [comment]
Also: let's discuss if it's possible to separate the raiden tests in the simulation framework, so that we could ask the raiden team to include these travis tests on their end.

**Comment by offerm** [comment]
@kilrau suggest to put this on hold. 

I'm working on the raiden integration into xud-simnet and there are multiple problem. Suggest you give me some time to make sure we are stable before we integrate it into the simulation tests.

Main problem now - a) retry for SanitySwap (WETH)  (@sangaman ) b) not passing secretHash for a WETH/BTC swap (@erkarl ).

**Comment by kilrau** [comment]
Ok, moved. Goes without saying, coordinate with @moshababo when you need his help for manual tests

**Comment by kilrau** [comment]
Moved to `1.0.0-bounty`, since @erkarl is almost there.

**Comment by kilrau** [comment]
bump

**Comment by kilrau** [comment]
Closing, PR merged https://github.com/ExchangeUnion/xud/pull/1195
