### ISSUE TITLE
Sanity swap - Raiden

### ISSUE THREAD

**Issue by offerm** [ExchangeUnion/xud#934]
The payment request to raiden should include a secrethash having length of 66 chars. 

Should include 0x at the beginning.

Raiden log:
```
{
  "node": "cdb6238c",
  "registry_address": "0x81E09B9Ba95c9D1fcC6Be59D7798eFB8E1EF342E",
  "token_address": "0x4c354C76d5f73A63a90Be776897DC81Fb6238772",
  "target_address": "0x7ed0299Fa1ADA71D10536B866231D447cDFa48b9",
  "amount": 1,
  "payment_identifier": 5321335948005626,
  "secret": null,
  "secret_hash": "6a47a3f0b2fa906a4c3b0bda5261e7b1ff8859546672858fcebf6e85ab6b4245",
  "event": "Initiating payment",
  "logger": "raiden.api.rest",
  "level": "debug",
  "timestamp": "2019-05-01 09:38:23.536048"
}
{
  "errors": "secret_hash length should be 66.",
  "status_code": 409,
  "event": "Error processing request",
  "logger": "raiden.api.rest",
  "level": "error",
  "timestamp": "2019-05-01 09:38:23.536454"
}
```

**Comment by offerm** [comment]
also, The amount here is `1 WETH` ?  this is very high.

**Comment by offerm** [comment]
Another comment here: 
The raiden code is not very mature with regards to error handling.  When things don't work well they just hang until expiration which can be 40-50 blocks away. This can take half an hour. 

To be on the safe side, before we attempt a sanity swap we should check:
- do we have a direct channel with the peer?
- do we have outgoing capacity on the channel?
- does the peer have outgoing capacity on its end? [This may not be needed but the peer will fail the channel anyway]

Only if the above is successful we should go to the sanity swap.

**Comment by sangaman** [comment]
I take it then that we should just be preprending "0x" to all `secret_hash` values sent to Raiden?

>  The amount here is 1 WETH ? this is very high.

Oh if that's the case then, I totally misunderstood the documentation then, based on the description and example here 
https://raiden-network.readthedocs.io/en/stable/rest_api.html#payments. The example used an `amount` of 200, too much to be denominated in WETH I thought, and I don't see any examples of fractional amounts. With sanity swaps I'm trying to send the smallest unit supported, gwei in this case.

> The raiden code is not very mature with regards to error handling. When things don't work well they just hang until expiration which can be 40-50 blocks away. This can take half an hour.
> 
> To be on the safe side, before we attempt a sanity swap we should check:
> 
>     do we have a direct channel with the peer?
>     do we have outgoing capacity on the channel?
>     does the peer have outgoing capacity on its end? [This may not be needed but the peer will fail the channel anyway]
> 
> Only if the above is successful we should go to the sanity swap.

If it's just the call that hangs, that shouldn't be a big problem as we time out the sanity swap anyway. If it causes Raiden to hang, I guess we can add in a set of temporary checks like you describe for Raiden, but it'd be kind of unfortunate to have to spend time developing and testing that only to throw away later. Ideally the sanity swaps themselves should determine whether we're able to swap with the peer.

**Comment by offerm** [comment]
We can try to see how it works and decide . Direct channel however is kind
of a must, currently.

Will check the amount later to be sure what 1 means. Will let you know.

**Comment by sangaman** [comment]
Sounds good to me.

**Comment by offerm** [comment]
So I can't pay 0.1 WETH.
I can pay 1.1 WETH but it looks like that only 1.0 was really paid. 

The code define the amount as int.

https://github.com/raiden-network/raiden/issues/3978

Lets use round numbers for now until this is clear.

Anyway, direct channel should be checked before doing the sanity payment and if this is done we can also check the balances.

**Comment by offerm** [comment]
So the numbers are in the smallest unit. 

1 is OK for Sanity swap.

**Comment by offerm** [comment]
@erkarl  when can we expect a fix for this (correct secrethash length and direct channel validation)?

**Comment by erkarl** [comment]
@offerm created https://github.com/ExchangeUnion/xud/pull/938 so that you wouldn't be blocked by this issue. You're not blocked by direct channels validations, right? Nevertheless, I'm planning on getting that done this week.

**Comment by erkarl** [comment]
@offerm In the latest master `37f543ef69e8bdfb33c97f35e0c85ca0c0f601d5` prepending `0x` to the `secret_hash` should now be automatic within the sanity swaps.

**Comment by offerm** [comment]
OK Thanks. Will check.

**Comment by offerm** [comment]
This one can be closed.
