### ISSUE TITLE
WETH - Quantity 

### ISSUE THREAD

**Issue by offerm** [ExchangeUnion/xud#935]
Trying to place a BUY and SELL orders for `WETH/BTC` via API:

		{
			price:    0.0305,
			quantity: 3.5*1E8,
			side:     xudrpc.OrderSide_BUY,
			pairId:	  "WETH/BTC",
		},
		{
			price:    0.0315,
			quantity: 3.5*1E8,
			side:     xudrpc.OrderSide_SELL,
			pairId:	  "WETH/BTC",
		},
 
The result:
```
Trading pair: WETH/BTC
┌────────────────────────────────────────────────────┬────────────────────────────────────────────────────┐
│ Buy                                                │ Sell                                               │
├───────────────────┬───────────────────┬────────────┼───────────────────┬───────────────────┬────────────┤
│ Quantity          │ Price             │ Own Order  │ Quantity          │ Price             │ Own Order  │
├───────────────────┼───────────────────┼────────────┼───────────────────┼───────────────────┼────────────┤
│                   │                   │            │ 3.50000000        │ 0.0315            │ X          │
└───────────────────┴───────────────────┴────────────┴───────────────────┴───────────────────┴────────────┘
```

The BUY order fails. Finding this in the log:

```
01/05/2019 13:31:27.360 [RPC] error: WETH outbound balance of 50 is not sufficient for order amount of 3500000000000000000
```

the channel has 50 WETH available.

**Comment by offerm** [comment]
As I learned here https://github.com/raiden-network/raiden/issues/3978 the validation looks good. 
I will recreate the channel with a correct amount.

@sangaman I placed the order with an amount of `3.5*1E8` and you got it as 3.5 WETH.  Is this OK?

When I open the channel with Raiden I have to use it as 3.5E18 and if I use the same notation with XUD the number will be 10^10 times larger. What do you think?

**Comment by kilrau** [comment]
Can this be closed? @offerm

**Comment by offerm** [comment]
@kilrau I'm still not happy that we are using 1E8 when we should be using 1E18. If you don't see a need for a change here we can close.

**Comment by kilrau** [comment]
Thinking about this, it's fairly important and avoids a breaking change on the grpc after 1.0.0. Closing this in favor of https://github.com/ExchangeUnion/xud/issues/952
