### ISSUE TITLE
Deploy Raiden Contract on Ropsten

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#951]
Features:
* on-chain fallback for swap, SHA256 (Done)
* no limits (Done)
* add support for [DAI](https://ropsten.etherscan.io/token/0xa1b8a2c7a942963165fe5747d3ea960070ea4dc7) & [WETH](https://ropsten.etherscan.io/token/0xc778417e063141139fce010982780140aa0cd5ab)

**Comment by kilrau** [comment]
As discussed in our call, we plan to base the contract off the [current mainnet contract](https://github.com/raiden-network/raiden-contracts/tree/fac73623d5b92b7c070fdde2b446648ec9117474/raiden_contracts/contracts).

**Comment by ImmanuelSegol** [comment]
@moshababo When you decide on the final limit please tag me its important for #948

**Comment by kilrau** [comment]
decision needed if we take this one or `develop` branch of raiden @offerm @moshababo

**Comment by kilrau** [comment]
Registering token networks is in the works (https://github.com/raiden-network/raiden-contracts/issues/646), thanks for pointing us at it @mat7ias !

**Comment by kilrau** [comment]
As check & fix raiden contract tests. If it's not trivial to do, let us know @moshababo

**Comment by kilrau** [comment]
Call: decision on which contract to use (v0.4.0 vs v0.24.0)

**Comment by offerm** [comment]
deployed on Ropsten: Version 0.4.0 without limits.
DAI and WETH registered. 
{
    "EndpointRegistry": "0xc890fF7f17A8C27651c1dC9483D941Bec5EDB386",
    "SecretRegistry": "0x10e6e104ff8D8a8AB019F0daA88aDa06f4DeF84D",
    "TokenNetworkRegistry": "0x84485026e44f0deF6965BA4bB1aDaEb9d0D695DA"
}

@kilrau anything else here or we can close?

**Comment by kilrau** [comment]
Nope, closing.
