### ISSUE TITLE
grpc: separate internal/external amount representation

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#952]
grpc (& CLI): decimals
internal: 1E8 integers for all coins and tokens (BTC/LTC/ERC20)

Motivation:
Currently it's 1E8 on the grpc [which is dangerous for ERC20 tokens](https://github.com/ExchangeUnion/xud/issues/935).

Notes:
* we decided to not represent ERC20 as 1E18 internally [since even bigint wouldn't be enough to store more than 1 digit amounts](https://github.com/ExchangeUnion/xud/issues/740#issuecomment-475992232))
* I still think that one class/module globally handling the decimal <-> integer conversion for grpc and cli is a good idea

**Comment by erkarl** [comment]
Think we can close this?

CC @sangaman

**Comment by kilrau** [comment]
Yes.
