### ISSUE TITLE
simulation tests: cannot start xud network

### ISSUE THREAD

**Issue by erkarl** [ExchangeUnion/xud#955]
I'm experiencing a possible race condition error in our simulation tests that causes the build to occasionally fail with the following output:
```
xud_test.go:92: xud process (4-Dave) did not shutdown gracefully. process (13835) killed
harnessTest.go:64: Error outside of test: *errors.errorString cannot start xud network: credentials: failed to append certificates
    /home/travis/build/ExchangeUnion/xud/test/simulation/xud_test.go:251 (0xa2df53)
      TestExchangeUnionDaemon: ht.Fatalf("cannot start xud network: %v", err)
    /home/travis/.gimme/versions/go1.12.linux.amd64/src/testing/testing.go:865 (0x4f96a0)
      tRunner: fn(t)
    /home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/asm_amd64.s:1337 (0x45d371)
      goexit: BYTE	$0x90	// NOP
```

**Comment by kilrau** [comment]
can you reliably reproduce that? @erkarl

**Comment by erkarl** [comment]
@kilrau no, that's what makes this difficult to debug and occasionally makes the simulation tests fail. I consider this a low priority, but it would be nice to have simulation tests produce consistent results.

**Comment by kilrau** [comment]
> I consider this a low priority, but it would be nice to have simulation tests produce consistent results.

Agree, that's why moved to `post-1.0.0`

**Comment by kilrau** [comment]
Did you see this too? @rsercano

**Comment by rsercano** [comment]
yes, in fact this's the reason why we get automated build fails; #1142 but I really don't know where it comes from. 

IMHO, this's a **file read** issue, if there's already a working test in VM, it opens the certificate file(s), if there's another build in the meantime, it tries to open it too, but since it's already opened by another build, it fails. But that's not a certain proved truth, that's just what I can think of about it.

**Comment by rsercano** [comment]
I implemented a simple logic to try to read cert files of node 3 times before exiting with an error.

**Comment by kilrau** [comment]
I assume this is gone in the recent simulation test fixes, if not please reopen @erkarl
