### ISSUE TITLE
xud-simnet BTC channels size

### ISSUE THREAD

**Issue by offerm** [ExchangeUnion/xud#967]
As we installed original LND  we now have this limitation:

```
[lncli] rpc error: code = Unknown desc = funding amount is too large, the max channel size is: 0.16777215 BTC
```

@kilrau let me know what you like to do about it.

Should I scale the channels management and order pacing down for the new capacity?

**Comment by kilrau** [comment]
Scale down for the new capacity, will partly close https://github.com/ExchangeUnion/xud/issues/948

**Comment by offerm** [comment]
So we have a channel of 0.16 BTC, we split capacity 0.08 and 0.08 between the parties.  Please also check the limitation on LTC channels. 

What should be the order size? 

Today, with a channel capacity of 2500000000 sat  we have these orders:
```
			price:    0.0077,
			quantity: 3.5*1E8,
			side:     xudrpc.OrderSide_BUY,
			pairId:	  "LTC/BTC",
		},
		{
			price:    0.0076,
			quantity: 15.5*1E8,
			side:     xudrpc.OrderSide_BUY,
			pairId:	  "LTC/BTC",
		},
		{
			price:    0.0075,
			quantity: 18.0*1E8,
			side:     xudrpc.OrderSide_BUY,
			pairId:	  "LTC/BTC",
		},
		{
			price:    0.0074,
			quantity: 21.25*1E8,
			side:     xudrpc.OrderSide_BUY,
			pairId:	  "LTC/BTC",
		},
		{
			price:    0.0073,
			quantity: 24.0*1E8,
			side:     xudrpc.OrderSide_BUY,
			pairId:	  "LTC/BTC",
		},
```

for LTC we currently have 225000000000 capacity.

**Comment by kilrau** [comment]
> So we have a channel of 0.16 BTC, we split capacity 0.08 and 0.08 between the parties

Yep.

> Please also check the limitation on LTC channels.

As per https://github.com/lightningnetwork/lnd/pull/1246 : `maxLtcFundingAmount = maxBtcFundingAmount * btcToLtcConversionRate` whereas is hardcoded as `btcToLtcConversionRate = 60` which leaves us with a max channel size of 9.6 LTC.

> What should be the order size?

BTC Old: 2500000000 New: 16000000 - divide order sizes by 156
LTC Old: 225000000000 New: 960000000 - divide order sizes by 234

Please check if that makes sense @offerm

**Comment by offerm** [comment]
Math wize yes.

Business wize - not really.

**Comment by kilrau** [comment]
Meaning you would rather maintain a fork to lift these limits from the get go? I wouldn't feel comfortable with that (https://github.com/lightningnetwork/lnd/pull/1246).

**Comment by offerm** [comment]
Yes. At least for simnet.
We can take the same LND branch and patch it before we build.

**Comment by kilrau** [comment]
Patch lnd latest release with increased limits for Simnet: fine with me. If the overhead is acceptable, go ahead and do it @offerm

**Comment by offerm** [comment]
done. Will share "how to do it" once simnet is stable again.

**Comment by kilrau** [comment]
Working.
