### ISSUE TITLE
Simnet sanity swap fails due to FinalExpiryTooSoon (cltv calc wrong!?)

### ISSUE THREAD

**Issue by erkarl** [ExchangeUnion/xud#977]
Reported by Offer for simnet BTC:

```
24/05/2019 10:30:41.875 [SWAPS] warn: got payment error during sanity swap with 028599d05b18c0c3f8028915a17d603416f7276c822b6b2d20e71a3502bd0f9e0a for BTC using rHash 1dfddc15739f787e5
42f6e8a23c2462bbe29731babb2de981ef984b6639e9821: FinalExpiryTooSoon
```

Also, Offerm:
> I managed to have it working with direct channels.
> My recommendation is to execute the sanity swap (non blocking, once per connection) with the same code/logic that we are using for a regular swap.
> Swap should not be attempted if there is no channel and if there is no route.

**Comment by kilrau** [comment]
seems cltv's are not being calculated correctly on a multi-hop route

**Comment by kilrau** [comment]
Moving this back into `1.0.0-testnet` since this could potentially mean loss of funds.

**Comment by kilrau** [comment]
Let's check if this issue still exists and close if not @erkarl
