### ISSUE TITLE
Sanity Swaps fixes

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#988]
The idea for sanity swaps: setup htlcs, but don't release preimage. Swap partner has to be aware that this is the sanity swap test to not punish us for this behavior. Make sure this doesn't make it into the reputation system. Reason: routing fees would make sanity swaps (e.g. 1 sat for 1 sat) cost money if preimage was released.

**Comment by sangaman** [comment]
I'm thinking (and my understanding based on what @offerm said) that we can do this even for single-hop payments. The idea being that once all the HTLCs are constructed, we can just fail the payment and treat errors for unknown payment hash as if it were a successful swap.

**Comment by kilrau** [comment]
Discussion: in general yes, we want this

Todo:
- enable config option, mark as experimental
- failure should be "preimage not found"
