### ISSUE TITLE
Logger contexts

### ISSUE THREAD

**Issue by moshababo** [ExchangeUnion/xud#99]
New `Logger` contexts are to be define, in addition to GLOBAL: DB, RPC, P2P, ORDERBOOK, LND, RAIDEN.
They should all have a static instance defined on `Logger` class, that should be used by the appropriate components, instead of `Logger.global`. 
They should all map to the same output file for now, same as GLOBAL (`xud.log`), but should have a unique output format : `[CONTEXT] ...`

**Comment by michael1011** [comment]
I think this issue can be closed?

**Comment by moshababo** [comment]
Yes.
