### ISSUE TITLE
Litecoin on Simnet is breaking

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#996]

**Comment by sangaman** [comment]
It was working for me (even with the newer version of lnd and the rebooted chain) as of about a week ago but I can't get lnd to start now. I haven't looked into it closely yet.

**Comment by kilrau** [comment]
https://github.com/ExchangeUnion/xud-simnet/issues/29

**Comment by kilrau** [comment]
Fixed, tested today.
